package cli

import (
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Goldziher/ai-rulez/v5/tests/e2e/testutil"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const guardProjectConfig = `version = "5.0"
agents_md = false
name = "guard-e2e"
presets = ["claude", "codex", "gemini", "cursor", "opencode"]

[guard]
generated = true
command = ["ai-rulez"]
`

// runGuard pipes a hook payload into `ai-rulez guard` and returns its exit code and stderr.
func runGuard(t *testing.T, dir, payload string) (int, string) {
	t.Helper()
	//nolint:gosec // G204: the test runs the binary it just built
	cmd := exec.Command(testutil.SetupTestBinary(t), "guard")
	cmd.Dir = dir
	cmd.Stdin = strings.NewReader(payload)
	var stderr strings.Builder
	cmd.Stderr = &stderr
	err := cmd.Run()
	var exitErr *exec.ExitError
	if errors.As(err, &exitErr) {
		return exitErr.ExitCode(), stderr.String()
	}
	require.NoError(t, err)
	return 0, stderr.String()
}

func TestGuardE2E_GenerateThenBlockGeneratedEdits(t *testing.T) {
	t.Cleanup(testutil.CleanupTestBinary)
	dir := testutil.CreateTempDir(t)
	require.NoError(t, os.MkdirAll(filepath.Join(dir, ".ai-rulez", "rules"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(dir, ".ai-rulez", "config.toml"), []byte(guardProjectConfig), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(dir, ".ai-rulez", "rules", "style.md"), []byte("# style\n\nBe terse.\n"), 0o644))
	testutil.RunCLIExpectSuccess(t, dir, "generate", "--yes")

	// The hooks are in the harness settings files.
	for _, rel := range []string{".claude/settings.json", ".codex/hooks.json", ".gemini/settings.json", ".cursor/hooks.json"} {
		data, err := os.ReadFile(filepath.Join(dir, filepath.FromSlash(rel)))
		require.NoError(t, err, rel)
		assert.Contains(t, string(data), "ai-rulez guard", rel)
	}

	tests := []struct {
		name       string
		payload    string
		wantCode   int
		wantStderr string
	}{
		{name: "generated rule is blocked and names its source",
			payload:  `{"tool_name":"Edit","tool_input":{"file_path":".claude/rules/style.md"}}`,
			wantCode: 2, wantStderr: ".ai-rulez/rules/style.md"},
		{name: "generated instructions file is blocked", payload: `{"tool_name":"Write","tool_input":{"file_path":"CLAUDE.md"}}`,
			wantCode: 2, wantStderr: "CLAUDE.md is generated by ai-rulez"},
		{name: "merged settings document is allowed", payload: `{"tool_name":"Edit","tool_input":{"file_path":".claude/settings.json"}}`},
		{name: "source file is allowed", payload: `{"tool_name":"Edit","tool_input":{"file_path":".ai-rulez/rules/style.md"}}`},
		{name: "malformed payload is allowed", payload: `{`},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			code, stderr := runGuard(t, dir, tt.payload)

			assert.Equal(t, tt.wantCode, code)
			assert.Contains(t, stderr, tt.wantStderr)
		})
	}
}
