version: "2"

run:
    go: '1.24'

linters:
    default: none
    enable:
        - asasalint
        - bidichk
        - decorder
        - dupword
        - durationcheck
        - errcheck
        - errorlint
        - exhaustive
        - goconst
        - gocritic
        # - godot  # Disabled: Don't require periods at end of comments
        - goheader
        - gomodguard
        - goprintffuncname
        - gosec
        - govet
        - ineffassign
        - misspell
        - nilnil
        - nolintlint
        - prealloc
        - predeclared
        - reassign
        - revive
        - sqlclosecheck
        - staticcheck
        - tagalign
        - testpackage  # Keep enabled: tests should be in separate package
        - thelper
        - unconvert
        - unparam
        - unused
        - usestdlibvars
        - wastedassign
        - whitespace
    settings:
        revive:
            enable-all-rules: true
            rules:
                - name: file-header
                  disabled: true
                - name: unchecked-type-assertion
                  disabled: true
                - name: comment-spacings
                  disabled: true
                - name: function-length
                  disabled: true
                - name: banned-characters
                  disabled: true
                - name: add-constant
                  disabled: true
                - name: line-length-limit
                  disabled: true
                - name: flag-parameter
                  disabled: true
                - name: deep-exit
                  disabled: true
                - name: cyclomatic
                  arguments: [25]
                - name: cognitive-complexity
                  arguments: [25]
                - name: max-public-structs
                  disabled: true
                - name: function-result-limit
                  arguments: [2]
                - name: argument-limit
                  arguments: [5]
                - name: var-naming
                  disabled: true  # Allow underscores in package names (ai_rules)
                - name: package-comments
                  disabled: true  # Don't require package comments for main
        goconst:
            ignore-tests: true
        govet:
            check-shadowing: true
            disable-all: true
        gosec:
            excludes:
                - G301  # Directory permissions 0755 are acceptable
                - G304  # File path provided as argument is acceptable
                - G306  # File permissions 0644 are acceptable
        decorder:
            dec-order:
                - const
                - type
                - var
                - func
        maintidx:
            min-index: 80
    exclusions:
        fix: true