version: "2"

run:
  go: '1.24'
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - goconst

linters-settings:
  govet:
    shadow: true
  goconst:
    ignore-tests: true

issues:
  exclude-rules:
    - path: vendor/
    - path: build/