project_name: ai-rulez

before:
  hooks:
    - go mod download

builds:
  - id: ai-rulez
    binary: ai-rulez
    main: .
    env:
      - CGO_ENABLED=0
      - GOPROXY=direct
      - GOSUMDB=off
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: Goldziher
    name: ai-rulez

# Temporarily disabled for Homebrew testing
# nfpms:
#   - id: packages
#     description: "AI rules configuration management tool"
#     maintainer: "Goldziher"
#     license: "MIT"
#     formats:
#       - deb
#       - rpm
#       - apk

brews:
  - name: ai-rulez
    description: "⚡ Lightning-fast CLI tool (written in Go) for managing AI assistant rules"
    homepage: "https://github.com/Goldziher/ai-rulez"
    license: "MIT"
    tap:
      owner: Goldziher
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    install: |
      bin.install "ai-rulez"
    test: |
      system "#{bin}/ai-rulez", "--version"