project_name: airules

before:
  hooks: []

builds:
  - id: airules
    binary: airules
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: Goldziher
    name: airules

nfpms:
  - id: packages
    description: "AI rules configuration management tool"
    maintainer: "Goldziher"
    license: "MIT"
    formats:
      - deb
      - rpm
      - apk