# Pre-commit hooks for ai-rulez
# Usage: Add this to your .pre-commit-config.yaml:
#
# repos:
#   - repo: https://github.com/Goldziher/ai-rulez
#     rev: v1.0.0  # Use the latest version
#     hooks:
#       - id: ai-rulez-generate
#
- id: ai-rulez-validate
  name: Validate AI rulez configuration
  description: Validate ai-rulez configuration files and ensure they would generate successfully
  entry: ai-rulez generate --dry-run
  language: golang
  additional_dependencies: []
  files: '\.(ai-rulez|ai_rulez)\.(yaml|yml)$|^\.ai-rulez\.(yaml|yml)$|^ai-rulez\.(yaml|yml)$'
  pass_filenames: false
  always_run: false
  require_serial: false

- id: ai-rulez-generate
  name: Generate AI assistant configuration files
  description: Generate AI assistant configuration files from ai-rulez configuration
  entry: ai-rulez generate
  language: golang
  additional_dependencies: []
  files: '\.(ai-rulez|ai_rulez)\.(yaml|yml)$|^\.ai-rulez\.(yaml|yml)$|^ai-rulez\.(yaml|yml)$'
  pass_filenames: false
  always_run: false
  require_serial: false

- id: ai-rulez-recursive
  name: Generate AI assistant files (recursive)
  description: Generate all ai-rulez output files in the repository recursively
  entry: ai-rulez generate --recursive
  language: golang
  additional_dependencies: []
  files: '\.(ai-rulez|ai_rulez)\.(yaml|yml)$|^\.ai-rulez\.(yaml|yml)$|^ai-rulez\.(yaml|yml)$'
  pass_filenames: false
  always_run: false
  require_serial: false