#!/usr/bin/env bats
# The Cline hook wrappers ai-rulez emits (internal/generator/settings/hooks_cline.go).
#
# setup_file renders them through the binary into a scratch project whose path holds a space and
# a quote, with HOME and XDG redirected; the tests then run the emitted scripts as Cline would:
# hook JSON on stdin, the last command's stdout as the hook's output.

bats_require_minimum_version 1.5.0

setup_file() {
  bats_load_library xberg-bats
  load "${BATS_TEST_DIRNAME}/../helpers/common"
  isolate_home "$BATS_FILE_TMPDIR"

  export PROJECT="$BATS_FILE_TMPDIR/proj o'brien dir"
  make_project "$PROJECT" '"cline"' "$(
    cat <<'EOF'
[[hooks]]
event = "PreToolUse"
[[hooks.hooks]]
script = "scripts/guard.sh"
args = ["a b", "it's", "$HOME"]
[[hooks.hooks]]
command = "cat; exit ${LAST_EXIT:-0}"

[[hooks]]
event = "UserPromptSubmit"
[[hooks.hooks]]
command = "cat # a trailing comment must not swallow the closing brace"
EOF
  )"
  mkdir -p "$PROJECT/scripts"
  printf '%s\n' '#!/bin/sh' \
    '{ printf "args:"; for a in "$@"; do printf " [%s]" "$a"; done; printf "\n"; printf "stdin:"; cat; } >>"$HOOK_LOG"' \
    'echo "guard stdout"' \
    'exit "${GUARD_EXIT:-0}"' >"$PROJECT/scripts/guard.sh"
  chmod +x "$PROJECT/scripts/guard.sh"

  (cd "$PROJECT" && "$(ai_rulez_bin)" generate --yes) >"$BATS_FILE_TMPDIR/generate.log" 2>&1 || {
    cat "$BATS_FILE_TMPDIR/generate.log" >&2
    return 1
  }
  export HOOK="$PROJECT/.clinerules/hooks/PreToolUse"
  export PROMPT_HOOK="$PROJECT/.clinerules/hooks/UserPromptSubmit"
}

setup() {
  bats_load_library xberg-bats
  load "${BATS_TEST_DIRNAME}/../helpers/common"
  xberg_setup
  export HOOK_LOG="$BATS_TEST_TMPDIR/hook.log"
  INPUT='{"tool":"Bash","command":"echo $(id) `id` %s \\ done"}'
  unset GUARD_EXIT LAST_EXIT
}

# Run a hook with $INPUT on stdin.
run_hook() {
  local hook="$1"
  shift
  run "$@" "$hook" <<<"$INPUT"
}

@test "each event gets one executable POSIX sh script marked as generated" {
  local hook
  for hook in "$HOOK" "$PROMPT_HOOK"; do
    [ -x "$hook" ]
    [ "$(sed -n 1p "$hook")" = "#!/bin/sh" ]
    sed -n 2p "$hook" | grep -q '^# Generated by ai-rulez'
    sh -n "$hook"
  done
}

@test "every command gets the hook input and the last one's output is the hook's output" {
  run_hook "$HOOK"

  xberg_assert_status 0
  xberg_assert_output "$INPUT"
  xberg_assert_file "$HOOK_LOG" "$(printf '%s\n' "args: [a b] [it's] [\$HOME]" "stdin:$INPUT")"
}

@test "an earlier command's stdout is not part of the hook output" {
  run_hook "$HOOK"

  [[ "$output" != *"guard stdout"* ]]
}

@test "the project root resolves from the script's location, from any working directory" {
  cd "$BATS_TEST_TMPDIR"
  run_hook "$HOOK"
  xberg_assert_status 0

  cd "$PROJECT"
  run_hook .clinerules/hooks/PreToolUse
  xberg_assert_status 0
  xberg_assert_output "$INPUT"
}

@test "a failing earlier command stops the rest and its status is the hook's status" {
  export GUARD_EXIT=7

  run_hook "$HOOK"

  xberg_assert_status 7
  xberg_assert_no_output
}

@test "the last command's status is the hook's status" {
  export LAST_EXIT=5

  run_hook "$HOOK"

  xberg_assert_status 5
  xberg_assert_output "$INPUT"
}

@test "a trailing comment in a command does not swallow the group's closing brace" {
  run_hook "$PROMPT_HOOK"

  xberg_assert_status 0
  xberg_assert_output "$INPUT"
}

@test "a missing project script fails the hook instead of passing silently" {
  mv "$PROJECT/scripts/guard.sh" "$BATS_TEST_TMPDIR/guard.sh"

  run_hook "$HOOK" -127
  local got="$status"
  mv "$BATS_TEST_TMPDIR/guard.sh" "$PROJECT/scripts/guard.sh"

  [ "$got" -eq 127 ]
}

@test "an exported CDPATH does not corrupt the project root when the hook is run by a relative path" {
  cd "$PROJECT"
  export CDPATH=".:$BATS_TEST_TMPDIR"

  run_hook .clinerules/hooks/PreToolUse

  xberg_assert_status 0
  xberg_assert_output "$INPUT"
}

@test "a user-scope hook addresses its script by an absolute path that may contain spaces" {
  local home="$BATS_TEST_TMPDIR/user home"
  mkdir -p "$home/.config/ai-rulez/hooks"
  printf '%s\n' 'version = "5.0"' 'name = "user"' 'presets = ["cline"]' '[[hooks]]' 'event = "PreToolUse"' \
    '[[hooks.hooks]]' 'script = "hooks/guard.sh"' >"$home/.config/ai-rulez/config.toml"
  cp "$PROJECT/scripts/guard.sh" "$home/.config/ai-rulez/hooks/guard.sh"
  HOME="$home" XDG_CONFIG_HOME="$home/.config" XDG_CACHE_HOME="$home/.cache" \
    XDG_DATA_HOME="$home/.local/share" XDG_STATE_HOME="$home/.local/state" \
    run "$(ai_rulez_bin)" generate --user --yes
  xberg_assert_status 0

  cd "$BATS_TEST_TMPDIR"
  run_hook "$home/Documents/Cline/Hooks/PreToolUse"

  xberg_assert_status 0
  xberg_assert_output "guard stdout"
  xberg_assert_file "$HOOK_LOG" "$(printf '%s\n' "args:" "stdin:$INPUT")"
}
