package guard

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/Goldziher/ai-rulez/v5/internal/testutil"
)

const manifestBody = `{"version":"1","files":["AGENTS.md","CLAUDE.md",".claude/rules/style.md",".claude/settings.json",".vscode/settings.json"],
"merged":{".claude/settings.json":[{"path":["hooks"]}]}}`

const localManifestBody = `{"version":"1","files":["CLAUDE.local.md"]}`

func newProject(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	if real, err := filepath.EvalSymlinks(root); err == nil {
		root = real
	}
	write := func(rel, body string) {
		path := filepath.Join(root, filepath.FromSlash(rel))
		require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
		require.NoError(t, os.WriteFile(path, []byte(body), 0o644))
	}
	write(".ai-rulez/.generated-manifest.json", manifestBody)
	write(".ai-rulez/.generated-manifest.local.json", localManifestBody)
	write("AGENTS.md", "<!--\nGenerated by ai-rulez. Edit the source, not this file.\n-->\n")
	write(".claude/rules/style.md", "<!--\nGenerated by ai-rulez from .ai-rulez/rules/style.md. Edit the source, not this file.\n-->\n")
	write("src/main.go", "package main\n")
	return root
}

func TestCheck(t *testing.T) {
	root := newProject(t)
	abs := filepath.Join(root, "AGENTS.md")
	tests := []struct {
		name       string
		payload    string
		cwd        string
		wantBlock  bool
		wantPath   string
		wantSource string
	}{
		{name: "claude edit of a generated file", payload: `{"tool_name":"Edit","tool_input":{"file_path":"` + esc(abs) + `"}}`,
			wantBlock: true, wantPath: "AGENTS.md"},
		{name: "relative path resolves against the payload cwd", payload: `{"tool_name":"Write","tool_input":{"file_path":"CLAUDE.md"},"cwd":"` + esc(root) + `"}`,
			wantBlock: true, wantPath: "CLAUDE.md"},
		{name: "relative path resolves against the process cwd", payload: `{"tool_name":"Write","tool_input":{"file_path":"CLAUDE.md"}}`,
			cwd: root, wantBlock: true, wantPath: "CLAUDE.md"},
		{name: "names the source from the banner", payload: `{"tool_name":"MultiEdit","tool_input":{"file_path":".claude/rules/style.md"},"cwd":"` + esc(root) + `"}`,
			wantBlock: true, wantPath: ".claude/rules/style.md", wantSource: ".ai-rulez/rules/style.md"},
		{name: "machine-local manifest is consulted", payload: `{"tool_name":"Write","tool_input":{"file_path":"CLAUDE.local.md"},"cwd":"` + esc(root) + `"}`,
			wantBlock: true, wantPath: "CLAUDE.local.md"},
		{name: "gemini write_file", payload: `{"tool_name":"write_file","tool_input":{"file_path":"AGENTS.md"},"cwd":"` + esc(root) + `"}`,
			wantBlock: true, wantPath: "AGENTS.md"},
		{name: "cursor path key", payload: `{"tool_name":"Write","tool_input":{"path":"AGENTS.md"},"cwd":"` + esc(root) + `"}`,
			wantBlock: true, wantPath: "AGENTS.md"},
		{name: "codex apply_patch names files in the patch",
			payload:   `{"tool_name":"apply_patch","tool_input":{"command":"*** Begin Patch\n*** Update File: src/main.go\n*** Update File: AGENTS.md\n*** End Patch"},"cwd":"` + esc(root) + `"}`,
			wantBlock: true, wantPath: "AGENTS.md"},
		{name: "copilot toolArgs as an object", payload: `{"toolName":"edit","toolArgs":{"path":"AGENTS.md"},"cwd":"` + esc(root) + `"}`,
			wantBlock: true, wantPath: "AGENTS.md"},
		{name: "copilot toolArgs as a JSON string", payload: `{"toolName":"create","toolArgs":"{\"path\":\"AGENTS.md\"}","cwd":"` + esc(root) + `"}`,
			wantBlock: true, wantPath: "AGENTS.md"},
		{name: "copilot read tool is allowed", payload: `{"toolName":"view","toolArgs":{"path":"AGENTS.md"},"cwd":"` + esc(root) + `"}`},
		{name: "dot dot segments are cleaned", payload: `{"tool_name":"Edit","tool_input":{"file_path":"src/../src/../AGENTS.md"},"cwd":"` + esc(root) + `"}`,
			wantBlock: true, wantPath: "AGENTS.md"},
		{name: "cwd in a subdirectory finds the project", payload: `{"tool_name":"Edit","tool_input":{"file_path":"../AGENTS.md"},"cwd":"` + esc(filepath.Join(root, "src")) + `"}`,
			wantBlock: true, wantPath: "AGENTS.md"},
		{name: "partially owned merged document is allowed", payload: `{"tool_name":"Edit","tool_input":{"file_path":".claude/settings.json"},"cwd":"` + esc(root) + `"}`},
		{name: "ordinary source file is allowed", payload: `{"tool_name":"Edit","tool_input":{"file_path":"src/main.go"},"cwd":"` + esc(root) + `"}`},
		{name: "reading a generated file is allowed", payload: `{"tool_name":"Read","tool_input":{"file_path":"AGENTS.md"},"cwd":"` + esc(root) + `"}`},
		{name: "a shell call is allowed", payload: `{"tool_name":"Bash","tool_input":{"command":"cat AGENTS.md"},"cwd":"` + esc(root) + `"}`},
		{name: "path outside the project is allowed", payload: `{"tool_name":"Edit","tool_input":{"file_path":"/etc/AGENTS.md"},"cwd":"` + esc(root) + `"}`},
		{name: "traversal out of the project is allowed", payload: `{"tool_name":"Edit","tool_input":{"file_path":"../AGENTS.md"},"cwd":"` + esc(root) + `"}`},
		{name: "no file path is allowed", payload: `{"tool_name":"Edit","tool_input":{}}`, cwd: root},
		{name: "malformed JSON fails open", payload: `{"tool_name":`, cwd: root},
		{name: "empty stdin fails open", payload: ``, cwd: root},
		{name: "non-object input fails open", payload: `{"tool_name":"Edit","tool_input":"AGENTS.md"}`, cwd: root},
		{name: "no project fails open", payload: `{"tool_name":"Edit","tool_input":{"file_path":"AGENTS.md"},"cwd":"` + esc(t.TempDir()) + `"}`},
		{name: "relative cwd fails open", payload: `{"tool_name":"Edit","tool_input":{"file_path":"AGENTS.md"},"cwd":"."}`},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Act
			got := Check(strings.NewReader(tt.payload), tt.cwd)

			// Assert
			assert.Equal(t, tt.wantBlock, got.Block)
			assert.Equal(t, tt.wantPath, got.Path)
			assert.Equal(t, tt.wantSource, got.Source)
		})
	}
}

func TestCheck_SymlinkAndOversizedPayload(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("symlinks need privileges on Windows")
	}
	root := newProject(t)
	outside := t.TempDir()
	testutil.SymlinkOrSkip(t, filepath.Join(root, "AGENTS.md"), filepath.Join(root, "src", "link.md"))
	testutil.SymlinkOrSkip(t, root, filepath.Join(outside, "project"))
	testutil.SymlinkOrSkip(t, outside, filepath.Join(root, "src", "outside"))
	require.NoError(t, os.WriteFile(filepath.Join(outside, "AGENTS.md"), []byte("x"), 0o644))

	tests := []struct {
		name      string
		file      string
		wantBlock bool
		wantPath  string
	}{
		{name: "a link to a generated file", file: "src/link.md", wantBlock: true, wantPath: "AGENTS.md"},
		{name: "a link to the project through another directory", file: filepath.Join(outside, "project", "AGENTS.md"), wantBlock: true, wantPath: "AGENTS.md"},
		{name: "a link out of the project to a same-named file", file: "src/outside/AGENTS.md"},
		{name: "a new file below a linked directory", file: filepath.Join(outside, "project", "CLAUDE.md"), wantBlock: true, wantPath: "CLAUDE.md"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Act
			got := Check(strings.NewReader(`{"tool_name":"Edit","tool_input":{"file_path":"`+esc(tt.file)+`"},"cwd":"`+esc(root)+`"}`), root)

			// Assert
			assert.Equal(t, tt.wantBlock, got.Block)
			assert.Equal(t, tt.wantPath, got.Path)
		})
	}

	t.Run("an oversized payload is blocked", func(t *testing.T) {
		big := `{"tool_name":"apply_patch","tool_input":{"command":"*** Update File: AGENTS.md\n` + strings.Repeat("a", maxPayload) + `"},"cwd":"` + esc(root) + `"}`
		got := Check(strings.NewReader(big), root)
		assert.True(t, got.Block)
		assert.Contains(t, got.Message(), "larger than")
	})
}

func patchPayload(root string, lines []string) string {
	body := "*** Begin Patch\n" + strings.Join(lines, "\n") + "\n*** End Patch"
	b, _ := json.Marshal(map[string]any{"tool_name": "apply_patch", "tool_input": map[string]any{"command": body}, "cwd": root})
	return string(b)
}

func TestCheck_LargePatches(t *testing.T) {
	root := newProject(t)
	many := func(n int, distinct bool) []string {
		lines := make([]string, 0, n+1)
		for i := 0; i < n; i++ {
			name := "src/same.go"
			if distinct {
				name = fmt.Sprintf("src/f%d.go", i)
			}
			lines = append(lines, "*** Add File: "+name)
		}
		return append(lines, "*** Update File: AGENTS.md")
	}
	tests := []struct {
		name      string
		lines     []string
		wantBlock bool
		wantPath  string
		wantMsg   string
	}{
		{name: "duplicates are collapsed before the generated file is found", lines: many(280000, false), wantBlock: true, wantPath: "AGENTS.md"},
		{name: "a patch within the cap still finds the generated file", lines: many(maxTargets-2, true), wantBlock: true, wantPath: "AGENTS.md"},
		{name: "more distinct files than the cap is blocked", lines: many(maxTargets+5, true), wantBlock: true, wantMsg: "more than"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Arrange
			payload := patchPayload(root, tt.lines)

			// Act
			start := time.Now()
			got := Check(strings.NewReader(payload), root)

			// Assert
			assert.Less(t, time.Since(start), time.Second, "a large patch must not outlast the harness timeout")
			assert.Equal(t, tt.wantBlock, got.Block)
			assert.Equal(t, tt.wantPath, got.Path)
			assert.Contains(t, got.Message(), tt.wantMsg)
		})
	}
}

func BenchmarkCheck_LargePatch(b *testing.B) {
	root := b.TempDir()
	_ = os.MkdirAll(filepath.Join(root, ".ai-rulez"), 0o755)
	_ = os.WriteFile(filepath.Join(root, ".ai-rulez", manifestName), []byte(manifestBody), 0o644)
	lines := make([]string, 0, 500)
	for i := 0; i < 500; i++ {
		lines = append(lines, fmt.Sprintf("*** Add File: src/f%d.go", i))
	}
	payload := patchPayload(root, lines)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		Check(strings.NewReader(payload), root)
	}
}

func TestCheck_CorruptManifestFailsOpen(t *testing.T) {
	root := newProject(t)
	require.NoError(t, os.WriteFile(filepath.Join(root, ".ai-rulez", ".generated-manifest.json"), []byte("{not json"), 0o644))
	require.NoError(t, os.Remove(filepath.Join(root, ".ai-rulez", ".generated-manifest.local.json")))

	got := Check(strings.NewReader(`{"tool_name":"Edit","tool_input":{"file_path":"AGENTS.md"},"cwd":"`+esc(root)+`"}`), root)

	assert.False(t, got.Block)
}

func TestDecisionMessage(t *testing.T) {
	tests := []struct {
		name     string
		decision Decision
		want     []string
	}{
		{name: "with a source", decision: Decision{Block: true, Path: "AGENTS.md", Source: ".ai-rulez/rules/a.md"},
			want: []string{"AGENTS.md is generated", "Edit its source .ai-rulez/rules/a.md", "ai-rulez generate", "ai-rulez skill"}},
		{name: "without a source", decision: Decision{Block: true, Path: "AGENTS.md"},
			want: []string{"AGENTS.md is generated", "matching source under .ai-rulez/", "ai-rulez skill"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := tt.decision.Message()
			for _, w := range tt.want {
				assert.Contains(t, got, w)
			}
		})
	}
}

// esc escapes a path for a JSON string literal.
func esc(p string) string { return strings.ReplaceAll(p, `\`, `\\`) }

func TestCheck_ProjectFromTheTargetAndPatchShapes(t *testing.T) {
	root := newProject(t)
	abs := filepath.Join(root, "AGENTS.md")
	other := filepath.Join(filepath.Dir(root), "sibling")
	require.NoError(t, os.MkdirAll(other, 0o755))
	patch := `*** Begin Patch\n*** Update File: AGENTS.md\n*** End Patch`
	tests := []struct {
		name      string
		payload   string
		cwd       string
		wantBlock bool
	}{
		{"payload cwd outside the project, absolute target inside", `{"tool_name":"Edit","tool_input":{"file_path":"` + esc(abs) + `"},"cwd":"` + esc(other) + `"}`, "", true},
		{"process cwd outside the project, absolute target inside", `{"tool_name":"Write","tool_input":{"file_path":"` + esc(abs) + `"}}`, other, true},
		{"relative traversal into the project from an outside cwd", `{"tool_name":"Edit","tool_input":{"file_path":"` + esc(filepath.Join("..", filepath.Base(root), "AGENTS.md")) + `"},"cwd":"` + esc(other) + `"}`, "", true},
		{"codex command array", `{"tool_name":"apply_patch","tool_input":{"command":["apply_patch","` + patch + `"]},"cwd":"` + esc(root) + `"}`, "", true},
		{"indented patch marker", `{"tool_name":"apply_patch","tool_input":{"input":"  *** Begin Patch\n   *** Update File: AGENTS.md\n"},"cwd":"` + esc(root) + `"}`, "", true},
		{"oversized read is allowed", `{"tool_name":"Read","tool_input":{"file_path":"AGENTS.md","pad":"` + strings.Repeat("a", maxPayload) + `"},"cwd":"` + esc(root) + `"}`, "", false},
		{"oversized edit is blocked", `{"tool_name":"Edit","tool_input":{"file_path":"src/main.go","pad":"` + strings.Repeat("a", maxPayload) + `"}}`, "", true},
		{"oversized payload naming no tool is blocked", `{"tool_input":{"pad":"` + strings.Repeat("a", maxPayload) + `"}}`, "", true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Act
			got := Check(strings.NewReader(tt.payload), tt.cwd)

			// Assert
			assert.Equal(t, tt.wantBlock, got.Block)
		})
	}
}

func TestCheck_CaseInsensitiveFileSystemsFoldTheRoot(t *testing.T) {
	if runtime.GOOS != "darwin" && runtime.GOOS != "windows" {
		t.Skip("paths are case-sensitive here")
	}
	root := newProject(t)
	altered := strings.ToUpper(root[:len(root)-1]) + root[len(root)-1:]
	payload := `{"tool_name":"Edit","tool_input":{"file_path":"` + esc(filepath.Join(altered, "AGENTS.md")) + `"},"cwd":"` + esc(root) + `"}`

	// Act
	got := Check(strings.NewReader(payload), root)

	// Assert
	assert.True(t, got.Block)
	assert.Equal(t, "AGENTS.md", got.Path)
}
