// Package guard decides whether an agent's tool call edits a file ai-rulez
// generated. It backs `ai-rulez guard`, the PreToolUse hook that [guard] generated
// adds to each harness: the hook payload arrives on stdin and a blocked call exits
// with code 2 and the reason on stderr.
//
// The guard fails open on its own errors. A payload it cannot parse, a project it
// cannot find and a path outside the project all allow the call: a guard that wedges
// the agent on its own error is worse than the hand edit it prevents, and
// `ai-rulez verify` still catches the edit afterwards. It does not fail open on
// input it chooses not to analyze: a payload over maxPayload or a call naming more
// than maxTargets files is blocked, because padding a patch must not be a bypass.
package guard

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"

	"github.com/Goldziher/ai-rulez/v5/internal/gitutil"
)

// ExitBlock is the exit code every supported harness reads as "block this tool call".
const ExitBlock = 2

const (
	configDirName     = ".ai-rulez"
	manifestName      = ".generated-manifest.json"
	localManifestName = ".generated-manifest.local.json"
	// maxPayload bounds stdin; an apply_patch payload carries the whole patch.
	maxPayload = 8 << 20
	// maxTargets bounds the distinct files one call may name; more is blocked.
	maxTargets = 1000
	// headerBytes is how much of a generated file is searched for its banner.
	headerBytes = 4096
)

// Decision is the guard's verdict on one tool call.
type Decision struct {
	// Block is true when the call edits a generated file.
	Block bool
	// Path is the project-relative, slash-separated path that was blocked.
	Path string
	// Source is the source file named in the generated file's header, when present.
	Source string
	// Reason, when set, replaces the generated-file message: the call was blocked
	// because the guard would not analyze it (oversized payload, too many files).
	Reason string
}

// Message is the text shown to the agent when the call is blocked.
func (d Decision) Message() string {
	if d.Reason != "" {
		return "Blocked: " + d.Reason + "\n"
	}
	var b strings.Builder
	b.WriteString("Blocked: " + d.Path + " is generated by ai-rulez and is overwritten by `ai-rulez generate`; a direct edit is lost.\n")
	if d.Source != "" {
		b.WriteString("Edit its source " + d.Source + " instead")
	} else {
		b.WriteString("Edit the matching source under " + configDirName + "/ (rules, context, skills, agents, commands or config.toml) instead")
	}
	b.WriteString(", then run `ai-rulez generate`.\n")
	b.WriteString("Read the ai-rulez skill if it is installed, or run `ai-rulez --help`, to see how the sources map to outputs.\n")
	return b.String()
}

// payload is the union of the hook payloads the supported harnesses send. Claude
// Code, Codex, Gemini CLI, Cursor, Factory and Copilot all send a JSON object with the tool
// name and its input; only the key names differ.
type payload struct {
	ToolName  string          `json:"tool_name"`
	ToolName2 string          `json:"toolName"`
	ToolInput json.RawMessage `json:"tool_input"`
	ToolArgs  json.RawMessage `json:"toolArgs"`
	Cwd       string          `json:"cwd"`
	FilePath  string          `json:"file_path"`
}

// pathKeys are the tool_input keys that carry the file a tool edits.
var pathKeys = []string{"file_path", "filePath", "path", "target_file", "notebook_path", "filepath", "file"}

// patchKeys are the keys that carry an apply_patch style patch body.
var patchKeys = []string{"command", "input", "patch", "cmd"}

var patchFile = regexp.MustCompile(`(?m)^\s*\*\*\* (?:Add File|Update File|Delete File|Move to): (.+?)\s*$`)

// editTools are the tools that write a file, lowercased, across the supported
// harnesses. Any other named tool (Read, Grep, Bash, view...) is never blocked even
// when its input names a generated file: reading one is fine.
var editTools = map[string]bool{
	"edit": true, "write": true, "multiedit": true, "notebookedit": true, // Claude Code, Cursor, Factory
	"replace": true, "write_file": true, // Gemini CLI
	"apply_patch": true, "applypatch": true, // Codex
	"create": true, "str_replace": true, "str_replace_editor": true, "create_file": true, "edit_file": true,
}

// Check decides one hook payload. cwd is the process working directory, used when
// the payload names none. Check never returns an error: see the package comment.
func Check(stdin io.Reader, cwd string) Decision {
	data, err := io.ReadAll(io.LimitReader(stdin, maxPayload+1))
	if err != nil {
		return Decision{}
	}
	if len(data) > maxPayload {
		// Only an edit tool is blocked for its size: an oversized Read is harmless.
		if name := topLevelTool(data); name != "" && !editTools[strings.ToLower(name)] {
			return Decision{}
		}
		return Decision{Block: true, Reason: fmt.Sprintf("the tool call payload is larger than %d MiB, which the ai-rulez guard does not analyze; make smaller edits", maxPayload>>20)}
	}
	var p payload
	if err := json.Unmarshal(data, &p); err != nil {
		return Decision{}
	}
	tool := p.ToolName
	if tool == "" {
		tool = p.ToolName2
	}
	if tool != "" && !editTools[strings.ToLower(tool)] {
		return Decision{}
	}
	if p.Cwd != "" {
		cwd = p.Cwd
	}
	paths, over := targets(&p)
	if over {
		return Decision{Block: true, Reason: fmt.Sprintf("the tool call edits more than %d files, which the ai-rulez guard does not analyze; split it", maxTargets)}
	}
	c := newCache()
	for _, target := range paths {
		if d, hit := c.check(cwd, target); hit {
			return d
		}
	}
	return Decision{}
}

// topLevelTool reads the tool name from a payload that is too large to parse,
// walking only its top-level keys. It returns "" when the name is not found
// before the data ends.
func topLevelTool(data []byte) string {
	dec := json.NewDecoder(bytes.NewReader(data))
	if tok, err := dec.Token(); err != nil || tok != json.Delim('{') {
		return ""
	}
	for dec.More() {
		keyTok, err := dec.Token()
		if err != nil {
			return ""
		}
		key, isKey := keyTok.(string)
		if !isKey {
			return ""
		}
		var raw json.RawMessage
		if err := dec.Decode(&raw); err != nil {
			return ""
		}
		if key == "tool_name" || key == "toolName" {
			var name string
			if json.Unmarshal(raw, &name) == nil && name != "" {
				return name
			}
		}
	}
	return ""
}

// project is a located project with its manifests read once.
type project struct {
	root, realRoot string
	files          owned
}

// cache keeps what one Check run looked up: the project of each base directory and
// the manifests of each project root, so a patch naming thousands of files does the
// directory walk, the manifest parse and the symlink resolution once.
type cache struct {
	byBase map[string]*project
	byRoot map[string]*project
}

func newCache() *cache {
	return &cache{byBase: map[string]*project{}, byRoot: map[string]*project{}}
}

func (c *cache) project(base string) (*project, bool) {
	if p, ok := c.byBase[base]; ok {
		return p, p != nil
	}
	root, ok := findProject(base)
	if !ok {
		c.byBase[base] = nil
		return nil, false
	}
	p := c.byRoot[root]
	if p == nil {
		realRoot, err := filepath.EvalSymlinks(root)
		if err != nil {
			realRoot = root
		}
		p = &project{root: root, realRoot: realRoot, files: loadManifest(root)}
		c.byRoot[root] = p
	}
	c.byBase[base] = p
	return p, true
}

// check decides one target. The project is located from the working directory
// and from the target's own directory: a payload whose cwd lies outside the
// project (or names none) must not hide a generated file inside it.
func (c *cache) check(cwd, target string) (Decision, bool) {
	var bases []string
	if cwd != "" {
		bases = append(bases, cwd)
	}
	abs := target
	if !filepath.IsAbs(abs) && cwd != "" {
		abs = filepath.Join(cwd, abs)
	}
	if filepath.IsAbs(abs) {
		if dir := filepath.Dir(filepath.Clean(abs)); dir != cwd {
			bases = append(bases, dir)
		}
	}
	for _, base := range bases {
		proj, ok := c.project(base)
		if !ok {
			continue
		}
		if rel, hit := proj.files.lookup(proj.root, proj.realRoot, base, target); hit {
			return Decision{Block: true, Path: rel, Source: sourceOf(filepath.Join(proj.root, filepath.FromSlash(rel)))}, true
		}
	}
	return Decision{}, false
}

// targets lists every distinct path the call writes. over is true when there are
// more than maxTargets of them.
func targets(p *payload) (out []string, over bool) {
	seen := map[string]bool{}
	add := func(s string) bool {
		if !seen[s] {
			if len(seen) >= maxTargets {
				return false
			}
			seen[s] = true
			out = append(out, s)
		}
		return true
	}
	if p.FilePath != "" {
		add(p.FilePath)
	}
	for _, raw := range []json.RawMessage{p.ToolInput, p.ToolArgs} {
		if !inputTargets(raw, add) {
			return out, true
		}
	}
	return out, false
}

// inputTargets passes to add every path one tool input names; it returns false
// as soon as add refuses one (too many targets).
func inputTargets(raw json.RawMessage, add func(string) bool) bool {
	if len(raw) == 0 {
		return true
	}
	// Some harnesses send the arguments as a JSON document inside a string.
	var asText string
	if json.Unmarshal(raw, &asText) == nil {
		raw = json.RawMessage(asText)
	}
	var input map[string]any
	if json.Unmarshal(raw, &input) != nil {
		return true
	}
	for _, key := range pathKeys {
		if s, ok := input[key].(string); ok && s != "" && !add(s) {
			return false
		}
	}
	for _, key := range patchKeys {
		for _, s := range stringsIn(input[key]) {
			for _, m := range patchFile.FindAllStringSubmatch(s, -1) {
				if !add(m[1]) {
					return false
				}
			}
		}
	}
	return true
}

// stringsIn lists the strings of a patch value: the string itself, or every string
// element of an array (Codex sends the patch as ["apply_patch", "<patch>"]).
func stringsIn(v any) []string {
	switch t := v.(type) {
	case string:
		return []string{t}
	case []any:
		var out []string
		for _, e := range t {
			out = append(out, stringsIn(e)...)
		}
		return out
	}
	return nil
}

// findProject walks up from dir to the nearest directory with a generated manifest.
func findProject(dir string) (string, bool) {
	dir = filepath.Clean(dir)
	if !filepath.IsAbs(dir) {
		return "", false
	}
	for {
		for _, name := range []string{manifestName, localManifestName} {
			if info, err := os.Stat(filepath.Join(dir, configDirName, name)); err == nil && info.Mode().IsRegular() {
				return dir, true
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", false
		}
		dir = parent
	}
}

type manifestFile struct {
	Files  []string                   `json:"files"`
	Merged map[string]json.RawMessage `json:"merged"`
}

// owned is the set of wholly owned outputs, keyed by slash path relative to the
// project root (lowercased where the file system is case-insensitive) and
// mapping to the path as the manifest spells it.
type owned map[string]string

// loadManifest reads the committed and machine-local manifests. A path listed under
// "merged" is a document ai-rulez only contributes keys to, so it is never owned.
func loadManifest(root string) owned {
	set := owned{}
	merged := map[string]bool{}
	for _, name := range []string{manifestName, localManifestName} {
		path := filepath.Join(root, configDirName, name)
		if name == localManifestName && gitutil.UntrustedLocalFile(path) != "" {
			continue // forged or tracked: it must not decide what the guard protects
		}
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		var m manifestFile
		if json.Unmarshal(data, &m) != nil {
			continue
		}
		for _, f := range m.Files {
			if f = cleanRel(f); f != "" {
				set[fold(f)] = f
			}
		}
		for f := range m.Merged {
			merged[fold(cleanRel(f))] = true
		}
	}
	for f := range merged {
		delete(set, f)
	}
	return set
}

func cleanRel(p string) string {
	p = filepath.ToSlash(filepath.Clean(filepath.FromSlash(p)))
	if p == "." || p == ".." || strings.HasPrefix(p, "../") || filepath.IsAbs(filepath.FromSlash(p)) {
		return ""
	}
	return p
}

// fold makes a path comparable on a case-insensitive file system.
func fold(p string) string {
	if runtime.GOOS == "darwin" || runtime.GOOS == "windows" {
		return strings.ToLower(p)
	}
	return p
}

// lookup reports whether target, as the tool names it, is an owned output. Both the
// lexical path and the path with symlinks resolved are checked: an agent could name
// the generated file directly, through "..", or through a link to it.
func (o owned) lookup(root, realRoot, cwd, target string) (string, bool) {
	abs := target
	if !filepath.IsAbs(abs) {
		abs = filepath.Join(cwd, abs)
	}
	abs = filepath.Clean(abs)
	for _, c := range []struct{ base, path string }{{root, abs}, {realRoot, resolve(abs)}} {
		// Both sides are folded on a case-insensitive file system: a path that
		// differs from the root only in case is the same path there.
		rel, err := filepath.Rel(fold(c.base), fold(c.path))
		if err != nil {
			continue
		}
		rel = filepath.ToSlash(rel)
		if rel == ".." || strings.HasPrefix(rel, "../") {
			continue
		}
		if orig, ok := o[fold(rel)]; ok {
			return orig, true
		}
	}
	return "", false
}

// resolve evaluates symlinks of the longest existing prefix of p, so a file that
// does not exist yet (a Write) still resolves through a linked directory.
func resolve(p string) string {
	rest := ""
	for cur := p; ; {
		if resolved, err := filepath.EvalSymlinks(cur); err == nil {
			return filepath.Join(resolved, rest)
		}
		parent := filepath.Dir(cur)
		if parent == cur {
			return p
		}
		rest = filepath.Join(filepath.Base(cur), rest)
		cur = parent
	}
}

var headerSource = regexp.MustCompile(`Generated by ai-rulez from (.+?)\. Edit the source`)

// sourceOf names the source file a generated file's banner points at, or "".
func sourceOf(path string) string {
	f, err := os.Open(path)
	if err != nil {
		return ""
	}
	defer func() { _ = f.Close() }()
	buf := make([]byte, headerBytes)
	n, err := io.ReadFull(f, buf)
	if err != nil && !errors.Is(err, io.ErrUnexpectedEOF) {
		return "" // an empty file or a read error: no banner to read
	}
	m := headerSource.FindSubmatch(buf[:n])
	if m == nil {
		return ""
	}
	return strings.TrimSpace(string(m[1]))
}
