// Generated by ai-rulez from the [[hooks]] of .ai-rulez/config.toml. Do not edit: the next
// `ai-rulez generate` overwrites this file and `ai-rulez clean` removes it.
//
// Each hook command runs in a shell from the project directory and receives a JSON document on
// stdin shaped like Claude Code's hook input: session_id, cwd, hook_event_name and the fields of
// the event (tool_name, tool_input, tool_response, prompt, source, ...). tool_name is the Claude
// Code name of the tool where one exists and harness_tool_name is pi's own.
// Exit code 2 from a pre-tool hook blocks the call and its stderr becomes the reason; any other
// non-zero exit, a timeout or a spawn failure is logged to stderr and does not block.
// @ts-nocheck
import { spawn } from "node:child_process";

const HOOK_CONFIG = {
  "harness": "pi",
  "blocking": [
    "PreToolUse",
    "UserPromptSubmit"
  ],
  "tools": {
    "bash": [
      "Bash"
    ],
    "edit": [
      "Edit",
      "MultiEdit"
    ],
    "find": [
      "Glob"
    ],
    "grep": [
      "Grep"
    ],
    "ls": [
      "LS"
    ],
    "read": [
      "Read"
    ],
    "write": [
      "Write"
    ]
  },
  "hooks": {
    "PostCompact": [
      {
        "command": "echo after"
      }
    ],
    "PostToolUse": [
      {
        "matcher": "Edit|Write",
        "command": "echo format"
      }
    ],
    "PostToolUseFailure": [
      {
        "command": "echo failed"
      }
    ],
    "PreCompact": [
      {
        "command": "echo before"
      }
    ],
    "PreToolUse": [
      {
        "matcher": "Bash",
        "command": "echo guard",
        "timeout": 10000
      }
    ],
    "SessionEnd": [
      {
        "command": "echo bye"
      }
    ],
    "SessionStart": [
      {
        "matcher": "startup",
        "command": "'./scripts/boot.sh' --quick 'a b'"
      }
    ],
    "Stop": [
      {
        "command": "echo done",
        "async": true
      }
    ],
    "UserPromptSubmit": [
      {
        "command": "echo prompt"
      }
    ]
  }
};

const DEFAULT_TIMEOUT_MS = 600000;
const MAX_OUTPUT_LENGTH = 1048576;
const MAX_REASON_LENGTH = 2000;
const matchers = new Map();

function log(message) {
  console.error(`[ai-rulez hooks] ${message}`);
}

// The names a tool answers to: its own and the Claude Code names mapped onto it.
function toolNames(native) {
  const aliases = Object.prototype.hasOwnProperty.call(HOOK_CONFIG.tools, native) ? HOOK_CONFIG.tools[native] : [];
  return [native, ...aliases];
}

// A matcher is a regular expression that must match a whole subject, as in Claude Code.
function matches(matcher, subjects) {
  if (!matcher) return true;
  let pattern = matchers.get(matcher);
  if (pattern === undefined) {
    try {
      pattern = new RegExp(`^(?:${matcher})$`);
    } catch (error) {
      log(`ignoring the invalid matcher ${JSON.stringify(matcher)}: ${error.message}`);
      pattern = null;
    }
    matchers.set(matcher, pattern);
  }
  return pattern !== null && subjects.some((subject) => pattern.test(subject));
}

// Claude Code names the command and the path of a tool call command and file_path.
function normalizeInput(input) {
  if (input === null || typeof input !== "object") return {};
  const out = { ...input };
  if (out.command === undefined && typeof out.cmd === "string") out.command = out.cmd;
  if (out.file_path === undefined) {
    const file = out.filePath ?? out.path ?? out.file;
    if (typeof file === "string") out.file_path = file;
  }
  return out;
}

function clean(text) {
  const reason = String(text)
    .replace(/\u001b\[[0-9;?]*[ -/]*[@-~]/g, "")
    .replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f-\u009f]/g, "")
    .trim();
  if (reason === "") return "Blocked by an ai-rulez hook.";
  return reason.length > MAX_REASON_LENGTH ? `${reason.slice(0, MAX_REASON_LENGTH)}...` : reason;
}

function runCommand(hook, stdin, dir, event) {
  return new Promise((resolve) => {
    let stdout = "";
    let stderr = "";
    let timedOut = false;
    let settled = false;
    let timer = null;
    const finish = (code) => {
      if (settled) return;
      settled = true;
      if (timer !== null) clearTimeout(timer);
      resolve({ code, stdout, stderr, timedOut });
    };
    let child;
    try {
      child = spawn(hook.command, {
        shell: true,
        cwd: dir,
        env: { ...process.env, CLAUDE_PROJECT_DIR: dir, AI_RULEZ_PROJECT_DIR: dir, AI_RULEZ_HOOK_EVENT: event },
        stdio: ["pipe", "pipe", "pipe"],
        windowsHide: true,
      });
    } catch (error) {
      stderr = String(error?.message ?? error);
      finish(null);
      return;
    }
    timer = setTimeout(() => {
      timedOut = true;
      child.kill("SIGKILL");
    }, hook.timeout > 0 ? hook.timeout : DEFAULT_TIMEOUT_MS);
    child.stdout.on("data", (chunk) => {
      if (stdout.length < MAX_OUTPUT_LENGTH) stdout += chunk;
    });
    child.stderr.on("data", (chunk) => {
      if (stderr.length < MAX_OUTPUT_LENGTH) stderr += chunk;
    });
    child.on("error", (error) => {
      stderr = stderr || String(error.message);
      finish(null);
    });
    child.on("close", (code) => finish(code));
    child.stdin.on("error", () => {});
    child.stdin.end(stdin);
  });
}

// Exit code 2, or a JSON decision of block or deny on stdout, blocks a blocking event.
function blockReason(event, result) {
  if (!HOOK_CONFIG.blocking.includes(event) || result.timedOut) return null;
  if (result.code === 2) return clean(result.stderr.trim() || result.stdout.trim());
  const text = result.stdout.trim();
  if (result.code !== 0 || !text.startsWith("{")) return null;
  try {
    const decision = JSON.parse(text);
    const specific = decision.hookSpecificOutput ?? {};
    if (decision.decision === "block" || decision.decision === "deny") return clean(decision.reason ?? "");
    if (specific.permissionDecision === "deny") return clean(specific.permissionDecisionReason ?? "");
  } catch {
    // Plain output is not a decision.
  }
  return null;
}

function report(event, index, result) {
  if (result.timedOut) {
    log(`${event} hook ${index} timed out`);
  } else if (result.code !== 0) {
    const detail = result.stderr.trim().split("\n")[0];
    log(`${event} hook ${index} failed (${result.code === null ? "not run" : `exit ${result.code}`})${detail ? `: ${detail}` : ""}`);
  }
}

// Runs the hooks of an event in order and returns the reason of the first one that blocks, or null.
// target is { tool } for a tool event, { subject } for an event matched on a string, or absent.
async function dispatch(event, dir, fields, target) {
  const hooks = HOOK_CONFIG.hooks[event] ?? [];
  const subjects = target === undefined ? null : target.tool !== undefined ? toolNames(target.tool) : [target.subject];
  const input = { session_id: "", cwd: dir, hook_event_name: event };
  if (target !== undefined && target.tool !== undefined) {
    input.tool_name = toolNames(target.tool)[1] ?? target.tool;
    input.harness_tool_name = target.tool;
  }
  Object.assign(input, fields);
  if (input.session_id === undefined) input.session_id = "";
  if (target !== undefined && target.tool !== undefined) input.tool_input = normalizeInput(fields.tool_input);
  let stdin;
  try {
    stdin = JSON.stringify(input);
  } catch (error) {
    log(`cannot encode the input of the ${event} hooks: ${error.message}`);
    return null;
  }
  for (let index = 0; index < hooks.length; index += 1) {
    const hook = hooks[index];
    if (subjects !== null && !matches(hook.matcher, subjects)) continue;
    if (hook.async) {
      void runCommand(hook, stdin, dir, event).then((result) => report(event, index, result));
      continue;
    }
    const result = await runCommand(hook, stdin, dir, event);
    const reason = blockReason(event, result);
    if (reason !== null) return reason;
    report(event, index, result);
  }
  return null;
}

const SESSION_SOURCES = { startup: "startup", reload: "startup", new: "clear", resume: "resume", fork: "startup" };

function sessionId(ctx) {
  try {
    return ctx.sessionManager.getSessionId() ?? "";
  } catch {
    return "";
  }
}

function transcriptPath(ctx) {
  try {
    return ctx.sessionManager.getSessionFile() ?? undefined;
  } catch {
    return undefined;
  }
}

function base(ctx) {
  return { session_id: sessionId(ctx), transcript_path: transcriptPath(ctx) };
}

function directory(ctx) {
  return ctx?.cwd ?? process.cwd();
}

export default function (pi: any) {
  pi.on("session_start", async (event, ctx) => {
    const source = SESSION_SOURCES[event.reason] ?? "startup";
    await dispatch("SessionStart", directory(ctx), { ...base(ctx), source }, { subject: source });
  });
  pi.on("session_shutdown", async (event, ctx) => {
    await dispatch("SessionEnd", directory(ctx), { ...base(ctx), reason: event.reason });
  });
  pi.on("input", async (event, ctx) => {
    if (event.source === "extension") return { action: "continue" };
    const reason = await dispatch("UserPromptSubmit", directory(ctx), { ...base(ctx), prompt: event.text });
    if (reason === null) return { action: "continue" };
    try {
      if (ctx.hasUI) ctx.ui.notify(reason, "error");
      else console.error(reason);
    } catch {
      console.error(reason);
    }
    return { action: "handled" };
  });
  pi.on("tool_call", async (event, ctx) => {
    const reason = await dispatch(
      "PreToolUse",
      directory(ctx),
      { ...base(ctx), tool_use_id: event.toolCallId, tool_input: event.input },
      { tool: event.toolName },
    );
    if (reason !== null) return { block: true, reason };
  });
  pi.on("tool_result", async (event, ctx) => {
    const failed = event.isError === true;
    const fields = {
      ...base(ctx),
      tool_use_id: event.toolCallId,
      tool_input: event.input,
      tool_response: { content: event.content, is_error: failed },
    };
    if (!failed) await dispatch("PostToolUse", directory(ctx), fields, { tool: event.toolName });
    if (failed) await dispatch("PostToolUseFailure", directory(ctx), fields, { tool: event.toolName });
  });
  pi.on("session_before_compact", async (event, ctx) => {
    const trigger = event.reason === "manual" ? "manual" : "auto";
    await dispatch("PreCompact", directory(ctx), { ...base(ctx), trigger }, { subject: trigger });
  });
  pi.on("session_compact", async (event, ctx) => {
    const trigger = event.reason === "manual" ? "manual" : "auto";
    await dispatch("PostCompact", directory(ctx), { ...base(ctx), trigger }, { subject: trigger });
  });
  pi.on("agent_settled", async (_event, ctx) => {
    await dispatch("Stop", directory(ctx), base(ctx));
  });
}
