package lint

import (
	"context"
	"sort"
	"testing"
)

// fakePlan is a PlannedFiles over a map.
type fakePlan map[string]string

func (f fakePlan) Planned(rel string) ([]byte, bool) {
	s, ok := f[rel]
	return []byte(s), ok
}

func (f fakePlan) PlannedPaths() []string {
	paths := make([]string, 0, len(f))
	for p := range f {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	return paths
}

func lintWithPlan(t *testing.T, files map[string]string, plan PlannedFiles) []Finding {
	t.Helper()
	root := t.TempDir()
	writeFiles(t, root, files)
	gitAdd(t, root)
	cfg, err := loadWithResolvers(context.Background(), root)
	if err != nil {
		t.Fatalf("load config: %v", err)
	}
	tree, err := LoadTree(root)
	if err != nil {
		t.Fatal(err)
	}
	rep, err := RunWith(cfg, tree, Options{}, WithPlanned(plan))
	if err != nil {
		t.Fatal(err)
	}
	return rep.Findings
}

func TestTrapsJudgeThePlannedFiles(t *testing.T) {
	const cfg = ".ai-rulez/config.toml"
	kiro := trapConfig(`"kiro"`, "")
	badSteering := "\n---\ninclusion: manual\n---\n# s\n" // a blank line before the frontmatter
	generated := "<!-- Generated by ai-rulez from x.md. Edit the source, not this file. -->\n"
	tests := []struct {
		name  string
		files map[string]string
		plan  fakePlan
		want  int
	}{
		{
			name:  "a planned file the repository does not hold yet is judged",
			files: map[string]string{cfg: kiro},
			plan:  fakePlan{".kiro/steering/s.md": badSteering},
			want:  1,
		},
		{
			name:  "a generated file on disk is judged by what the plan would write",
			files: map[string]string{cfg: kiro, ".kiro/steering/s.md": generated + "---\ninclusion: manual\n---\n# s\n"},
			plan:  fakePlan{".kiro/steering/s.md": badSteering},
			want:  1,
		},
		{
			name:  "a hand-written file on disk keeps its own content: the run would leave it alone",
			files: map[string]string{cfg: kiro, ".kiro/steering/s.md": "---\ninclusion: manual\n---\n# mine\n"},
			plan:  fakePlan{".kiro/steering/s.md": badSteering},
		},
		{
			name:  "a good planned file raises nothing",
			files: map[string]string{cfg: kiro},
			plan:  fakePlan{".kiro/steering/s.md": "---\ninclusion: manual\n---\n# s\n"},
		},
		{
			name:  "no plan reads the disk as before",
			files: map[string]string{cfg: kiro, ".kiro/steering/s.md": badSteering},
			want:  1,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Arrange / Act
			var plan PlannedFiles
			if tt.plan != nil {
				plan = tt.plan
			}
			got := codeHits(lintWithPlan(t, tt.files, plan), CodeKiroSteeringFirst)

			// Assert
			if len(got) != tt.want {
				t.Fatalf("want %d %s findings, got %d: %+v", tt.want, CodeKiroSteeringFirst, len(got), got)
			}
		})
	}
}
