package lint

import (
	"regexp"
	"testing"
)

// Every regular expression this package compiles lazily with sync.OnceValue is
// compiled here once, so a pattern that does not parse fails the test run instead
// of panicking at its first use in production. tests/archlint fails when an
// accessor is missing from this list.
func TestRegexAccessorsCompile(t *testing.T) {
	accessors := map[string]func() *regexp.Regexp{
		"addMarkerRe":        addMarkerRe,
		"alternativeRe":      alternativeRe,
		"ambiguousLabelRe":   ambiguousLabelRe,
		"ansiCSI":            ansiCSI,
		"ansiOSC":            ansiOSC,
		"assignRe":           assignRe,
		"atRefRe":            atRefRe,
		"authSchemeRe":       authSchemeRe,
		"authorityRe":        authorityRe,
		"backtickRe":         backtickRe,
		"bareDownloaderRe":   bareDownloaderRe,
		"base64ExecRe":       base64ExecRe,
		"blobRe":             blobRe,
		"broadBashToolRe":    broadBashToolRe,
		"chmod777Re":         chmod777Re,
		"claimRe":            claimRe,
		"claudeModelRe":      claudeModelRe,
		"clauseEndRe":        clauseEndRe,
		"codeRe":             codeRe,
		"codeSpanRe":         codeSpanRe,
		"commandCueRe":       commandCueRe,
		"copyVerbRe":         copyVerbRe,
		"credSegSplitRe":     credSegSplitRe,
		"dataLinkRe":         dataLinkRe,
		"dataRefRe":          dataRefRe,
		"dateHolderRe":       dateHolderRe,
		"ddDiskRe":           ddDiskRe,
		"ddRe":               ddRe,
		"digitsRe":           digitsRe,
		"directiveRe":        directiveRe,
		"directiveTagRe":     directiveTagRe,
		"dnsExfilRe":         dnsExfilRe,
		"dnsPayloadRe":       dnsPayloadRe,
		"dnsStartRe":         dnsStartRe,
		"dnsTickRe":          dnsTickRe,
		"dotdirRe":           dotdirRe,
		"driveAuthority":     driveAuthority,
		"dropDBRe":           dropDBRe,
		"envAssignRe":        envAssignRe,
		"envDumpRe":          envDumpRe,
		"envPipeRe":          envPipeRe,
		"envRefRe":           envRefRe,
		"escapeRe":           escapeRe,
		"evalBenignRe":       evalBenignRe,
		"evalRe":             evalRe,
		"exampleInfoRe":      exampleInfoRe,
		"exampleRe":          exampleRe,
		"exfilVerbRe":        exfilVerbRe,
		"extRe":              extRe,
		"fakeTagRe":          fakeTagRe,
		"fenceRe":            fenceRe,
		"fileArgRe":          fileArgRe,
		"flagSecretRe":       flagSecretRe,
		"fmKeyLineRe":        fmKeyLineRe,
		"fmNameLineRe":       fmNameLineRe,
		"forkBombRe":         forkBombRe,
		"fragLineRe":         fragLineRe,
		"governingNegRe":     governingNegRe,
		"headerArgRe":        headerArgRe,
		"headerSecretRe":     headerSecretRe,
		"headingRe":          headingRe,
		"hexRefRe":           hexRefRe,
		"htmlCommentRe":      htmlCommentRe,
		"httpURLRe":          httpURLRe,
		"httpieRe":           httpieRe,
		"ignoredRe":          ignoredRe,
		"imageURLRe":         imageURLRe,
		"imperativeMarkerRe": imperativeMarkerRe,
		"imperativeRe":       imperativeRe,
		"importRe":           importRe,
		"includeCacheRE":     includeCacheRE,
		"inlineLinkRe":       inlineLinkRe,
		"ipURLRe":            ipURLRe,
		"justRe":             justRe,
		"justRecipeRe":       justRecipeRe,
		"kebabRe":            kebabRe,
		"keychainCmdRe":      keychainCmdRe,
		"lineSuffixRe":       lineSuffixRe,
		"listMarkerRe":       listMarkerRe,
		"makeRe":             makeRe,
		"makeTargetRe":       makeTargetRe,
		"markerLineRe":       markerLineRe,
		"markerWordRe":       markerWordRe,
		"mcpNameRe":          mcpNameRe,
		"mcpToolRe":          mcpToolRe,
		"mkfsRe":             mkfsRe,
		"nameAfterRe":        nameAfterRe,
		"nameBeforeRe":       nameBeforeRe,
		"negationRe":         negationRe,
		"netCmdRe":           netCmdRe,
		"noBeforeRe":         noBeforeRe,
		"nonNameRe":          nonNameRe,
		"notSecretKeyRe":     notSecretKeyRe,
		"npmRunRe":           npmRunRe,
		"orgSuffixRe":        orgSuffixRe,
		"ownerRe":            ownerRe,
		"pipeSegSplitRe":     pipeSegSplitRe,
		"pipeSplitRe":        pipeSplitRe,
		"pipeToInterpRe":     pipeToInterpRe,
		"pipeToShellRe":      pipeToShellRe,
		"placeholder":        placeholder,
		"placeholderRe":      placeholderRe,
		"placeholderValRe":   placeholderValRe,
		"pluginRootRe":       pluginRootRe,
		"pluginWordRe":       pluginWordRe,
		"procSubstRe":        procSubstRe,
		"projectVarRe":       projectVarRe,
		"pytestMarkRe":       pytestMarkRe,
		"quotedBoolRe":       quotedBoolRe,
		"readVarRe":          readVarRe,
		"readVerbRe":         readVerbRe,
		"redirectInRe":       redirectInRe,
		"redirectOutRe":      redirectOutRe,
		"refCommentRe":       refCommentRe,
		"refLinkRe":          refLinkRe,
		"repoSlugRe":         repoSlugRe,
		"repoWordRe":         repoWordRe,
		"scalarValueRe":      scalarValueRe,
		"schemeRe":           schemeRe,
		"scopedFlagRe":       scopedFlagRe,
		"secretFlagRe":       secretFlagRe,
		"secretKeyRe":        secretKeyRe,
		"secretName":         secretName,
		"secretVarRe":        secretVarRe,
		"segSplitRe":         segSplitRe,
		"semverRe":           semverRe,
		"sentenceEndRe":      sentenceEndRe,
		"skillCallRe":        skillCallRe,
		"skillNameRe":        skillNameRe,
		"skillRelRe":         skillRelRe,
		"slashRe":            slashRe,
		"slugDropRe":         slugDropRe,
		"smallImgRe":         smallImgRe,
		"stageNameRe":        stageNameRe,
		"stagePlaceholderRe": stagePlaceholderRe,
		"stageSplit":         stageSplit,
		"subagentRe":         subagentRe,
		"tableDotdirs":       tableDotdirs,
		"targetTokenRe":      targetTokenRe,
		"taskRe":             taskRe,
		"teeRe":              teeRe,
		"tickSlashRe":        tickSlashRe,
		"unpinnedStartRe":    unpinnedStartRe,
		"unsafeAfterRe":      unsafeAfterRe,
		"urlCredRe":          urlCredRe,
		"urlRe":              urlRe,
		"useWhenRe":          useWhenRe,
		"usedMarkerRe":       usedMarkerRe,
		"varRefRe":           varRefRe,
		"vendorModelRe":      vendorModelRe,
		"versionPinRe":       versionPinRe,
		"versionRangeRe":     versionRangeRe,
		"versionedInterpRe":  versionedInterpRe,
		"winDriv":            winDriv,
		"wordRe":             wordRe,
		"writeOutsideRe":     writeOutsideRe,
	}
	for name, get := range accessors {
		if get() == nil {
			t.Errorf("%s compiled to nil", name)
		}
	}
}
