package lint

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestReadTrapFile(t *testing.T) {
	dir := t.TempDir()
	write := func(name, content string) string {
		p := filepath.Join(dir, name)
		require.NoError(t, os.WriteFile(p, []byte(content), 0o600))
		return p
	}

	t.Run("a missing file has no content", func(t *testing.T) {
		content, generated := readTrapFile(filepath.Join(dir, "missing"))
		assert.Nil(t, content)
		assert.False(t, generated)
	})
	t.Run("an empty file has empty, non-nil content", func(t *testing.T) {
		content, generated := readTrapFile(write("empty", ""))
		assert.NotNil(t, content)
		assert.Empty(t, content)
		assert.False(t, generated)
	})
	t.Run("the banner marks a generated file", func(t *testing.T) {
		content, generated := readTrapFile(write("gen", "<!-- Generated by ai-rulez -->\nbody\n"))
		assert.True(t, generated)
		assert.Equal(t, "<!-- Generated by ai-rulez -->\nbody\n", string(content))
	})
	t.Run("a long file is cut at the bound", func(t *testing.T) {
		content, _ := readTrapFile(write("long", strings.Repeat("a", maxTrapFileBytes+500)))
		assert.Len(t, content, maxTrapFileBytes)
	})
	t.Run("a small file does not allocate the bound", func(t *testing.T) {
		p := write("small", "# small\n")
		var before, after runtime.MemStats
		runtime.ReadMemStats(&before)
		for range 50 {
			readTrapFile(p)
		}
		runtime.ReadMemStats(&after)
		assert.Less(t, after.TotalAlloc-before.TotalAlloc, uint64(50*maxTrapFileBytes/8), "each read allocated the full %d byte bound", maxTrapFileBytes)
	})
}
