package lint

import (
	"github.com/Goldziher/ai-rulez/v5/internal/config"
	"os"
	"strings"
	"testing"
)

func trapConfig(presets, extra string) string {
	return "version = \"4.0\"\nname = \"t\"\npresets = [" + presets + "]\n" + extra
}

func trapFindings(t *testing.T, files map[string]string) []Finding {
	t.Helper()
	root := t.TempDir()
	writeFiles(t, root, files)
	gitAdd(t, root)
	return lintDir(t, root)
}

func TestHarnessTraps(t *testing.T) {
	const cfg = ".ai-rulez/config.toml"
	cursorCfg := trapConfig(`"cursor"`, "")
	copilotCfg := trapConfig(`"copilot"`, "")
	generated := "<!-- Generated by ai-rulez from x.md. Edit the source, not this file. -->\n"
	tests := []struct {
		name     string
		files    map[string]string
		wantCode string // "" means no trap finding at all
		wantSev  Severity
		wantLine int
	}{
		// AR9C1
		{name: "AR9C1 bad: plain md in cursor rules", files: map[string]string{cfg: cursorCfg, ".cursor/rules/api.md": "# api\n"}, wantCode: CodeCursorRuleExtension, wantSev: SeverityWarning, wantLine: 1},
		{name: "AR9C1 good: mdc and README", files: map[string]string{cfg: cursorCfg, ".cursor/rules/api.mdc": "---\nalwaysApply: true\n---\n# api\n", ".cursor/rules/README.md": "# about\n"}},
		{name: "AR9C1 good: folder rule RULE.md is exempt", files: map[string]string{cfg: cursorCfg, ".cursor/rules/api/RULE.md": "---\ndescription: x\n---\n# api\n"}},
		{name: "AR9C1 nested package", files: map[string]string{cfg: cursorCfg, "pkg/.cursor/rules/x.txt": "x\n"}, wantCode: CodeCursorRuleExtension, wantSev: SeverityWarning, wantLine: 1},
		{name: "AR9C1 generated file is an error", files: map[string]string{cfg: cursorCfg, ".cursor/rules/gen.md": generated + "# g\n"}, wantCode: CodeCursorRuleExtension, wantSev: SeverityError, wantLine: 1},
		// AR9C2
		{name: "AR9C2 bad: mdc applies to nothing", files: map[string]string{cfg: cursorCfg, ".cursor/rules/m.mdc": "---\nalwaysApply: false\n---\n# m\n"}, wantCode: CodeCursorRuleNotApplied, wantSev: SeverityWarning, wantLine: 1},
		{name: "AR9C2 bad: no frontmatter", files: map[string]string{cfg: cursorCfg, ".cursor/rules/m.mdc": "# m\n"}, wantCode: CodeCursorRuleNotApplied, wantSev: SeverityWarning, wantLine: 1},
		{name: "AR9C2 good: always apply", files: map[string]string{cfg: cursorCfg, ".cursor/rules/m.mdc": "---\nalwaysApply: true\n---\n# m\n"}},
		{name: "AR9C2 good: globs", files: map[string]string{cfg: cursorCfg, ".cursor/rules/m.mdc": "---\nglobs: \"**/*.go\"\n---\n# m\n"}},
		{name: "AR9C2 good: description", files: map[string]string{cfg: cursorCfg, ".cursor/rules/m.mdc": "---\ndescription: Use for API work\n---\n# m\n"}},
		{name: "AR9C2 skipped: generated manual rule", files: map[string]string{cfg: cursorCfg, ".cursor/rules/m.mdc": "---\nalwaysApply: false\n---\n" + generated + "# m\n"}},
		// AR9C3
		{name: "AR9C3 bad: invalid value", files: map[string]string{cfg: copilotCfg, ".github/instructions/a.instructions.md": "---\napplyTo: \"**\"\nexcludeAgent: \"review\"\n---\nbody\n"}, wantCode: CodeCopilotExcludeAgent, wantSev: SeverityWarning, wantLine: 3},
		{name: "AR9C3 good: valid values", files: map[string]string{cfg: copilotCfg, ".github/instructions/a.instructions.md": "---\nexcludeAgent: \"code-review\"\n---\nb\n", ".github/instructions/b.instructions.md": "---\nexcludeAgent: cloud-agent\n---\nb\n"}},
		{name: "AR9C3 good: legacy coding-agent still accepted", files: map[string]string{cfg: copilotCfg, ".github/instructions/a.instructions.md": "---\nexcludeAgent: \"coding-agent\"\n---\nb\n"}},
		{name: "AR9C3 good: key absent", files: map[string]string{cfg: copilotCfg, ".github/instructions/a.instructions.md": "---\napplyTo: \"**\"\n---\nb\n"}},
		// AR9C4
		{name: "AR9C4 bad: wrong suffix", files: map[string]string{cfg: copilotCfg, ".github/instructions/go.md": "# go\n"}, wantCode: CodeCopilotInstructionsName, wantSev: SeverityWarning, wantLine: 1},
		{name: "AR9C4 good: right suffix", files: map[string]string{cfg: copilotCfg, ".github/instructions/go.instructions.md": "# go\n"}},
		{name: "AR9C4 good: README ignored", files: map[string]string{cfg: copilotCfg, ".github/instructions/README.md": "# x\n"}},
		// applicability
		{name: "not configured: no cursor traps", files: map[string]string{cfg: trapConfig(`"claude"`, ""), ".cursor/rules/api.md": "# api\n"}},
		{name: "extra_harnesses turns cursor traps on", files: map[string]string{cfg: trapConfig(`"claude"`, "\n[lint.traps]\nextra_harnesses = [\"cursor\"]\n"), ".cursor/rules/api.md": "# api\n"}, wantCode: CodeCursorRuleExtension, wantSev: SeverityWarning, wantLine: 1},
		{name: "severity override wins over the generated escalation", files: map[string]string{cfg: trapConfig(`"cursor"`, "\n[lint.severity]\nAR9C1 = \"info\"\n"), ".cursor/rules/gen.md": generated + "# g\n"}, wantCode: CodeCursorRuleExtension, wantSev: SeverityInfo, wantLine: 1},
		{name: "ignored by code", files: map[string]string{cfg: trapConfig(`"cursor"`, "\n[lint]\nignore = [\"AR9C1\"]\n"), ".cursor/rules/api.md": "# api\n"}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Act
			findings := trapFindings(t, tt.files)
			// Assert
			var got []Finding
			for _, f := range findings {
				if strings.HasPrefix(f.Code, "AR9C") {
					got = append(got, f)
				}
			}
			if tt.wantCode == "" {
				if len(got) != 0 {
					t.Fatalf("want no trap findings:\n%s", dump(got))
				}
				return
			}
			if len(got) != 1 {
				t.Fatalf("want exactly one %s:\n%s", tt.wantCode, dump(got))
			}
			f := got[0]
			if f.Code != tt.wantCode || f.Severity != tt.wantSev || f.Line != tt.wantLine {
				t.Errorf("got %s %s line %d, want %s %s line %d", f.Code, f.Severity, f.Line, tt.wantCode, tt.wantSev, tt.wantLine)
			}
			if f.Trap == nil || f.Trap.Harness == "" || f.Trap.Evidence == "" || f.Trap.VerifiedOn == "" || f.Trap.Hint == "" {
				t.Errorf("finding lacks provenance: %+v", f)
			}
		})
	}
}

func TestTrapTableIsWellFormed(t *testing.T) {
	traps, err := Traps()
	if err != nil {
		t.Fatal(err)
	}
	if len(traps) == 0 {
		t.Fatal("empty trap table")
	}
	vocab := map[string]bool{predExtNotIn: true, predNameSuffixRequired: true, predFrontmatterEnum: true, predFrontmatterMissing: true, predKeyMisspelt: true, predSizeOver: true}
	seen := map[string]bool{}
	for _, tr := range traps {
		rowKey := tr.Code + "/" + tr.Harness + "/" + tr.Scope.Dir
		if seen[rowKey] {
			t.Errorf("duplicate row %s", rowKey)
		}
		seen[rowKey] = true
		rule, ok := lookupRule(tr.Code)
		switch {
		case !ok:
			t.Errorf("%s is not in the rule registry", tr.Code)
		case rule.Name != tr.Name:
			t.Errorf("%s: table name %q differs from registry name %q", tr.Code, tr.Name, rule.Name)
		}
		if !strings.HasPrefix(tr.Code, "AR9C") {
			t.Errorf("%s is outside the traps range AR9C1-AR9C9", tr.Code)
		}
		if !vocab[tr.Predicate.Kind] {
			t.Errorf("%s: unknown predicate kind %q", tr.Code, tr.Predicate.Kind)
		}
		for field, v := range map[string]string{"harness": tr.Harness, "message": tr.Message, "hint": tr.Hint, "source": tr.Source, "quote": tr.Quote, "verified_on": tr.VerifiedOn} {
			if strings.TrimSpace(v) == "" {
				t.Errorf("%s: %s is empty; a trap needs its provenance", tr.Code, field)
			}
		}
	}
}

func TestTrapDocsAreGenerated(t *testing.T) {
	want, err := TrapsMarkdown()
	if err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile("../../docs/harness-traps.md")
	if err != nil {
		t.Fatal(err)
	}
	const begin, end = "<!-- traps:begin -->\n", "<!-- traps:end -->"
	text := string(data)
	i, j := strings.Index(text, begin), strings.Index(text, end)
	if i < 0 || j < i {
		t.Fatalf("docs/harness-traps.md lacks the %q ... %q markers", begin, end)
	}
	if os.Getenv("UPDATE_DOCS") != "" {
		text = text[:i+len(begin)] + want + text[j:]
		if err := os.WriteFile("../../docs/harness-traps.md", []byte(text), 0o644); err != nil { //nolint:gosec // docs file
			t.Fatal(err)
		}
		return
	}
	if got := text[i+len(begin) : j]; got != want {
		t.Errorf("docs/harness-traps.md is out of date with traps.toml; regenerate it with UPDATE_DOCS=1 go test ./internal/lint -run TestTrapDocsAreGenerated; want:\n%s", want)
	}
}

func TestValidateTrapSettings(t *testing.T) {
	cfgOf := func(h ...string) []string { return validateTraps(&config.LintTraps{ExtraHarnesses: h}) }
	if p := cfgOf("cursor", "Copilot"); len(p) != 0 {
		t.Errorf("known harnesses rejected: %v", p)
	}
	if p := cfgOf("cursr"); len(p) != 1 || !strings.Contains(p[0], "cursr") {
		t.Errorf("typo not reported: %v", p)
	}
}
