package lint

import (
	"os"
	"strings"
	"testing"
	"time"

	"github.com/Goldziher/ai-rulez/v5/internal/config"
	"github.com/Goldziher/ai-rulez/v5/internal/harnesslimits"
)

func repeat(s string, n int) string { return strings.Repeat(s, n) }

func TestLimitAndSpellingTraps(t *testing.T) {
	const cfg = ".ai-rulez/config.toml"
	claudeCfg := trapConfig(`"claude"`, "")
	codexCfg := trapConfig(`"codex"`, "")
	devinCfg := trapConfig(`"devin"`, "")
	agyCfg := trapConfig(`"antigravity"`, "")
	skill := func(fm string) string { return "---\n" + fm + "---\n# body\n" }
	tests := []struct {
		name     string
		files    map[string]string
		wantCode string
		wantSev  Severity
		wantLine int
		wantFile string // suffix of the finding's file
	}{
		// AR9C7 skills
		{name: "AR9C7 bad: underscore for hyphen", files: map[string]string{cfg: claudeCfg, ".claude/skills/a/SKILL.md": skill("name: a\ndisable_model_invocation: true\n")}, wantCode: CodeClaudeKeySpelling, wantSev: SeverityWarning, wantLine: 3},
		{name: "AR9C7 bad: camel case user-invocable", files: map[string]string{cfg: claudeCfg, ".claude/skills/a/SKILL.md": skill("userInvocable: false\n")}, wantCode: CodeClaudeKeySpelling, wantSev: SeverityWarning, wantLine: 2},
		{name: "AR9C7 good: documented spellings", files: map[string]string{cfg: claudeCfg, ".claude/skills/a/SKILL.md": skill("name: a\nwhen_to_use: x\nuser-invocable: true\nallowed-tools: Read\n")}},
		{name: "AR9C7 good: unrelated custom key", files: map[string]string{cfg: claudeCfg, ".claude/skills/a/SKILL.md": skill("owner: me\n")}},
		{name: "AR9C7 generated escalates", files: map[string]string{cfg: claudeCfg, ".claude/skills/a/SKILL.md": skill("allowed_tools: Read\n") + "<!-- Generated by ai-rulez from x -->\n"}, wantCode: CodeClaudeKeySpelling, wantSev: SeverityError, wantLine: 2},
		// AR9C7 subagents
		{name: "AR9C7 bad: snake case maxTurns", files: map[string]string{cfg: claudeCfg, ".claude/agents/r.md": skill("name: r\nmax_turns: 5\n")}, wantCode: CodeClaudeKeySpelling, wantSev: SeverityWarning, wantLine: 3},
		{name: "AR9C7 good: camel case", files: map[string]string{cfg: claudeCfg, ".claude/agents/r.md": skill("name: r\nmaxTurns: 5\ndisallowedTools: Bash\n")}},
		{name: "AR9C7 not configured", files: map[string]string{cfg: codexCfg, ".claude/agents/r.md": skill("max_turns: 5\n")}},
		// AR9C8
		{name: "AR9C8 bad: description plus when_to_use over the cap", files: map[string]string{cfg: claudeCfg, ".claude/skills/a/SKILL.md": skill("description: " + repeat("a", 1000) + "\nwhen_to_use: " + repeat("b", 600) + "\n")}, wantCode: CodeClaudeListingTruncated, wantSev: SeverityWarning, wantLine: 1},
		{name: "AR9C8 good: exactly at the cap", files: map[string]string{cfg: claudeCfg, ".claude/skills/a/SKILL.md": skill("description: " + repeat("a", 1000) + "\nwhen_to_use: " + repeat("b", 536) + "\n")}},
		// AR9C9 devin
		{name: "AR9C9 bad: devin rule over 12000 chars", files: map[string]string{cfg: devinCfg, ".devin/rules/big.md": repeat("é", 12001)}, wantCode: CodeHarnessLimitExceeded, wantSev: SeverityWarning, wantLine: 1},
		{name: "AR9C9 good: devin rule at 12000 chars (runes, not bytes)", files: map[string]string{cfg: devinCfg, ".devin/rules/ok.md": repeat("é", 12000)}},
		// AR9C9 antigravity
		{name: "AR9C9 bad: antigravity rule over 24000 bytes", files: map[string]string{cfg: agyCfg, ".agents/rules/big.md": repeat("x", 24001)}, wantCode: CodeHarnessLimitExceeded, wantSev: SeverityWarning, wantLine: 1},
		{name: "AR9C9 good: antigravity rule at 24000 bytes", files: map[string]string{cfg: agyCfg, ".agents/rules/ok.md": repeat("x", 24000)}},
		// AR9C9 codex chain
		{name: "AR9C9 bad: single AGENTS.md over the chain limit", files: map[string]string{cfg: codexCfg, "AGENTS.md": repeat("x", 32769)}, wantCode: CodeHarnessLimitExceeded, wantSev: SeverityWarning, wantLine: 1, wantFile: "AGENTS.md"},
		{name: "AR9C9 bad: chain crosses at the nested file", files: map[string]string{cfg: codexCfg, "AGENTS.md": repeat("x", 20000), "pkg/AGENTS.md": repeat("y", 13000)}, wantCode: CodeHarnessLimitExceeded, wantSev: SeverityWarning, wantLine: 1, wantFile: "pkg/AGENTS.md"},
		{name: "AR9C9 good: siblings do not add up", files: map[string]string{cfg: codexCfg, "a/AGENTS.md": repeat("x", 20000), "b/AGENTS.md": repeat("y", 20000)}},
		{name: "AR9C9 good: at the limit", files: map[string]string{cfg: codexCfg, "AGENTS.md": repeat("x", 32768)}},
		{name: "AR9C9 [codex] project_doc_max_bytes replaces the default", files: map[string]string{cfg: trapConfig(`"codex"`, "\n[codex]\nproject_doc_max_bytes = 1000\n"), "AGENTS.md": repeat("x", 1001)}, wantCode: CodeHarnessLimitExceeded, wantSev: SeverityWarning, wantLine: 1},
		{name: "AR9C9 [codex] project_doc_max_bytes = 0 turns the check off", files: map[string]string{cfg: trapConfig(`"codex"`, "\n[codex]\nproject_doc_max_bytes = 0\n"), "AGENTS.md": repeat("x", 40000)}},
		{name: "AR9C9 not configured: no devin traps", files: map[string]string{cfg: claudeCfg, ".devin/rules/big.md": repeat("x", 13000)}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Arrange / Act
			findings := trapFindings(t, tt.files)
			// Assert
			var got []Finding
			for _, f := range findings {
				if strings.HasPrefix(f.Code, "AR9C") {
					got = append(got, f)
				}
			}
			if tt.wantCode == "" {
				if len(got) != 0 {
					t.Fatalf("want no trap findings:\n%s", dump(got))
				}
				return
			}
			if len(got) != 1 {
				t.Fatalf("want exactly one %s:\n%s", tt.wantCode, dump(got))
			}
			f := got[0]
			if f.Code != tt.wantCode || f.Severity != tt.wantSev || f.Line != tt.wantLine {
				t.Errorf("got %s %s line %d, want %s %s line %d", f.Code, f.Severity, f.Line, tt.wantCode, tt.wantSev, tt.wantLine)
			}
			if tt.wantFile != "" && !strings.HasSuffix(strings.ReplaceAll(f.File, "\\", "/"), tt.wantFile) {
				t.Errorf("finding file %s, want suffix %s", f.File, tt.wantFile)
			}
			if f.Trap == nil || f.Trap.Evidence == "" || f.Trap.VerifiedOn == "" {
				t.Errorf("finding lacks provenance: %+v", f)
			}
		})
	}
}

func TestEveryLimitRowIsWellFormed(t *testing.T) {
	limits, err := harnesslimits.All()
	if err != nil || len(limits) == 0 {
		t.Fatalf("limits table: %v (%d rows)", err, len(limits))
	}
	ids := map[string]bool{}
	for _, l := range limits {
		if ids[l.ID] {
			t.Errorf("duplicate limit %s", l.ID)
		}
		ids[l.ID] = true
		if l.Value <= 0 || l.Source == "" || l.Quote == "" || l.VerifiedOn == "" || l.Harness == "" || (l.Unit != "chars" && l.Unit != "bytes") {
			t.Errorf("%s lacks provenance or a value: %+v", l.ID, l)
		}
		if _, ok := rowAgeDays(l.VerifiedOn, time.Now()); !ok {
			t.Errorf("%s: verified_on %q is not YYYY-MM-DD", l.ID, l.VerifiedOn)
		}
	}
	traps, _ := Traps() //nolint:errcheck // checked by the table test
	for _, tr := range traps {
		if tr.Predicate.Kind == predSizeOver && tr.Quote == "" {
			t.Errorf("%s/%s: size-over row did not resolve limit %q", tr.Code, tr.Harness, tr.Predicate.LimitID)
		}
	}
}

// The duplicated size numbers elsewhere in the repository must equal the table.
func TestSizeConstantsEqualTheLimitsTable(t *testing.T) {
	want := map[string]int{
		"claude-skill-listing": harnesslimits.MustValue("claude.skill_listing_chars"),
		"codex-agents-chain":   harnesslimits.MustValue("codex.agents_md_chain_bytes"),
		"windsurf-rule-file":   harnesslimits.MustValue("devin.rule_file_chars"),
	}
	for _, b := range loadBudgets {
		if v, ok := want[b.ID]; ok && b.Limit != v {
			t.Errorf("load budget %s = %d, limits table says %d", b.ID, b.Limit, v)
		}
	}
	if config.ClaudeSkillDescriptionLimit != harnesslimits.MustValue("claude.skill_listing_chars") {
		t.Errorf("config.ClaudeSkillDescriptionLimit = %d, limits table says %d", config.ClaudeSkillDescriptionLimit, harnesslimits.MustValue("claude.skill_listing_chars"))
	}
	if config.DefaultCodexProjectDocMaxBytes != harnesslimits.MustValue("codex.agents_md_chain_bytes") {
		t.Errorf("config.DefaultCodexProjectDocMaxBytes = %d", config.DefaultCodexProjectDocMaxBytes)
	}
}

func TestHarnessTableStale(t *testing.T) {
	now := trapNow
	t.Cleanup(func() { trapNow = now })
	trapNow = func() time.Time { return time.Date(2027, 2, 1, 0, 0, 0, 0, time.UTC) } // 118 days after the rows
	const cfg = ".ai-rulez/config.toml"
	count := func(extra string) int {
		n := 0
		for _, f := range trapFindings(t, map[string]string{cfg: trapConfig(`"claude"`, extra)}) {
			if f.Code == CodeHarnessTableStale {
				n++
			}
		}
		return n
	}
	if n := count(""); n != 0 {
		t.Errorf("off by default, got %d findings", n)
	}
	if n := count("\n[lint.traps]\nmax_table_age_days = 365\n"); n != 0 {
		t.Errorf("rows are younger than 365 days, got %d findings", n)
	}
	if n := count("\n[lint.traps]\nmax_table_age_days = 30\n"); n == 0 {
		t.Error("rows are older than 30 days, want findings")
	}
}

// TestHarnessVerify backs `task harness:verify`: it lists every row with its
// source and date and fails when one is older than the allowed age. It never
// touches the network unless HARNESS_VERIFY_FETCH=1 (then it also checks that
// each quote is still on its page).
func TestHarnessVerify(t *testing.T) {
	if os.Getenv("HARNESS_VERIFY") == "" {
		t.Skip("set HARNESS_VERIFY=1 (task harness:verify) to run the freshness check")
	}
	maxAge := defaultMaxTableAgeDays
	if n := repoMaxTableAgeDays(); n > 0 {
		maxAge = n
	}
	if v := os.Getenv("HARNESS_MAX_AGE_DAYS"); v != "" {
		n, err := parsePositive(v)
		if err != nil {
			t.Fatalf("HARNESS_MAX_AGE_DAYS: %v", err)
		}
		maxAge = n
	}
	stale := 0
	for _, row := range TableRows() {
		days, ok := rowAgeDays(row.VerifiedOn, time.Now())
		t.Logf("%-5s %-60s verified_on=%s %s", row.Kind, row.ID, row.VerifiedOn, row.Source)
		if !ok || days > maxAge {
			stale++
			t.Errorf("%s %s: verified_on %q is older than %d days", row.Kind, row.ID, row.VerifiedOn, maxAge)
		}
	}
	t.Logf("%d stale rows, max age %d days", stale, maxAge)
	if os.Getenv("HARNESS_VERIFY_FETCH") == "1" {
		verifyQuotesOnline(t)
	}
}
