package commands

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestRunGuard(t *testing.T) {
	root := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(root, ".ai-rulez"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(root, ".ai-rulez", ".generated-manifest.json"),
		[]byte(`{"version":"1","files":["AGENTS.md"]}`), 0o644))
	tests := []struct {
		name       string
		payload    string
		wantCode   int
		wantStderr string
	}{
		{name: "generated file is blocked with exit 2", payload: `{"tool_name":"Edit","tool_input":{"file_path":"AGENTS.md"}}`,
			wantCode: 2, wantStderr: "AGENTS.md is generated by ai-rulez"},
		{name: "other file passes silently", payload: `{"tool_name":"Edit","tool_input":{"file_path":"main.go"}}`},
		{name: "garbage passes silently", payload: `not json`},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Arrange
			var stderr bytes.Buffer

			// Act
			code := runGuard(strings.NewReader(tt.payload), &stderr, root)

			// Assert
			assert.Equal(t, tt.wantCode, code)
			if tt.wantStderr == "" {
				assert.Empty(t, stderr.String())
				return
			}
			assert.Contains(t, stderr.String(), tt.wantStderr)
		})
	}
}

func TestGuardCmd_IsRegisteredAndListed(t *testing.T) {
	cmd, _, err := RootCmd.Find([]string{"guard"})

	require.NoError(t, err)
	assert.Same(t, GuardCmd, cmd)
	assert.False(t, cmd.Hidden, "guard is a documented command, listed in --help")
}
