package commands

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/Goldziher/ai-rulez/internal/agents"
	"github.com/Goldziher/ai-rulez/internal/config"
	"github.com/Goldziher/ai-rulez/internal/hooks"
	"github.com/Goldziher/ai-rulez/internal/logger"
	"github.com/Goldziher/ai-rulez/internal/templates"
	"github.com/samber/oops"
	"github.com/spf13/cobra"
)

var (
	allProviders     bool
	popularProviders bool
	withAgents       bool
	withSections     bool
	noComments       bool
	preset           string
	useAgent         string
	noAgent          bool
	listAgents       bool
	setupHooks       bool

	claudeFlag      bool
	cursorFlag      bool
	windsurfFlag    bool
	copilotFlag     bool
	geminiFlag      bool
	ampFlag         bool
	codexFlag       bool
	clineFlag       bool
	continueDevFlag bool
)

// InitCmd represents the init command
var InitCmd = &cobra.Command{
	Use:   "init [project-name]",
	Short: "Initialize a new AI rules configuration",
	Long: `Initialize a new AI rules configuration for your project.
This creates an ai_rulez.yaml file with sensible defaults and 
configures outputs for your selected AI assistants.`,
	Args: cobra.MaximumNArgs(1),
	Run:  runInit,
}

func init() {
	InitCmd.Flags().BoolVar(&allProviders, "all", false, "Enable all supported providers")
	InitCmd.Flags().BoolVar(&popularProviders, "popular", false, "Enable popular providers (Claude, Cursor, Windsurf, Copilot)")
	InitCmd.Flags().StringVar(&preset, "preset", "", "Use a preset configuration (claude, cursor, windsurf, copilot, etc.)")

	InitCmd.Flags().BoolVar(&claudeFlag, "claude", false, "Include Claude configuration")
	InitCmd.Flags().BoolVar(&cursorFlag, "cursor", false, "Include Cursor configuration")
	InitCmd.Flags().BoolVar(&windsurfFlag, "windsurf", false, "Include Windsurf configuration")
	InitCmd.Flags().BoolVar(&copilotFlag, "copilot", false, "Include GitHub Copilot configuration")
	InitCmd.Flags().BoolVar(&geminiFlag, "gemini", false, "Include Gemini configuration")
	InitCmd.Flags().BoolVar(&ampFlag, "amp", false, "Include AMP configuration")
	InitCmd.Flags().BoolVar(&codexFlag, "codex", false, "Include Codex configuration")
	InitCmd.Flags().BoolVar(&clineFlag, "cline", false, "Include Cline configuration")
	InitCmd.Flags().BoolVar(&continueDevFlag, "continue-dev", false, "Include Continue.dev configuration")

	InitCmd.Flags().BoolVar(&withAgents, "with-agents", false, "Include agent configurations (for Claude)")
	InitCmd.Flags().BoolVar(&withSections, "with-sections", true, "Include documentation sections")
	InitCmd.Flags().BoolVar(&noComments, "no-comments", false, "Omit explanatory comments from the generated config")

	InitCmd.Flags().StringVar(&useAgent, "use-agent", "", "Use an AI agent to generate configuration (claude, gemini, etc.)")
	InitCmd.Flags().BoolVar(&noAgent, "no-agent", false, "Skip AI agent detection and usage")
	InitCmd.Flags().BoolVar(&listAgents, "list-agents", false, "List available AI agents and exit")

	InitCmd.Flags().BoolVar(&setupHooks, "setup-hooks", false, "Automatically configure git hooks for ai-rulez validation if lefthook, pre-commit, or husky is detected")
}

func runInit(cmd *cobra.Command, args []string) {
	if handleListAgents() {
		return
	}

	checkExistingConfig()
	projectName := getProjectName(args)
	providerConfig := parseProviderFlags(cmd)

	if tryAgentGeneration(cmd, projectName, providerConfig) {
		return
	}

	generateAndWriteConfig(projectName, providerConfig)
	handleContinueDevSetup(providerConfig)
	displaySuccessMessage(projectName, providerConfig)

	if setupHooks {
		handleHooksSetup()
	}
}

func handleContinueDevSetup(providerConfig templates.ProviderConfig) {
	if !providerConfig.ContinueDev {
		return
	}

	configPyContent := `# Welcome to Continue.dev!
#
# This file is the central configuration for the Continue.dev extension.
# For more information, see the documentation at https://continue.dev/docs/customization

from continuedev.core.config import Config, CustomLLM
from continuedev.core.models import Models
from continuedev.plugins.context_providers import FileContextProvider, TerminalContextProvider
from continuedev.plugins.steps import OpenFileStep, RunTerminalCommandStep

# ------------------------------------------------------------------
# AI Rulez Integration - Import your generated agents
# ------------------------------------------------------------------
# ai-rulez generates a file with a list of CustomLLM objects.
# Import this list to add your agents to Continue.dev.
try:
    from .continue.ai_rulez_agents import generated_agents
except ImportError:
    generated_agents = []
# ------------------------------------------------------------------


config = Config(
    # Add your models here.
    # For more information, see https://continue.dev/docs/customization/models
    models=Models(
        default=CustomLLM(
            model="gpt-4-turbo",
            system_message="You are an expert software developer.",
        ),
        # Add the agents generated by ai-rulez
        custom_llms=generated_agents,
    ),

    # Define your context providers.
    # For more information, see https://continue.dev/docs/customization/context-providers
    context_providers=[
        FileContextProvider(),
        TerminalContextProvider(),
    ],

    # Define your slash commands.
    # For more information, see https://continue.dev/docs/customization/slash-commands
    slash_commands=[
        OpenFileStep(),
        RunTerminalCommandStep(
            name="bash",
            description="Run a bash command",
            prompt="Enter a bash command",
        ),
    ],
)
`
	configPyPath := "config.py"
	if _, err := os.Stat(configPyPath); os.IsNotExist(err) {
		if err := os.WriteFile(configPyPath, []byte(configPyContent), 0o644); err != nil {
			logger.Warn(fmt.Sprintf("Failed to create sample %s: %v", configPyPath, err))
		} else {
			logger.Info(fmt.Sprintf("  - Created sample %s to get you started", configPyPath))
		}
	} else {
		logger.Info(fmt.Sprintf("  - Found existing %s. To use ai-rulez agents, add the following:", configPyPath))
		logger.Info(`
# 1. Import the generated agents at the top of your config.py
try:
    from .continue.ai_rulez_agents import generated_agents
except ImportError:
    generated_agents = []

# 2. Add the imported agents to your 'custom_llms' list
config = Config(
    models=Models(
        ...
        custom_llms=generated_agents,
        ...
    ),
    ...
)
`)
	}
}

func handleListAgents() bool {
	if listAgents {
		agents.ListAvailableAgents()
		return true
	}
	return false
}

func checkExistingConfig() {
	if _, err := config.FindConfigFile("."); err == nil {
		logger.Error("Configuration file already exists in this directory")
		logger.Info("Remove or rename the existing file to initialize a new configuration")
		os.Exit(1)
	}
}

func getProjectName(args []string) string {
	projectName := "MyProject"
	if len(args) > 0 {
		projectName = args[0]
	} else {
		if cwd, err := os.Getwd(); err == nil {
			projectName = filepath.Base(cwd)
		}
	}
	return projectName
}

func tryAgentGeneration(cmd *cobra.Command, projectName string, providerConfig templates.ProviderConfig) bool {
	if !noAgent && (useAgent != "" || agents.ShouldPromptForAgent()) {
		generatedConfig, handled := agents.HandleAgentGeneration(cmd, projectName, providerConfig, useAgent)
		if handled {
			writeConfigFile(generatedConfig)
			logger.Info("✅ Configuration generated successfully with AI assistance")
			return true
		}
	}
	return false
}

func generateAndWriteConfig(projectName string, providerConfig templates.ProviderConfig) {
	configContent := templates.GenerateConfigTemplate(projectName, providerConfig)
	writeConfigFile(configContent)
}

func writeConfigFile(content string) {
	if err := os.WriteFile("ai_rulez.yaml", []byte(content), 0o644); err != nil {
		logger.LogError("Failed to write configuration file", oops.
			With("path", "ai_rulez.yaml").
			Wrapf(err, "write file"))
		os.Exit(1)
	}
}

func displaySuccessMessage(projectName string, providerConfig templates.ProviderConfig) {
	logger.Info("✅ Created ai_rulez.yaml", "project", projectName)
	logger.Info("Configuration includes:")

	displayProviderIncludes(providerConfig)
	displayNextSteps()
}

func displayProviderIncludes(providerConfig templates.ProviderConfig) {
	if providerConfig.Claude {
		logger.Info("  - Claude (CLAUDE.md)")
		if withAgents {
			logger.Info("  - Claude agents (.claude/agents/)")
		}
	}
	if providerConfig.Cursor {
		logger.Info("  - Cursor (.cursor/rules/)")
	}
	if providerConfig.Windsurf {
		logger.Info("  - Windsurf (.windsurf/)")
	}
	if providerConfig.Copilot {
		logger.Info("  - GitHub Copilot (.github/copilot-instructions.md)")
	}
	if providerConfig.Gemini {
		logger.Info("  - Gemini (GEMINI.md)")
	}
	if providerConfig.Amp || providerConfig.Codex {
		logger.Info("  - AMP/Codex (AGENTS.md)")
	}
	if providerConfig.Cline {
		logger.Info("  - Cline (.clinerules/)")
	}
	if providerConfig.ContinueDev {
		logger.Info("  - Continue.dev rules (.continue/rules/)")
		logger.Info("  - Continue.dev agents (.continue/ai_rulez_agents.py)")
	}
}

func displayNextSteps() {
	logger.Info("\nNext steps:")
	logger.Info("  1. Edit ai_rulez.yaml to customize your rules and sections")
	logger.Info("  2. Run 'ai-rulez generate' to create the output files")

	if hooks.DetectGitHooks() != "" {
		logger.Info("  3. Consider setting up git hooks for automatic generation")
	}
}

func parseProviderFlags(cmd *cobra.Command) templates.ProviderConfig {
	if preset != "" {
		return parsePresetFlag()
	}

	if allProviders {
		return parseAllProvidersFlag()
	}

	if popularProviders {
		return parsePopularProvidersFlag()
	}

	return parseIndividualFlags(cmd)
}

func parsePresetFlag() templates.ProviderConfig {
	presetMap := map[string]func(*templates.ProviderConfig){
		"claude":       func(pc *templates.ProviderConfig) { pc.Claude = true },
		"cursor":       func(pc *templates.ProviderConfig) { pc.Cursor = true },
		"windsurf":     func(pc *templates.ProviderConfig) { pc.Windsurf = true },
		"copilot":      func(pc *templates.ProviderConfig) { pc.Copilot = true },
		"gemini":       func(pc *templates.ProviderConfig) { pc.Gemini = true },
		"amp":          func(pc *templates.ProviderConfig) { pc.Amp = true },
		"codex":        func(pc *templates.ProviderConfig) { pc.Codex = true },
		"cline":        func(pc *templates.ProviderConfig) { pc.Cline = true },
		"continue-dev": func(pc *templates.ProviderConfig) { pc.ContinueDev = true },
		"continue":     func(pc *templates.ProviderConfig) { pc.ContinueDev = true },
	}

	pc := templates.ProviderConfig{}
	if setter, exists := presetMap[preset]; exists {
		setter(&pc)
	}
	return pc
}

func parseAllProvidersFlag() templates.ProviderConfig {
	return templates.ProviderConfig{
		Claude:      true,
		Cursor:      true,
		Windsurf:    true,
		Copilot:     true,
		Gemini:      true,
		Amp:         true,
		Codex:       true,
		Cline:       true,
		ContinueDev: true,
	}
}

func parsePopularProvidersFlag() templates.ProviderConfig {
	return templates.ProviderConfig{
		Claude:   true,
		Cursor:   true,
		Windsurf: true,
		Copilot:  true,
	}
}

func parseIndividualFlags(cmd *cobra.Command) templates.ProviderConfig {
	pc := templates.ProviderConfig{
		Claude:      claudeFlag,
		Cursor:      cursorFlag,
		Windsurf:    windsurfFlag,
		Copilot:     copilotFlag,
		Gemini:      geminiFlag,
		Amp:         ampFlag,
		Codex:       codexFlag,
		Cline:       clineFlag,
		ContinueDev: continueDevFlag,
	}

	if !pc.HasAny() {
		pc.Claude = true
	}

	if pc.Claude && !cmd.Flags().Changed("with-agents") {
		withAgents = true
	}

	return pc
}

func handleHooksSetup() {
	logger.Info("\nDetecting git hook managers...")

	hookSystem := hooks.DetectGitHooks()
	if hookSystem == "" {
		logger.Info("  - No git hook manager detected")
		logger.Info("    Install lefthook, pre-commit, or husky to enable automatic validation")
		return
	}

	logger.Info(fmt.Sprintf("  - Found %s configuration", hooks.GetHookSystemName(hookSystem)))

	if err := hooks.SetupHooks(); err != nil {
		logger.Warn(fmt.Sprintf("    Failed to setup %s: %v", hooks.GetHookSystemName(hookSystem), err))
	} else {
		logger.Info(fmt.Sprintf("  ✅ Successfully configured %s for ai-rulez validation", hooks.GetHookSystemName(hookSystem)))
		logger.Info("    Your AI rules will be validated automatically on git commit")
	}
}
