metadata:
  name: "cli"
  description: "Command-line tool development practices"

rules:
  - name: "CLI UX"
    priority: 20
    content: |
      Design intuitive command interfaces. Use clear subcommands, helpful error messages, and follow Unix conventions.

  - name: "Flag Design"
    priority: 19
    content: |
      Provide both short and long flag options. Use sensible defaults and support environment variable configuration.

  - name: "Help & Documentation"
    priority: 18
    content: |
      Provide comprehensive help text, usage examples, and man pages. Include --help and --version flags.

  - name: "Output Formatting"
    priority: 17
    content: |
      Support multiple output formats (JSON, table, plain text). Provide quiet and verbose modes for different use cases.

  - name: "Cross-platform Support"
    priority: 16
    content: |
      Ensure the CLI works across different operating systems. Handle path separators and platform-specific behaviors.

  - name: "Installation & Distribution"
    priority: 15
    content: |
      Provide easy installation methods (package managers, single binaries). Include upgrade mechanisms and proper versioning.