metadata:
  name: "default"
  description: "Core engineering best practices for any project"

rules:
  - name: "Code Quality"
    priority: 10
    content: |
      Write clean, readable, and maintainable code. Follow established patterns and conventions for your language and framework.

  - name: "Error Handling"
    priority: 9
    content: |
      Handle errors gracefully and provide meaningful error messages. Don't ignore errors or fail silently.

  - name: "Documentation"
    priority: 7
    content: |
      Document public APIs, complex logic, and architectural decisions. Keep documentation up to date with code changes.

  - name: "Testing"
    priority: 8
    content: |
      Write tests for critical functionality. Focus on edge cases and error conditions.

  - name: "Security"
    priority: 9
    content: |
      Follow security best practices. Never expose sensitive data, validate inputs, and use secure defaults.

  - name: "Performance"
    priority: 6
    content: |
      Write efficient code but prioritize readability. Profile before optimizing and measure the impact of changes.