metadata:
  name: "library"
  description: "Reusable library and package development practices"

rules:
  - name: "Public API Design"
    priority: 20
    content: |
      Design stable, minimal public APIs. Follow semantic versioning and clearly separate public from internal interfaces.

  - name: "Backward Compatibility"
    priority: 19
    content: |
      Maintain backward compatibility within major versions. Use deprecation warnings before breaking changes.

  - name: "Dependencies"
    priority: 18
    content: |
      Minimize external dependencies. When adding dependencies, choose well-maintained, stable packages.

  - name: "Documentation & Examples"
    priority: 17
    content: |
      Provide comprehensive documentation with runnable examples. Include getting started guides and API references.

  - name: "Testing & CI"
    priority: 16
    content: |
      Maintain high test coverage and test against multiple environments. Use continuous integration for all supported versions.

  - name: "Packaging & Distribution"
    priority: 15
    content: |
      Follow platform packaging conventions. Provide clear installation instructions and support multiple package managers.