metadata:
  name: "web-app"
  description: "Frontend web application development practices"

rules:
  - name: "Component Architecture"
    priority: 20
    content: |
      Build reusable, composable components. Keep components focused on a single responsibility and use clear prop interfaces.

  - name: "State Management"
    priority: 19
    content: |
      Use appropriate state management patterns. Keep state close to where it's used and avoid unnecessary re-renders.

  - name: "Accessibility"
    priority: 18
    content: |
      Build accessible interfaces. Use semantic HTML, proper ARIA labels, and keyboard navigation support.

  - name: "Bundle Optimization"
    priority: 17
    content: |
      Optimize bundle size through code splitting, tree shaking, and lazy loading. Monitor bundle size in CI.

  - name: "Browser Compatibility"
    priority: 16
    content: |
      Ensure cross-browser compatibility. Use feature detection and polyfills when necessary.

  - name: "SEO & Meta Tags"
    priority: 15
    content: |
      Implement proper SEO practices including meta tags, structured data, and server-side rendering when needed.