package presets

import (
	"strings"

	"github.com/Goldziher/ai-rulez/internal/config"
	"github.com/Goldziher/ai-rulez/internal/generator/rulefiles"
	"github.com/Goldziher/ai-rulez/internal/templates"
)

// RenderLocalRootRules renders the body of a machine-local root override file
// (CLAUDE.local.md, AGENTS.local.md, GEMINI.local.md, ...). It emits the same
// generated-file header plus "## Rules" and "## Context" sections, reusing the
// exact inline-rule and inline-context formatting as the committed root file so
// local overrides read identically to the files they augment.
//
// allRules is the rules the root inlines: the caller removes the ones written
// as personal rule files. Context comes from the local tree (skills/agents are
// out of scope for local overrides). outputFile is the local variant's path
// relative to the base dir, used only for the header banner.
func RenderLocalRootRules(local *config.ContentTree, allRules []config.ContentFile, cfg *config.Config, outputFile string) string {
	return RenderLocalRootRulesFor(local, allRules, cfg, outputFile, strings.Replace(outputFile, ".local.md", ".md", 1))
}

// RenderLocalRootRulesFor is RenderLocalRootRules for a local file whose name does
// not derive from the shared root file it stands in for (sharedRoot), such as
// .junie/rules/ai-rulez.local.md for a root AGENTS.md. sharedRoot decides which
// items a frontmatter targets list selects.
func RenderLocalRootRulesFor(local *config.ContentTree, allRules []config.ContentFile, cfg *config.Config,
	outputFile, sharedRoot string,
) string {
	var builder strings.Builder

	allRules = rulefiles.FilterInline(allRules, rulefiles.RootTarget("", sharedRoot))
	allContext := rulefiles.FilterInline(allInlineContext(local), rulefiles.RootTarget("", sharedRoot))

	data := &templates.TemplateData{
		ProjectName:  cfg.Name,
		Timestamp:    cfg.HeaderTimestamp(),
		ConfigFile:   configFileName(cfg),
		OutputFile:   outputFile,
		Config:       cfg,
		RuleCount:    len(allRules),
		SectionCount: 0,
		AgentCount:   0,
	}
	builder.WriteString(templates.GenerateHeader(data))
	builder.WriteString(localSections(allRules, allContext, cfg))
	return builder.String()
}

// localSections renders the "## Rules" and "## Context" sections of a local root
// file, with the exact formatting of the committed root files.
func localSections(allRules, allContext []config.ContentFile, cfg *config.Config) string {
	var builder strings.Builder
	rulefiles.WriteInlineRules(&builder, allRules, rulefiles.InlineOpts{Compact: cfg.IsCompact(), AppliesTo: true}, nil)
	rulefiles.WriteInlineContext(&builder, allContext, rulefiles.InlineOpts{Compact: cfg.IsCompact(), AppliesTo: true, ContextSummary: true}, nil)
	return builder.String()
}

// AgentsOverrideFile is the machine-local file Codex and Hermes load in place of
// AGENTS.md in the same directory (the first of AGENTS.override.md, AGENTS.md
// wins), so it has to carry the shared content as well as the local one.
const AgentsOverrideFile = "AGENTS.override.md"

// RenderAgentsOverride renders AGENTS.override.md: a banner saying what the file
// is, the shared AGENTS.md exactly as written this run (header included), then
// the local rule and context sections formatted like the .local root files. owners
// are the presets that read the file, which select the items targeted at them.
// It reports false when the local content leaves nothing to add.
func RenderAgentsOverride(sharedAgentsMD string, local *config.ContentTree, rules []config.ContentFile,
	cfg *config.Config, owners []string,
) (string, bool) {
	root := rulefiles.Target{RootFile: string(config.SharedAgentsMD), Owners: owners}
	allRules := rulefiles.FilterInline(rules, root)
	allContext := rulefiles.FilterInline(allInlineContext(local), root)
	sections := localSections(allRules, allContext, cfg)
	if strings.TrimSpace(sections) == "" {
		return "", false
	}

	var builder strings.Builder
	builder.WriteString(templates.GenerateHeader(&templates.TemplateData{
		ProjectName: cfg.Name,
		Timestamp:   cfg.HeaderTimestamp(),
		ConfigFile:  configFileName(cfg),
		OutputFile:  AgentsOverrideFile,
		Config:      cfg,
		RuleCount:   len(allRules),
	}))
	builder.WriteString("<!--\nGenerated machine-local file, never committed. It replaces AGENTS.md for Codex and Hermes,\n" +
		"so it repeats AGENTS.md and appends your local rules and context.\n" +
		"It is regenerated by `ai-rulez generate`; edit " + localDirLabel(cfg) + " instead.\n-->\n\n")
	builder.WriteString(sharedAgentsMD)
	if !strings.HasSuffix(sharedAgentsMD, "\n") {
		builder.WriteString("\n")
	}
	builder.WriteString(sections)
	return builder.String(), true
}

// localDirLabel is the project-relative directory machine-local content lives in.
func localDirLabel(cfg *config.Config) string {
	dir := strings.TrimSpace(cfg.ConfigDirName)
	if dir == "" {
		dir = ".ai-rulez"
	}
	return dir + "/local/"
}
