package hookplugins

import (
	"fmt"
	"os"
	"regexp"
	"strings"

	"github.com/Goldziher/ai-rulez/v5/internal/diag"
)

// moduleMarker opens the first line of every generated module (see
// templates/header.tmpl). It is the provenance check that keeps ai-rulez from
// overwriting a hand-written plugin that happens to share the file name.
const moduleMarker = "// Generated by ai-rulez"

// MayWriteModule reports whether ai-rulez may write the module at path: the file
// is absent or was generated by ai-rulez (its first line carries the marker). A
// file the consumer wrote is theirs; it is left alone and a warning says so.
func MayWriteModule(d *diag.Collector, path string) bool {
	data, err := os.ReadFile(path) //nolint:gosec // path is derived from the preset layout and the base directory
	if err != nil {
		if os.IsNotExist(err) {
			return true
		}
		d.Warn("[[hooks]] plugin not generated: cannot read the existing " + path + ": " + err.Error())
		return false
	}
	first, _, _ := strings.Cut(string(data), "\n")
	if strings.HasPrefix(strings.TrimRight(first, "\r"), moduleMarker) {
		return true
	}
	d.Warn("[[hooks]] plugin not generated: "+path+" already exists and was not written by ai-rulez",
		"hint", "rename or remove it to let ai-rulez write the hooks plugin")
	return false
}

// matcherProblem returns why a matcher cannot be evaluated the same way by Go and
// by the generated module's JavaScript RegExp, or "" when it can. The runtime
// wraps a matcher as ^(?:matcher)$, so a matcher that does not stand on its own
// (`a)|(b`) could escape the anchoring, and one the runtime fails to compile
// matches nothing, which for a blocking hook fails open. Only the syntax both
// engines read identically is accepted.
func matcherProblem(matcher string) string {
	if problem := incompatibleSyntax(matcher); problem != "" {
		return problem
	}
	if _, err := regexp.Compile(matcher); err != nil {
		return strings.TrimPrefix(err.Error(), "error parsing regexp: ")
	}
	return ""
}

func incompatibleSyntax(matcher string) string {
	inClass := false
	for i := 0; i < len(matcher); i++ {
		switch c := matcher[i]; {
		case c == '\\':
			i++
			if i >= len(matcher) {
				return "a trailing backslash"
			}
			if strings.ContainsRune("zZAQEpPkK123456789", rune(matcher[i])) {
				return fmt.Sprintf(`\%c is not portable`, matcher[i])
			}
		case inClass && c == '[' && i+1 < len(matcher) && matcher[i+1] == ':':
			return "POSIX classes are not portable"
		case inClass && c == ']':
			inClass = false
		case !inClass && c == '[':
			inClass = true
		case !inClass && c == '(' && i+1 < len(matcher) && matcher[i+1] == '?':
			if i+2 >= len(matcher) || matcher[i+2] != ':' {
				return "only (?: groups are portable"
			}
		}
	}
	return ""
}
