// Package clidocs renders the command reference of docs/ from the Cobra command
// tree, so the documented commands, flags, defaults and examples are the ones the
// binary has. scripts/clidocs writes the output; a test in cmd/commands fails
// when the checked-in docs differ from it.
//
// The output is deterministic: it depends only on the tree.
package clidocs

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// Markers delimit the generated command index inside a hand-written page.
const (
	IndexBegin = "<!-- BEGIN GENERATED: command-index (go run ./scripts/clidocs) -->"
	IndexEnd   = "<!-- END GENERATED: command-index -->"
)

// ReferenceHeader opens the generated reference page.
const ReferenceHeader = `# CLI Command Reference

<!-- Generated by ` + "`go run ./scripts/clidocs`" + ` from the command tree. Do not edit; change the command and rerun. -->

Every command, with its usage, aliases, examples and flags, generated from the
binary's own command tree. The flags every command accepts (` + "`--config`, `--config-dir`, `--debug`, `--quiet`, `--token`" + ` and the ` + "`--policy*`" + ` family) are in
[Global Flags](cli.md#global-flags); the prose for each command is in the [CLI Reference](cli.md).
`

// commands returns the documented commands below root, depth first in the
// order cobra lists them (alphabetical), root excluded.
func commands(root *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		subs := append([]*cobra.Command(nil), c.Commands()...)
		sort.SliceStable(subs, func(i, j int) bool { return subs[i].Name() < subs[j].Name() })
		for _, s := range subs {
			if s.Hidden || s.Name() == "help" {
				continue
			}
			out = append(out, s)
			walk(s)
		}
	}
	walk(root)
	return out
}

// bareURL matches a URL not already inside <...>, so cell can autolink it the way
// the markdown formatter would (keeping the generated page formatter-stable).
var bareURL = regexp.MustCompile(`(^|[\s(])(https?://[^\s)|<>]+)`)

func cell(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	s = strings.ReplaceAll(s, "\n", " ")
	return bareURL.ReplaceAllString(s, "$1<$2>")
}

// Index renders the table of every command with its one-line summary.
func Index(root *cobra.Command) string {
	var b strings.Builder
	b.WriteString("| Command | Summary |\n| ------- | ------- |\n")
	for _, c := range commands(root) {
		fmt.Fprintf(&b, "| `%s` | %s |\n", c.CommandPath(), cell(c.Short))
	}
	return b.String()
}

// Reference renders the full reference page.
func Reference(root *cobra.Command) string {
	var b strings.Builder
	b.WriteString(ReferenceHeader)
	for _, c := range commands(root) {
		fmt.Fprintf(&b, "\n## `%s`\n\n%s\n\n", c.CommandPath(), c.Short)
		fmt.Fprintf(&b, "```text\n%s\n```\n", c.UseLine())
		if len(c.Aliases) > 0 {
			fmt.Fprintf(&b, "\nAliases: `%s`\n", strings.Join(c.Aliases, "`, `"))
		}
		if ex := strings.TrimSpace(c.Example); ex != "" {
			b.WriteString("\nExamples:\n\n```bash\n")
			for _, line := range strings.Split(ex, "\n") {
				b.WriteString(strings.TrimPrefix(line, "  ") + "\n")
			}
			b.WriteString("```\n")
		}
		writeFlags(&b, root, c)
	}
	return b.String()
}

// writeFlags lists the flags of c: its own and those it inherits from a group
// command (roles --format), but not the root's global flags.
func writeFlags(b *strings.Builder, root, c *cobra.Command) {
	var rows []string
	add := func(f *pflag.Flag) {
		if f.Hidden || f.Name == "help" || root.PersistentFlags().Lookup(f.Name) != nil {
			return
		}
		name := "`--" + f.Name + "`"
		if f.Shorthand != "" {
			name += " / `-" + f.Shorthand + "`"
		}
		rows = append(rows, fmt.Sprintf("| %s | %s | %s | %s |", name, flagType(f), defaultOf(f), cell(f.Usage)))
	}
	c.LocalFlags().VisitAll(add)
	c.InheritedFlags().VisitAll(add)
	if len(rows) == 0 {
		return
	}
	b.WriteString("\n| Flag | Type | Default | Description |\n| ---- | ---- | ------- | ----------- |\n")
	b.WriteString(strings.Join(rows, "\n") + "\n")
}

func flagType(f *pflag.Flag) string {
	switch t := f.Value.Type(); t {
	case "stringSlice", "stringArray":
		return "string list"
	case "float64":
		return "number"
	case "int64":
		return "int"
	default:
		return t
	}
}

func defaultOf(f *pflag.Flag) string {
	switch f.DefValue {
	case "", "[]", "false":
		return ""
	}
	return "`" + cell(f.DefValue) + "`"
}

// ApplyIndex returns page with the text between the index markers replaced by
// the index. It fails when the page has no marker pair.
func ApplyIndex(page, index string) (string, error) {
	begin := strings.Index(page, IndexBegin)
	end := strings.Index(page, IndexEnd)
	if begin < 0 || end < begin {
		return "", fmt.Errorf("the page has no %q ... %q block", IndexBegin, IndexEnd)
	}
	return page[:begin+len(IndexBegin)] + "\n\n" + index + "\n" + page[end:], nil
}
