// Generated by ai-rulez. Registers the skills, commands, and agents bundled beside this file
// with OpenCode v2. OpenCode only scans its own config directories, so a plugin installed from
// npm has to register its bundled content itself.
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";

const root = import.meta.dirname;

function parse(text) {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/u.exec(text);
  if (!match) return { meta: {}, body: text };
  const meta = {};
  for (const line of match[1].split(/\r?\n/u)) {
    const pair = /^([A-Za-z0-9_-]+):\s*(.*)$/u.exec(line);
    if (pair) meta[pair[1]] = pair[2].trim().replace(/^(["'])(.*)\1$/u, "$2");
  }
  return { meta, body: match[2] };
}

async function entries(dir) {
  try {
    return (await readdir(path.join(root, dir), { withFileTypes: true })).toSorted((a, b) =>
      a.name.localeCompare(b.name),
    );
  } catch {
    return [];
  }
}

async function load() {
  const skills = [];
  for (const entry of await entries("skills")) {
    if (!entry.isDirectory()) continue;
    const file = path.join(root, "skills", entry.name, "SKILL.md");
    try {
      const { meta, body } = parse(await readFile(file, "utf8"));
      skills.push({
        id: entry.name,
        name: meta.name || entry.name,
        description: meta.description,
        path: file,
        content: body,
      });
    } catch {}
  }
  const commands = [];
  for (const entry of await entries("commands")) {
    if (!entry.isFile() || !entry.name.endsWith(".md")) continue;
    const { meta, body } = parse(await readFile(path.join(root, "commands", entry.name), "utf8"));
    commands.push({ name: entry.name.slice(0, -3), description: meta.description, template: body });
  }
  const agents = [];
  for (const entry of await entries("agents")) {
    if (!entry.isFile() || !entry.name.endsWith(".md")) continue;
    const { meta, body } = parse(await readFile(path.join(root, "agents", entry.name), "utf8"));
    agents.push({ id: entry.name.slice(0, -3), description: meta.description, mode: meta.mode, system: body.trim() });
  }
  return { skills, commands, agents };
}

export async function registerBundledContent(ctx) {
  const { skills, commands, agents } = await load();
  if (skills.length > 0) {
    await ctx.skill.transform((editor) => {
      for (const skill of skills) if (!editor.get(skill.id)) editor.add(skill);
    });
  }
  if (commands.length > 0) {
    await ctx.command.transform((editor) => {
      for (const command of commands) {
        editor.add({
          name: command.name,
          description: command.description,
          execute: async ({ sessionID, prompt, delivery }) => {
            await ctx.session.prompt({
              ...prompt,
              sessionID,
              text: command.template.replaceAll("$ARGUMENTS", prompt.text),
              delivery,
            });
          },
        });
      }
    });
  }
  if (agents.length > 0) {
    await ctx.agent.transform((editor) => {
      for (const agent of agents) {
        editor.update(agent.id, (item) => {
          if (agent.description) item.description = agent.description;
          if (["subagent", "primary", "all"].includes(agent.mode)) item.mode = agent.mode;
          if (agent.system) item.system = agent.system;
        });
      }
    });
  }
}
