// Generated by ai-rulez. Registers the skills, commands, agents, and MCP servers bundled with
// this plugin in OpenCode v2. OpenCode only scans its own config directories, so a plugin installed from
// npm has to register its bundled content itself.
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";

const root = import.meta.dirname;

function parse(text) {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/u.exec(text);
  if (!match) return { meta: {}, body: text };
  const meta = {};
  for (const line of match[1].split(/\r?\n/u)) {
    const pair = /^([A-Za-z0-9_-]+):\s*(.*)$/u.exec(line);
    if (pair) meta[pair[1]] = pair[2].trim().replace(/^(["'])(.*)\1$/u, "$2");
  }
  return { meta, body: match[2] };
}

async function entries(dir) {
  try {
    return (await readdir(path.join(root, dir), { withFileTypes: true })).toSorted((a, b) =>
      a.name.localeCompare(b.name),
    );
  } catch {
    return [];
  }
}

async function readBundle() {
  try {
    return JSON.parse(await readFile(path.join(root, "ai-rulez-bundle.json"), "utf8"));
  } catch {
    return {};
  }
}

// Plugin install directory: the parent of the .opencode directory this file lives in.
const pluginRoot = path.dirname(root);

// Resolves ${PLUGIN_ROOT} to the install directory and ${NAME} to process.env at runtime,
// so no install path or secret is baked into the package.
function expand(value) {
  return value.replaceAll(/\$\{([A-Za-z_][A-Za-z0-9_]*)\}/gu, (_, name) =>
    name === "PLUGIN_ROOT" ? pluginRoot : (process.env[name] ?? ""),
  );
}

function mcpServer(server) {
  if (server.type === "remote") return { type: "remote", url: expand(server.url) };
  const entry = { type: "local", command: server.command.map(expand) };
  if (server.environment) {
    entry.environment = Object.fromEntries(
      Object.entries(server.environment).map(([key, value]) => [key, expand(value)]),
    );
  }
  return entry;
}

async function load() {
  const bundle = await readBundle();
  const skills = [];
  for (const entry of await entries("skills")) {
    if (!entry.isDirectory()) continue;
    const file = path.join(root, "skills", entry.name, "SKILL.md");
    try {
      const { meta, body } = parse(await readFile(file, "utf8"));
      skills.push({
        id: entry.name,
        name: meta.name || entry.name,
        description: meta.description,
        path: file,
        content: body,
      });
    } catch {}
  }
  const commands = [];
  for (const entry of await entries("commands")) {
    if (!entry.isFile() || !entry.name.endsWith(".md")) continue;
    const { meta, body } = parse(await readFile(path.join(root, "commands", entry.name), "utf8"));
    commands.push({ name: entry.name.slice(0, -3), description: meta.description, template: body });
  }
  const agents = [];
  for (const entry of await entries("agents")) {
    if (!entry.isFile() || !entry.name.endsWith(".md")) continue;
    const { meta, body } = parse(await readFile(path.join(root, "agents", entry.name), "utf8"));
    const id = entry.name.slice(0, -3);
    // The bundle holds settings resolved at generation time (the model in particular); the
    // frontmatter fallback never carries a model, since a bare alias is not valid in OpenCode.
    const settings = bundle.agents?.[id] ?? { description: meta.description, mode: meta.mode };
    agents.push({ id, system: body.trim(), settings });
  }
  return { skills, commands, agents, mcp: bundle.mcp ?? {} };
}

export async function registerBundledContent(ctx) {
  const { skills, commands, agents, mcp } = await load();
  if (skills.length > 0) {
    await ctx.skill.transform((editor) => {
      for (const skill of skills) if (!editor.get(skill.id)) editor.add(skill);
    });
  }
  if (commands.length > 0) {
    await ctx.command.transform((editor) => {
      for (const command of commands) {
        editor.add({
          name: command.name,
          description: command.description,
          execute: async ({ sessionID, prompt, delivery }) => {
            await ctx.session.prompt({
              ...prompt,
              sessionID,
              text: command.template.replaceAll("$ARGUMENTS", prompt.text),
              delivery,
            });
          },
        });
      }
    });
  }
  if (agents.length > 0) {
    await ctx.agent.transform((editor) => {
      for (const agent of agents) {
        editor.update(agent.id, (item) => {
          const settings = agent.settings;
          if (settings.description) item.description = settings.description;
          if (["subagent", "primary", "all"].includes(settings.mode)) item.mode = settings.mode;
          if (typeof settings.hidden === "boolean") item.hidden = settings.hidden;
          if (typeof settings.model === "string" && settings.model.includes("/")) {
            const split = settings.model.indexOf("/");
            item.model = { providerID: settings.model.slice(0, split), id: settings.model.slice(split + 1) };
            if (settings.variant) item.model.variant = settings.variant;
          }
          for (const key of ["temperature", "top_p"]) {
            if (typeof settings[key] === "number") item.request.body[key] = settings[key];
          }
          if (agent.system) item.system = agent.system;
        });
      }
    });
  }
  if (Object.keys(mcp).length > 0) {
    await ctx.mcp.transform((editor) => {
      for (const [name, server] of Object.entries(mcp)) editor.set(name, mcpServer(server));
    });
  }
}
