package settings

import (
	"fmt"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Goldziher/ai-rulez/v5/internal/config"
)

// Cline has no hooks document: it runs the executable named after an event in
// .clinerules/hooks (user level: ~/Documents/Cline/Hooks), one per event. The
// vendor's current documentation only covers SDK plugins; the file contract
// (extensionless executable named after the event, JSON on stdin, JSON on stdout,
// both levels run) was read from the vendor's source, apps/vscode/src/core/hooks/utils.ts
// and sdk/packages/core/src/hooks/hook-file-config.ts, on 2026-10-05. ai-rulez
// renders one wrapper script per event that runs the configured commands.

// ClineHooksDir is the project directory of Cline hook scripts.
const ClineHooksDir = ".clinerules/hooks"

// ClineHookMarker marks a script as generated (it is also the banner the stale
// pass recognises); a script without it is the consumer's and is never overwritten.
const ClineHookMarker = "Generated by ai-rulez"

// clineEvents maps Claude Code events to Cline's. SessionStart and Stop map to
// the task lifecycle (TaskStart, TaskComplete), which is an inference: Cline
// documents no mapping.
var clineEvents = map[string]string{
	eventUserPromptSubmit: "UserPromptSubmit", eventPreToolUse: "PreToolUse", eventPostToolUse: "PostToolUse",
	eventPreCompact: "PreCompact", eventSessionStart: "TaskStart", eventStop: "TaskComplete",
}

// ClineHookEvents returns the native event names of the Cline hook scripts, sorted.
func ClineHookEvents() []string {
	names := make([]string, 0, len(clineEvents))
	for _, native := range clineEvents {
		names = append(names, native)
	}
	sort.Strings(names)
	return names
}

// HookScript is a generated hook script: the file name below the hooks directory
// and its body.
type HookScript struct {
	Name string
	Body string
}

// ClineHookScripts renders the Cline wrapper scripts for cfg.Hooks, sorted by
// name. A group Cline cannot express is skipped with a warning: Cline hooks have
// no matcher, timeout, async or condition.
func ClineHookScripts(cfg *config.Config) []HookScript {
	if cfg == nil || len(cfg.Hooks) == 0 || inScopeRun(cfg) {
		return nil
	}
	const harness = config.HarnessCline
	commands := map[string][]string{}
	needsRoot := map[string]bool{}
	for i := range cfg.Hooks {
		g := &cfg.Hooks[i]
		if !g.HookTargetsHarness(harness) {
			continue
		}
		native, ok := clineEvents[g.Event]
		if !ok {
			warn(cfg.Diag, harness, fmt.Sprintf("the event %s has no equivalent", g.Event), "hint", "restrict the group with targets, or remove it")
			continue
		}
		if matcher := g.Matchers[harness]; g.Matcher != "" || matcher != "" {
			warn(cfg.Diag, harness, fmt.Sprintf("Cline hooks have no matcher, so the %s group would run on every occurrence", g.Event),
				"hint", "remove the matcher or set targets to leave this harness out")
			continue
		}
		for j := range g.Hooks {
			action := &g.Hooks[j]
			if reason := clineUnsupported(action); reason != "" {
				warn(cfg.Diag, harness, fmt.Sprintf("a %s handler %s", g.Event, reason))
				continue
			}
			if action.Script != "" && !config.IsSafeHookScript(action.Script) {
				warn(cfg.Diag, harness, fmt.Sprintf("a %s handler has an unsafe script %q; a script path may only contain letters, digits, '.', '_', '-' and '/'",
					g.Event, action.Script))
				continue
			}
			line, usesRoot := clineCommand(cfg, action)
			commands[native] = append(commands[native], line)
			needsRoot[native] = needsRoot[native] || usesRoot
		}
	}
	names := make([]string, 0, len(commands))
	for native := range commands {
		names = append(names, native)
	}
	sort.Strings(names)
	scripts := make([]HookScript, 0, len(names))
	for _, native := range names {
		scripts = append(scripts, HookScript{Name: native, Body: clineScript(native, commands[native], needsRoot[native])})
	}
	return scripts
}

func clineUnsupported(action *config.HookAction) string {
	switch {
	case action.Type != "" && action.Type != config.HookTypeCommand:
		return fmt.Sprintf("has type %q; only command handlers are generated", action.Type)
	case action.Timeout > 0:
		return "sets a timeout, which Cline documents no way to express"
	case action.Async:
		return "is async, which Cline cannot express"
	case action.If != "":
		return "sets 'if', which Cline has no equivalent of"
	}
	return ""
}

// clineCommand is the shell line that runs an action with the hook payload on
// stdin. A project script is addressed from the wrapper's own location, because
// Cline documents no project-root variable.
func clineCommand(cfg *config.Config, action *config.HookAction) (line string, usesRoot bool) {
	command := action.Command
	if action.Script != "" {
		script := path.Clean(filepath.ToSlash(action.Script))
		if cfg.UserScope {
			command = quote(filepath.Join(cfg.ConfigDir, filepath.FromSlash(script)))
		} else {
			command = `"$root"/` + quote(script)
			usesRoot = true
		}
	}
	if len(action.Args) > 0 {
		command += " " + shellJoin(action.Args)
	}
	return command, usesRoot
}

// clineStdinLimit bounds the hook input the wrapper reads into memory (16 MiB).
const clineStdinLimit = 16 * 1024 * 1024

// IsClineHookGenerated reports whether a script body is one ai-rulez generated:
// the marker must open the comment on the line after the shebang. A marker
// anywhere else (a comment in a hand-written hook that quotes it) is not
// provenance, so such a script is never overwritten.
func IsClineHookGenerated(body []byte) bool {
	lines := strings.SplitN(string(body), "\n", 3)
	return len(lines) >= 2 && strings.HasPrefix(lines[0], "#!") &&
		strings.HasPrefix(strings.TrimRight(lines[1], "\r"), "# "+ClineHookMarker)
}

// clineScript renders a wrapper. Each command runs inside a { ... } group fed the
// hook input, so `cd x && y`, `a; b` and `a | b` stay one unit with one status; the
// newline before the closing brace keeps a trailing `# comment` from swallowing it.
// The pipeline's status is the group's, so a failing command propagates through
// `|| exit $?` (or as the script's own status for the last one).
func clineScript(event string, commands []string, needsRoot bool) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# " + ClineHookMarker + " (" + event + " hook): edit [[hooks]] in .ai-rulez/config.toml, not this file.\n")
	b.WriteString("# Every command receives the hook input on stdin; the last one's output is the hook's output,\n")
	b.WriteString("# and the first command that fails stops the rest.\n")
	if needsRoot {
		b.WriteString("root=$(cd \"$(dirname \"$0\")/../..\" && pwd)\n")
	}
	fmt.Fprintf(&b, "input=$(head -c %d)\n", clineStdinLimit)
	for i, command := range commands {
		if i < len(commands)-1 {
			fmt.Fprintf(&b, "printf '%%s\\n' \"$input\" | { %s\n} >/dev/null || exit $?\n", command)
			continue
		}
		fmt.Fprintf(&b, "printf '%%s\\n' \"$input\" | { %s\n}\n", command)
	}
	return b.String()
}
