package settings

import (
	"encoding/json"
	"strings"

	"github.com/Goldziher/ai-rulez/internal/config"
)

// CodexRulesPath is the Starlark rules file ai-rulez owns outright. Codex loads
// every *.rules file of .codex/rules (project, when trusted) and ~/.codex/rules.
const CodexRulesPath = ".codex/rules/ai-rulez.rules"

// Codex CLI: `prefix_rule(pattern=[argv tokens], decision="allow|prompt|forbidden")`.
// A pattern is a token prefix of the command's argv and the most restrictive
// matching rule wins, so the order of the rules does not matter. Only shell
// commands have a rule surface; paths and domains live in named permission
// profiles (`default_permissions`), which cannot be combined with `sandbox_mode`
// and are therefore not generated: filesystem, network and MCP rules are skipped
// with a warning.
//
// Sources: https://learn.chatgpt.com/docs/agent-configuration/rules and
// https://learn.chatgpt.com/docs/config-file/config-reference (read 2026-10-05;
// the rules page marks the feature experimental).
const codexRulesHeader = "# Generated by ai-rulez from [permissions]. Do not edit; change .ai-rulez/config.toml and regenerate.\n"

var codexDecisions = map[PermAction]string{ActionAllow: "allow", ActionAsk: "prompt", ActionDeny: "forbidden"}

// shellUnsafe are the characters a token must not contain to be a literal argv
// element; anything else needs shell parsing the rules file would not do.
const shellUnsafe = "\"'\\$`|&;<>()*?[]{}~#!\n\t"

// CodexRules renders .codex/rules/ai-rulez.rules. ok is false when no rule can be
// expressed, in which case the file is not generated.
func CodexRules(cfg *config.Config) (body string, ok bool) {
	if !applicable(cfg) {
		return "", false
	}
	t := newTranslation(cfg, config.HarnessCodex, "")
	var b strings.Builder
	b.WriteString(codexRulesHeader)
	n := 0
	for _, e := range t.entries {
		tokens, why := codexTokens(e)
		if why != "" {
			t.drop(e, why)
			continue
		}
		pattern, _ := json.Marshal(tokens)
		b.WriteString("\nprefix_rule(\n    pattern = " + string(pattern) + ",\n    decision = \"" + codexDecisions[e.Action] + "\",\n)\n")
		n++
	}
	if n == 0 {
		return "", false
	}
	return b.String(), true
}

func codexTokens(e permEntry) ([]string, string) {
	r := e.Rule
	if r.Kind != KindShell {
		return nil, "Codex has no rule surface for " + r.Tool + " (paths, domains and MCP tools need a permission profile, which replaces sandbox_mode)"
	}
	p := r.Shell()
	switch p.Kind {
	case ShellPrefix:
	case ShellExact:
		if e.Action == ActionAllow {
			return nil, "Codex rules match a token prefix, so an exact-command allow would be widened"
		}
	case ShellAny:
		return nil, "a rule needs a command to match; allow or deny of every command is approval_policy and sandbox_mode"
	default:
		return nil, "Codex rules match token prefixes; wildcards inside a command cannot be expressed"
	}
	tokens := strings.Fields(p.Literal)
	for _, tok := range tokens {
		if strings.ContainsAny(tok, shellUnsafe) {
			return nil, "the command has shell syntax that a token rule cannot match literally"
		}
	}
	if len(tokens) == 0 {
		return nil, "empty command"
	}
	return tokens, ""
}
