metadata:
  name: "Security Rules"

# This is an include file - outputs not needed when included
outputs:
  - file: "security-rules.md"

rules:
  - name: "Input Validation"
    priority: 20
    content: |
      - Validate all user inputs
      - Sanitize data before database operations
      - Use parameterized queries
      - Implement rate limiting

  - name: "Authentication"
    priority: 20
    content: |
      - Use strong password policies
      - Implement multi-factor authentication
      - Use secure session management
      - Log authentication attempts

  - name: "Data Protection"
    priority: 10
    content: |
      - Encrypt sensitive data at rest
      - Use HTTPS for all communications
      - Implement proper access controls
      - Regular security audits