package templates

// Built-in template definitions
const (
	defaultTemplate = `# {{.ProjectName}}
{{- if .Description}}

{{.Description}}
{{- end}}
{{- if .Version}}

Version: {{.Version}}
{{- end}}

Generated on {{.Timestamp.Format "2006-01-02 15:04:05"}}
{{- if or .RuleCount .SectionCount}}

Total content: {{.RuleCount}} rules, {{.SectionCount}} sections
{{- end}}
{{- range .AllContent}}
{{- if .IsRule}}

## {{.Title}}

**Priority:** {{.Priority}}

{{.Content}}
{{- else}}

{{.Content}}
{{- end}}
{{- end}}
`

	minimalTemplate = `{{range .Rules}}{{.Content}}

{{end}}`

	documentationTemplate = `# {{.ProjectName}} Documentation
{{- if .Description}}

{{.Description}}
{{- end}}

Generated on {{.Timestamp.Format "2006-01-02 15:04:05"}}

{{- range .Sections}}
## {{.Name}}

{{.Content}}

{{- end}}
{{- range .Rules}}
## {{.Name}}

**Priority:** {{.Priority}}

{{.Content}}

{{- end}}
`

	// MCP Server templates for different tools
	claudeCodeMCPTemplate = `{
{{- range $i, $server := .MCPServers}}
{{- if ne $i 0}},{{end}}
  "{{$server.Name}}": {
    "type": "{{$server.GetTransport}}"
{{- if and (ne $server.GetTransport "http") (ne $server.GetTransport "sse")}}{{if $server.Command}},
    "command": "{{$server.Command}}"{{end}}
{{- if $server.Args}},
    "args": [{{range $j, $arg := $server.Args}}{{if ne $j 0}}, {{end}}"{{$arg}}"{{end}}]{{end}}
{{- if $server.Env}},
    "env": {
{{- range $key, $value := $server.Env}}
      "{{$key}}": "{{$value}}"{{end}}
    }{{end}}
{{- else}}{{if $server.URL}},
    "url": "{{$server.URL}}"{{end}}
{{- end}}
  }
{{- end}}
}`

	cursorMCPTemplate = `{
  "McpServers": {
{{- range $i, $server := .MCPServers}}
{{- if ne $i 0}},{{end}}
    "{{$server.Name}}": {
{{- if or $server.Command (eq $server.GetTransport "stdio")}}
      "command": "{{$server.Command}}"
{{- if $server.Args}},
      "args": [{{range $j, $arg := $server.Args}}{{if ne $j 0}}, {{end}}"{{$arg}}"{{end}}]{{end}}
{{- if $server.Env}},
      "env": {
{{- range $key, $value := $server.Env}}
        "{{$key}}": "{{$value}}"{{end}}
      }{{end}}
{{- else if $server.URL}}
      "url": "{{$server.URL}}"
{{- end}}
    }
{{- end}}
  }
}`

	windsurfMCPTemplate = `{
  "mcpServers": {
{{- range $i, $server := .MCPServers}}
{{- if ne $i 0}},{{end}}
    "{{$server.Name}}": {
      "command": "{{$server.Command}}"
{{- if $server.Args}},
      "args": [{{range $j, $arg := $server.Args}}{{if ne $j 0}}, {{end}}"{{$arg}}"{{end}}]{{end}}
{{- if $server.Env}},
      "env": {
{{- range $key, $value := $server.Env}}
        "{{$key}}": "{{$value}}"{{end}}
      }{{end}}
    }
{{- end}}
  }
}`

	vscodeMCPTemplate = `{
  "servers": {
{{- range $i, $server := .MCPServers}}
{{- if ne $i 0}},{{end}}
    "{{$server.Name}}": {
      "type": "{{$server.GetTransport}}"
{{- if or $server.Command (eq $server.GetTransport "stdio")}},
      "command": "{{$server.Command}}"
{{- if $server.Args}},
      "args": [{{range $j, $arg := $server.Args}}{{if ne $j 0}}, {{end}}"{{$arg}}"{{end}}]{{end}}
{{- else if $server.URL}},
      "url": "{{$server.URL}}"
{{- end}}
    }
{{- end}}
  }
}`

	continuedevMCPTemplate = `name: {{.ProjectName}} MCP Configuration
version: 1.0.0
schema: v1
mcpServers:
{{- range .MCPServers}}
- name: {{.Name}}
{{- if .Description}}
  description: {{.Description}}
{{- end}}
{{- if ne .GetTransport "stdio"}}
  type: {{if eq .GetTransport "http"}}streamable-http{{else}}{{.GetTransport}}{{end}}
{{- end}}
{{- if or .Command (eq .GetTransport "stdio")}}
  command: {{.Command}}
{{- if .Args}}
  args:
{{- range .Args}}
  - "{{.}}"
{{- end}}
{{- end}}
{{- end}}
{{- if .URL}}
  url: {{.URL}}
{{- end}}
{{- if .Env}}
  env:
{{- range $key, $value := .Env}}
    {{$key}}: {{$value}}
{{- end}}
{{- end}}
{{- end}}
`

	clineMCPTemplate = `{
  "mcpServers": {
{{- range $i, $server := .MCPServers}}
{{- if ne $i 0}},{{end}}
    "{{$server.Name}}": {
{{- if $server.Command}}
      "command": "{{$server.Command}}"
{{- if $server.Args}},
      "args": [{{range $j, $arg := $server.Args}}{{if ne $j 0}}, {{end}}"{{$arg}}"{{end}}]{{end}}
{{- if $server.Env}},
      "env": {
{{- range $key, $value := $server.Env}}
        "{{$key}}": "{{$value}}"{{end}}
      }{{end}},
{{- end}}
      "disabled": {{if $server.IsEnabled}}false{{else}}true{{end}}
    }
{{- end}}
  }
}`

	continuedevAgentsTemplate = `# 🤖 GENERATED FILE - DO NOT EDIT DIRECTLY
# This file was generated by ai-rulez.
# To update, edit your ai_rulez.yaml and run 'ai-rulez generate'.

from continuedev.core.config import CustomLLM

# A list of agents generated from your ai_rulez.yaml configuration.
generated_agents = [
{{- range .Agents}}
    CustomLLM(
        title="{{.Name}}",
        model="{{.Model}}",
        system_message="""{{.SystemPrompt}}"""
    ),
{{- end}}
]
`
)

// getBuiltinTemplates returns all built-in templates
func getBuiltinTemplates() map[string]string {
	return map[string]string{
		"default":            defaultTemplate,
		"minimal":            minimalTemplate,
		"documentation":      documentationTemplate,
		"claude-code-mcp":    claudeCodeMCPTemplate,
		"cursor-mcp":         cursorMCPTemplate,
		"windsurf-mcp":       windsurfMCPTemplate,
		"vscode-mcp":         vscodeMCPTemplate,
		"continuedev-mcp":    continuedevMCPTemplate,
		"cline-mcp":          clineMCPTemplate,
		"continuedev-agents": continuedevAgentsTemplate,
	}
}
