package compression

// englishStopwords is a comprehensive set of English stopwords
var englishStopwords = map[string]struct{}{
	"a": {}, "about": {}, "above": {}, "after": {}, "again": {}, "against": {},
	"all": {}, "am": {}, "an": {}, "and": {}, "any": {}, "are": {}, "aren't": {},
	"as": {}, "at": {}, "be": {}, "because": {}, "been": {}, "before": {},
	"being": {}, "below": {}, "between": {}, "both": {}, "but": {}, "by": {},
	"can": {}, "can't": {}, "cannot": {}, "could": {}, "couldn't": {},
	"did": {}, "didn't": {}, "do": {}, "does": {}, "doesn't": {}, "doing": {},
	"don't": {}, "down": {}, "during": {}, "each": {}, "few": {}, "for": {},
	"from": {}, "further": {}, "get": {}, "got": {}, "had": {}, "hadn't": {},
	"has": {}, "hasn't": {}, "have": {}, "haven't": {}, "having": {},
	"he": {}, "he'd": {}, "he'll": {}, "he's": {}, "her": {}, "here": {},
	"here's": {}, "hers": {}, "herself": {}, "him": {}, "himself": {}, "his": {},
	"how": {}, "how's": {}, "i": {}, "i'd": {}, "i'll": {}, "i'm": {}, "i've": {},
	"if": {}, "in": {}, "into": {}, "is": {}, "isn't": {}, "it": {}, "it's": {},
	"its": {}, "itself": {}, "just": {}, "let's": {}, "me": {}, "might": {},
	"more": {}, "most": {}, "mustn't": {}, "my": {}, "myself": {},
	"no": {}, "nor": {}, "not": {}, "of": {}, "off": {}, "on": {}, "once": {},
	"only": {}, "or": {}, "other": {}, "ought": {}, "our": {}, "ours": {},
	"ourselves": {}, "out": {}, "over": {}, "own": {},
	"same": {}, "shan't": {}, "she": {}, "she'd": {}, "she'll": {}, "she's": {},
	"should": {}, "shouldn't": {}, "so": {}, "some": {}, "such": {},
	"than": {}, "that": {}, "that's": {}, "the": {}, "their": {}, "theirs": {},
	"them": {}, "themselves": {}, "then": {}, "there": {}, "there's": {},
	"these": {}, "they": {}, "they'd": {}, "they'll": {}, "they're": {},
	"they've": {}, "this": {}, "those": {}, "through": {}, "to": {}, "too": {},
	"under": {}, "until": {}, "up": {}, "very": {},
	"was": {}, "wasn't": {}, "we": {}, "we'd": {}, "we'll": {}, "we're": {},
	"we've": {}, "were": {}, "weren't": {}, "what": {}, "what's": {},
	"when": {}, "when's": {}, "where": {}, "where's": {}, "which": {},
	"while": {}, "who": {}, "who's": {}, "whom": {}, "why": {}, "why's": {},
	"will": {}, "with": {}, "won't": {}, "would": {}, "wouldn't": {},
	"you": {}, "you'd": {}, "you'll": {}, "you're": {}, "you've": {},
	"your": {}, "yours": {}, "yourself": {}, "yourselves": {},
	"also": {}, "already": {}, "always": {}, "another": {}, "anything": {},
	"around": {}, "away": {}, "back": {}, "became": {}, "become": {},
	"becomes": {}, "becoming": {}, "began": {}, "behind": {}, "believed": {},
	"beside": {}, "besides": {}, "best": {}, "better": {}, "beyond": {},
	"big": {}, "came": {}, "certain": {}, "certainly": {}, "come": {},
	"comes": {}, "coming": {}, "could've": {}, "currently": {}, "despite": {},
	"different": {}, "done": {}, "either": {}, "else": {}, "enough": {},
	"especially": {}, "even": {}, "every": {}, "everyone": {}, "everything": {},
	"exactly": {}, "far": {}, "find": {}, "first": {}, "found": {},
	"gave": {}, "general": {}, "give": {}, "given": {}, "goes": {},
	"going": {}, "gone": {}, "good": {}, "great": {},
	"hence": {}, "however": {}, "indeed": {}, "instead": {},
	"keep": {}, "kept": {}, "kind": {}, "knew": {}, "know": {}, "known": {},
	"knows": {}, "large": {}, "last": {}, "later": {}, "least": {}, "less": {},
	"like": {}, "likely": {}, "little": {}, "long": {}, "look": {},
	"looked": {}, "looking": {}, "looks": {},
	"made": {}, "make": {}, "makes": {}, "making": {}, "many": {}, "may": {},
	"maybe": {}, "much": {}, "must": {}, "need": {}, "never": {}, "new": {},
	"next": {}, "nothing": {}, "now": {}, "often": {}, "old": {}, "one": {},
	"ones": {}, "others": {}, "part": {}, "perhaps": {}, "place": {},
	"point": {}, "put": {}, "quite": {}, "rather": {}, "really": {},
	"right": {}, "said": {}, "say": {}, "says": {}, "second": {}, "see": {},
	"seem": {}, "seemed": {}, "seems": {}, "seen": {}, "several": {},
	"shall": {}, "since": {}, "small": {}, "something": {}, "sometimes": {},
	"soon": {}, "still": {}, "sure": {}, "take": {}, "taken": {}, "tell": {},
	"thing": {}, "things": {}, "think": {}, "third": {}, "thought": {},
	"three": {}, "thus": {}, "together": {}, "told": {}, "took": {},
	"toward": {}, "towards": {}, "try": {}, "trying": {}, "turned": {},
	"two": {}, "upon": {}, "us": {}, "use": {}, "used": {}, "using": {},
	"usually": {}, "want": {}, "wanted": {}, "wants": {}, "way": {},
	"well": {}, "went": {}, "whether": {}, "whole": {}, "whose": {},
	"without": {}, "work": {}, "worked": {}, "working": {}, "works": {},
	"world": {}, "would've": {}, "yet": {},
}
