#!/usr/bin/env bash
# Render the Homebrew formula for a release from its checksums.txt, and optionally push it to the tap.
#
# Usage: update-homebrew-formula.sh <version> <checksums.txt> [--push]
#   Without --push the formula goes to stdout.
#   With --push it is committed to Goldziher/homebrew-tap (Formula/ai-rulez.rb, branch main) using
#   HOMEBREW_TAP_GITHUB_TOKEN; an unchanged formula is a no-op, so reruns are idempotent.
# Fails closed: a missing checksum for any of the four Homebrew platforms is an error.
set -euo pipefail

if [ $# -lt 2 ] || [ $# -gt 3 ]; then
  echo "Usage: $0 <version> <checksums.txt> [--push]" >&2
  exit 2
fi
VERSION="${1#v}"
SUMS="$2"
PUSH="${3:-}"
[ -z "$PUSH" ] || [ "$PUSH" = "--push" ] || {
  echo "unknown option: $PUSH" >&2
  exit 2
}
TAP_REPO="${HOMEBREW_TAP_REPO:-Goldziher/homebrew-tap}"
BASE="https://github.com/Goldziher/ai-rulez/releases/download/v${VERSION}"

sha_for() {
  awk -v f="ai-rulez_${VERSION}_$1.tar.gz" '{n=$NF; sub(/^[*]/, "", n); if (n == f) print $1}' "$SUMS"
}

MAC_ARM="$(sha_for darwin_arm64)"
MAC_X64="$(sha_for darwin_amd64)"
LINUX_ARM="$(sha_for linux_arm64)"
LINUX_X64="$(sha_for linux_amd64)"

for pair in "darwin_arm64:$MAC_ARM" "darwin_amd64:$MAC_X64" "linux_arm64:$LINUX_ARM" "linux_amd64:$LINUX_X64"; do
  if [ -z "${pair#*:}" ]; then
    echo "missing checksum for ${pair%%:*} in $SUMS" >&2
    exit 1
  fi
  if ! [[ "${pair#*:}" =~ ^[0-9a-f]{64}$ ]]; then
    echo "invalid checksum for ${pair%%:*} in $SUMS" >&2
    exit 1
  fi
done

render() {
  cat <<EOF
# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-formula.sh in Goldziher/ai-rulez. Do not edit by hand.
class AiRulez < Formula
  desc "Standards-compliant lifecycle tool for agent knowledge and capabilities: author, generate, bundle, validate, govern, publish"
  homepage "https://goldziher.github.io/ai-rulez/"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE}/ai-rulez_${VERSION}_darwin_arm64.tar.gz"
      sha256 "${MAC_ARM}"
    end
    on_intel do
      url "${BASE}/ai-rulez_${VERSION}_darwin_amd64.tar.gz"
      sha256 "${MAC_X64}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE}/ai-rulez_${VERSION}_linux_arm64.tar.gz"
      sha256 "${LINUX_ARM}"
    end
    on_intel do
      url "${BASE}/ai-rulez_${VERSION}_linux_amd64.tar.gz"
      sha256 "${LINUX_X64}"
    end
  end

  def install
    bin.install "ai-rulez"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ai-rulez version")
  end
end
EOF
}

if [ -z "$PUSH" ]; then
  render
  exit 0
fi

: "${HOMEBREW_TAP_GITHUB_TOKEN:?HOMEBREW_TAP_GITHUB_TOKEN is required with --push}"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
# The token goes through an askpass helper, never into argv, the remote URL or the log.
cat >"$work/askpass.sh" <<'EOS'
#!/bin/sh
case "$1" in
Username*) echo x-access-token ;;
*) echo "$HOMEBREW_TAP_GITHUB_TOKEN" ;;
esac
EOS
chmod +x "$work/askpass.sh"
export GIT_ASKPASS="$work/askpass.sh" GIT_TERMINAL_PROMPT=0

git clone --quiet --depth 1 --branch main "https://github.com/${TAP_REPO}.git" "$work/tap"
mkdir -p "$work/tap/Formula"
render >"$work/tap/Formula/ai-rulez.rb"
cd "$work/tap"
if git diff --quiet -- Formula/ai-rulez.rb && git ls-files --error-unmatch Formula/ai-rulez.rb >/dev/null 2>&1; then
  echo "Formula already up to date for ${VERSION}"
  exit 0
fi
git add Formula/ai-rulez.rb
git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
  commit --quiet -m "Brew formula update for ai-rulez version v${VERSION}"
git push --quiet origin HEAD:main
echo "Pushed Formula/ai-rulez.rb for ${VERSION} to ${TAP_REPO}"
