package importer

import (
	"io/fs"
	"path"
	"regexp"
	"sort"
	"strings"

	"github.com/Goldziher/ai-rulez/v5/internal/generator"
	"github.com/Goldziher/ai-rulez/v5/internal/lint"
	"github.com/Goldziher/ai-rulez/v5/internal/utils"
)

const nativeName = "native"

// generatedMarker is in the header of every file ai-rulez generates; importing
// one back would turn our own output into source.
const generatedMarker = "AI-RULEZ ::"

var pointerOnly = regexp.MustCompile(`^@\S+$`)

type nativeImporter struct{}

func (nativeImporter) Name() string { return nativeName }

func (nativeImporter) Description() string {
	return "native tool files: CLAUDE.md, AGENTS.md, GEMINI.md, .cursor/rules, .github/instructions, .kiro/steering, .windsurf, .roo, .clinerules, skills, agents, commands and MCP files"
}

func (nativeImporter) Detect(fsys fs.FS) []string {
	r := newReader(fsys)
	var found []string
	for _, s := range nativeSources() {
		if _, ok := r.exists(s.Path); ok {
			found = append(found, s.Path)
		}
	}
	for _, m := range mcpFiles {
		if _, ok := r.exists(m.Path); ok {
			found = append(found, m.Path)
		}
	}
	for _, f := range nativeSettingsFiles {
		if _, ok := r.exists(f); ok {
			found = append(found, f)
		}
	}
	sort.Strings(found)
	return dedupeStrings(found)
}

func (n nativeImporter) Plan(fsys fs.FS, opt Options) (*Plan, error) {
	p := &Plan{}
	r := newReader(fsys)
	r.loadGeneratedManifests()
	sources := nativeSources()
	nested := nestedSourcePaths(sources)
	presetsSeen := map[string]bool{}

	onSkip := func(name, reason string) {
		p.add(newFinding(StatusDropped, name, "", "", reason))
	}
	for _, s := range sources {
		isDir, ok := r.exists(s.Path)
		if !ok {
			continue
		}
		if preset := s.impliedPreset(); preset != "" {
			presetsSeen[preset] = true
		}
		switch {
		case !isDir:
			n.importRootFile(p, r, s.Path, opt)
		case s.Kind == KindRule:
			n.importRules(p, r, s.Path, nested, onSkip)
		case s.Kind == KindSkill:
			n.importSkills(p, r, s.Path, opt, onSkip)
		case s.Kind == KindAgent, s.Kind == KindCommand:
			n.importFlat(p, r, s, onSkip)
		case s.Kind == KindContext:
			p.add(newFinding(StatusDropped, s.Path, "", "", "expected a file, found a directory"))
		}
	}
	importMCP(p, r)
	importClaudeSettings(p, r)
	importCursorPermissions(p, r)
	reportUnmappedPermissions(p, r)
	importNativeHooks(p, r)
	r.flushProblems(p)

	for preset := range presetsSeen {
		p.Presets = append(p.Presets, preset)
	}
	return p, nil
}

// nestedSourcePaths lists source directories that sit inside another source
// directory (.clinerules/workflows inside .clinerules), so the outer walk skips them.
func nestedSourcePaths(sources []nativeSource) map[string]bool {
	out := map[string]bool{}
	for _, s := range sources {
		out[s.Path] = true
	}
	return out
}

// isGenerated reports whether a file is ai-rulez output: it carries the
// `AI-RULEZ ::` header, or the generator's own banner check (GENERATED FILE,
// Generated by ai-rulez) matches it, judged by the file's extension.
func isGenerated(file string, data []byte) bool {
	head := data
	if len(head) > 2048 {
		head = head[:2048]
	}
	if strings.Contains(string(head), generatedMarker) {
		return true
	}
	for _, line := range strings.Split(string(head), "\n") {
		if strings.HasPrefix(line, "# Content-Hash: ") || strings.HasPrefix(line, "# Source-Hash: ") {
			return true // the freshness lines of generated frontmatter
		}
	}
	return generator.HasGeneratedBanner(file, data)
}

// isGeneratedFile also consults the manifest of the last generate run.
func (r *reader) isGeneratedFile(file string, data []byte) bool {
	return r.generated[file] || isGenerated(file, data)
}

func (nativeImporter) readOrReport(p *Plan, r *reader, file string) ([]byte, bool) {
	data, err := r.read(file)
	if err != nil {
		reason := skipReason(err)
		if reason == "" {
			reason = "could not be read: " + err.Error()
		}
		p.add(newFinding(StatusDropped, file, "", "", reason))
		return nil, false
	}
	if r.isGeneratedFile(file, data) {
		p.add(newFinding(StatusDropped, file, "", "", "generated by ai-rulez; not imported as source"))
		return nil, false
	}
	return data, true
}

// unnamedLabel is what utils.SanitizeName returns when nothing usable is left,
// which is every name without an ASCII letter or digit (日本語, 規則).
const unnamedLabel = "unnamed"

// safeName sanitises raw into an ai-rulez name. A name with nothing usable left
// gets a stable label derived from the original, so two such names stay
// distinct instead of colliding on "unnamed"; synthesized reports that.
func safeName(raw string) (name string, synthesized bool) {
	name = utils.SanitizeName(raw)
	if name == unnamedLabel && strings.ToLower(strings.TrimSpace(raw)) != unnamedLabel {
		return unnamedLabel + "-" + shortHash(raw), true
	}
	return name, false
}

func contextName(file string) string {
	name, _ := safeName(strings.TrimLeft(baseNoExt(file), "."))
	return name
}

func (n nativeImporter) importRootFile(p *Plan, r *reader, file string, opt Options) {
	data, ok := n.readOrReport(p, r, file)
	if !ok {
		return
	}
	text := normalizeText(string(data))
	if pointerOnly.MatchString(strings.TrimSpace(text)) {
		p.add(newFinding(StatusDropped, file, "", "", "only points at another file ("+strings.TrimSpace(text)+")"))
		return
	}
	if strings.TrimSpace(text) == "" {
		p.add(newFinding(StatusDropped, file, "", "", "file is empty"))
		return
	}
	text = n.nestRootKeys(p, file, text)
	name := contextName(file)
	if !opt.SplitHeadings {
		p.Items = append(p.Items, Item{Kind: KindContext, Name: name, Sources: []string{file}, Main: ensureNewline(text)})
		return
	}
	for _, sec := range splitH2(text) {
		secName := name
		if sec.header != "" {
			hdr, _ := safeName(sec.header)
			secName = name + "-" + hdr
		}
		body := sec.body
		if sec.header != "" {
			body = "## " + sec.header + "\n\n" + sec.body
		}
		if strings.TrimSpace(sec.body) == "" && sec.header == "" {
			continue
		}
		p.Items = append(p.Items, Item{Kind: KindContext, Name: secName, Sources: []string{file}, Main: ensureNewline(body)})
	}
}

// nestRootKeys keeps a root file's frontmatter keys that no tool reads (title,
// applies_to, updated) under `metadata:` rather than at the top level, where the
// strict validator would report each one (AR303), and says so.
func (nativeImporter) nestRootKeys(p *Plan, file, text string) string {
	out, moved := nestUnknownKeys(text, lint.KnownContextKeys())
	if len(moved) > 0 {
		p.add(newFinding(StatusApproximated, file, "frontmatter", "",
			"frontmatter keys no tool reads were kept under metadata: "+strings.Join(moved, ", ")))
	}
	return out
}

type h2Section struct{ header, body string }

// splitH2 splits Markdown at "## " headings outside code fences. The text
// before the first heading is its own section with an empty header. A fence
// opens with three or more backticks or tildes (indented at most three spaces)
// and closes only with the same character, at least as long, and no info string.
func splitH2(text string) []h2Section {
	var out []h2Section
	cur := h2Section{}
	var b strings.Builder
	var fenceChar byte
	fenceLen := 0
	flush := func() {
		cur.body = strings.TrimSpace(b.String())
		b.Reset()
		if cur.header != "" || cur.body != "" {
			out = append(out, cur)
		}
	}
	for _, line := range strings.Split(text, "\n") {
		if ch, n, rest, ok := fenceLine(line); ok {
			switch {
			case fenceLen == 0:
				fenceChar, fenceLen = ch, n
			case ch == fenceChar && n >= fenceLen && strings.TrimSpace(rest) == "":
				fenceLen = 0
			}
		}
		if fenceLen == 0 && strings.HasPrefix(line, "## ") {
			flush()
			cur = h2Section{header: strings.TrimSpace(strings.TrimPrefix(line, "## "))}
			continue
		}
		b.WriteString(line)
		b.WriteString("\n")
	}
	flush()
	return out
}

// fenceLine parses a code fence marker line: its character, length and the text
// after the run of marker characters.
func fenceLine(line string) (ch byte, n int, rest string, ok bool) {
	trimmed := strings.TrimLeft(line, " ")
	if len(line)-len(trimmed) > 3 || trimmed == "" || (trimmed[0] != '`' && trimmed[0] != '~') {
		return 0, 0, "", false
	}
	ch = trimmed[0]
	for n < len(trimmed) && trimmed[n] == ch {
		n++
	}
	if n < 3 {
		return 0, 0, "", false
	}
	return ch, n, trimmed[n:], true
}

func normalizeText(s string) string {
	s = strings.TrimPrefix(s, "\ufeff")
	return strings.ReplaceAll(strings.ReplaceAll(s, "\r\n", "\n"), "\r", "\n")
}

func ensureNewline(s string) []byte {
	if !strings.HasSuffix(s, "\n") {
		s += "\n"
	}
	return []byte(s)
}

var itemSuffixes = []string{".instructions.md", ".prompt.md", ".agent.md", ".chatmode.md", ".context.md", ".memory.md", ".mdc", ".md", ".markdown"}

func isMarkdown(name string) bool {
	for _, s := range []string{".md", ".mdc", ".markdown"} {
		if strings.HasSuffix(name, s) {
			return true
		}
	}
	return false
}

// itemName turns a path below a source directory into an item name:
// suffixes stripped, nested directories joined with a hyphen.
func itemName(rel string) (name string, synthesized bool) {
	dir, file := path.Split(rel)
	stem := baseNoExt(file, itemSuffixes...)
	full := strings.Trim(dir, "/")
	if full != "" {
		full += "-"
	}
	return safeName(strings.ReplaceAll(full+stem, "/", "-"))
}

func nameFinding(p *Plan, file string, kind Kind, name string, synthesized bool) {
	if synthesized {
		p.add(newFinding(StatusApproximated, file, "name", string(kind)+"s/"+name,
			"the name has no ASCII letters or digits; a stable name was derived from it"))
	}
}

func (n nativeImporter) importRules(p *Plan, r *reader, dir string, nested map[string]bool, onSkip func(string, string)) {
	cursor := strings.HasPrefix(dir, ".cursor")
	for _, rel := range r.walkFiles(dir, onSkip) {
		file := path.Join(dir, rel)
		if underNested(file, dir, nested) {
			continue
		}
		if !isMarkdown(rel) {
			p.add(newFinding(StatusUnsupported, file, "", "", "not a Markdown rule file"))
			continue
		}
		data, ok := n.readOrReport(p, r, file)
		if !ok {
			continue
		}
		name, synth := itemName(rel)
		nameFinding(p, file, KindRule, name, synth)
		fm, body, has := splitFrontmatter(string(data))
		var meta ruleFM
		if has {
			var found []Finding
			parsed, lenient := parseFrontmatter(fm)
			if lenient {
				p.add(newFinding(StatusApproximated, file, "frontmatter", "",
					"frontmatter is not valid YAML as written; it was read leniently, review the result"))
			}
			meta, found = translateRule(file, parsed, cursor)
			p.Findings = append(p.Findings, found...)
		} else if cursor {
			var found []Finding
			meta, found = translateRule(file, map[string]any{}, true)
			p.Findings = append(p.Findings, found...)
		}
		if strings.TrimSpace(body) == "" {
			p.add(newFinding(StatusDropped, file, "", "", "rule body is empty"))
			continue
		}
		out, err := renderRule(meta, body)
		if err != nil {
			p.add(newFinding(StatusDropped, file, "", "", "frontmatter could not be written: "+err.Error()))
			continue
		}
		p.Items = append(p.Items, Item{Kind: KindRule, Name: name, Sources: []string{file}, Main: out})
	}
}

// underNested reports whether file lies below a source directory nested in dir.
func underNested(file, dir string, nested map[string]bool) bool {
	for np := range nested {
		if np != dir && strings.HasPrefix(np, dir+"/") && strings.HasPrefix(file, np+"/") {
			return true
		}
	}
	return false
}

func (n nativeImporter) importSkills(p *Plan, r *reader, dir string, opt Options, onSkip func(string, string)) {
	for _, e := range r.dirEntries(dir, onSkip) {
		if !e.IsDir() {
			continue
		}
		skillDir := path.Join(dir, e.Name())
		skillFile := path.Join(skillDir, "SKILL.md")
		if _, ok := r.exists(skillFile); !ok {
			continue
		}
		if opt.SkipSkills[e.Name()] {
			p.add(newFinding(StatusDropped, skillDir, "", "", "tracked in skills-lock.json; imported as an installed skill"))
			continue
		}
		data, ok := n.readOrReport(p, r, skillFile)
		if !ok {
			continue
		}
		name, _ := safeName(e.Name())
		if name != e.Name() {
			p.add(newFinding(StatusApproximated, skillDir, "name", "skills/"+name, "skill directory renamed to a valid name"))
		}
		text := reviewAuxFrontmatter(p, skillFile, normalizeText(string(data)))
		text = setFrontmatterName(text, name)
		it := Item{Kind: KindSkill, Name: name, Sources: []string{skillDir}, Main: ensureNewline(text)}
		for _, rel := range r.walkFiles(skillDir, onSkip) {
			if rel == "SKILL.md" {
				continue
			}
			file := path.Join(skillDir, rel)
			res, err := r.read(file)
			if err != nil {
				p.add(newFinding(StatusDropped, file, "", "", skipReasonOr(err)))
				continue
			}
			if r.isGeneratedFile(file, res) {
				p.add(newFinding(StatusDropped, file, "", "", "generated by ai-rulez; not imported as source"))
				continue
			}
			it.Resources = append(it.Resources, File{Path: rel, Data: res, Exec: r.executable(file)})
		}
		p.Items = append(p.Items, it)
	}
}

func skipReasonOr(err error) string {
	if reason := skipReason(err); reason != "" {
		return reason
	}
	return "could not be read: " + err.Error()
}

func (n nativeImporter) importFlat(p *Plan, r *reader, s nativeSource, onSkip func(string, string)) {
	for _, rel := range r.walkFiles(s.Path, onSkip) {
		file := path.Join(s.Path, rel)
		if !isMarkdown(rel) {
			p.add(newFinding(StatusUnsupported, file, "", "", "only Markdown "+string(s.Kind)+" files are imported"))
			continue
		}
		data, ok := n.readOrReport(p, r, file)
		if !ok {
			continue
		}
		name, synth := itemName(rel)
		nameFinding(p, file, s.Kind, name, synth)
		text := reviewAuxFrontmatter(p, file, normalizeText(string(data)))
		p.Items = append(p.Items, Item{Kind: s.Kind, Name: name, Sources: []string{file}, Main: ensureNewline(text)})
	}
}
