package importer

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/fs"
	"path"
	"regexp"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/tailscale/hujson"
	"gopkg.in/yaml.v3"
)

// Tessl: tessl.json lists the plugins a project depends on and how they are
// installed (mode "managed": fetched on demand; "vendored": committed under
// .tessl/plugins/<workspace>/<plugin>/). A plugin holds skills/, rules/, docs/,
// evals/ and .tessl-plugin/plugin.json. The layout is read from the Tessl
// documentation and is not verified against a release (see docs/cli.md); a
// vendored plugin is imported from disk, a managed one that is not on disk is
// reported, and nothing is ever fetched from the registry.

const (
	tesslName       = "tessl"
	tesslManifest   = "tessl.json"
	tesslDir        = ".tessl"
	tesslPluginsDir = ".tessl/plugins"
	tesslPluginMeta = ".tessl-plugin"
	// maxTesslPlugins bounds how many vendored plugins are read.
	maxTesslPlugins = 200
	// evalSchemaVersion is the schema_version of an ai-rulez eval case file.
	evalSchemaVersion = 1
)

type tesslImporter struct{}

func (tesslImporter) Name() string { return tesslName }

func (tesslImporter) Description() string {
	return "Tessl project: tessl.json, vendored .tessl/plugins/ skills and rules, and eval scenarios as *.eval.yaml"
}

func (tesslImporter) Detect(fsys fs.FS) []string {
	r := newReader(fsys)
	var found []string
	for _, f := range []string{tesslManifest, tesslDir, tesslPluginMeta} {
		if _, ok := r.exists(f); ok {
			found = append(found, f)
		}
	}
	sort.Strings(found)
	return found
}

type tesslPlanner struct {
	p      *Plan
	r      *reader
	n      nativeImporter
	opt    Options
	onSkip func(name, reason string)
}

// tesslDep is one dependency of tessl.json.
type tesslDep struct{ name, version string }

func (tesslImporter) Plan(fsys fs.FS, opt Options) (*Plan, error) {
	p := &Plan{}
	r := newReader(fsys)
	r.loadGeneratedManifests()
	b := &tesslPlanner{p: p, r: r, opt: opt}
	b.onSkip = func(name, reason string) { p.add(newFinding(StatusDropped, name, "", "", reason)) }

	deps, err := b.importManifest()
	if err != nil {
		return nil, err
	}
	imported := b.importVendored(deps)
	for _, d := range deps {
		if !imported[d.name] {
			b.p.add(newFinding(StatusNeedsAction, tesslManifest, "dependencies."+d.name, "",
				fmt.Sprintf("plugin %s is not on disk under %s; run `tessl install` (or vendor it) and rerun, or point --source at a populated directory. Nothing is fetched from the registry", d.name, tesslPluginsDir)))
		}
	}
	if _, ok := r.exists(tesslPluginMeta); ok {
		b.importPlugin("", "this project")
	}
	if _, ok := r.exists(path.Join(tesslDir, "RULES.md")); ok {
		p.add(newFinding(StatusDropped, path.Join(tesslDir, "RULES.md"), "", "", "generated by Tessl; not imported as source"))
	}
	r.flushProblems(p)
	return p, nil
}

// importManifest reads tessl.json and returns its dependencies, sorted by name.
func (b *tesslPlanner) importManifest() ([]tesslDep, error) {
	if _, ok := b.r.exists(tesslManifest); !ok {
		return nil, nil
	}
	data, err := b.r.read(tesslManifest)
	if err != nil {
		b.p.add(newFinding(StatusDropped, tesslManifest, "", "", skipReasonOr(err)))
		return nil, nil
	}
	std, err := hujson.Standardize(data)
	var doc map[string]json.RawMessage
	if err == nil {
		err = json.Unmarshal(std, &doc)
	}
	if err != nil {
		return nil, fmt.Errorf("%s is not valid JSON (%s): %w", tesslManifest, CodeInvalid, err)
	}
	keys := make([]string, 0, len(doc))
	for k := range doc {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var deps []tesslDep
	for _, k := range keys {
		switch k {
		case "$schema", "name", "description", "version":
		case "mode":
			var mode string
			if json.Unmarshal(doc[k], &mode) != nil || (mode != "managed" && mode != "vendored") {
				b.p.add(newFinding(StatusUnsupported, tesslManifest, k, "", `mode must be "managed" or "vendored"`))
			}
		case "dependencies":
			deps = b.parseDependencies(doc[k])
		case "verify":
			b.p.add(newFinding(StatusUnsupported, tesslManifest, k, "", "Tessl's verify settings (integrity checks of the registry) have no ai-rulez equivalent; run `ai-rulez lock` after converting"))
		default:
			b.p.add(newFinding(StatusDropped, tesslManifest, k, "", "tessl.json key has no ai-rulez equivalent"))
		}
	}
	return deps, nil
}

func (b *tesslPlanner) parseDependencies(raw json.RawMessage) []tesslDep {
	var table map[string]json.RawMessage
	if err := json.Unmarshal(raw, &table); err != nil {
		b.p.add(newFinding(StatusUnsupported, tesslManifest, "dependencies", "", "dependencies is not an object keyed by plugin name"))
		return nil
	}
	names := make([]string, 0, len(table))
	for n := range table {
		names = append(names, n)
	}
	sort.Strings(names)
	var deps []tesslDep
	for _, n := range names {
		var obj struct {
			Version string `json:"version"`
		}
		var plain string
		switch {
		case json.Unmarshal(table[n], &plain) == nil:
			obj.Version = plain
		case json.Unmarshal(table[n], &obj) != nil:
			b.p.add(newFinding(StatusUnsupported, tesslManifest, "dependencies."+n, "", "dependency is neither a version nor an object"))
			continue
		}
		deps = append(deps, tesslDep{name: n, version: obj.Version})
	}
	return deps
}

// importVendored imports every plugin below .tessl/plugins/<workspace>/<plugin>
// and returns the names ("workspace/plugin") that were found on disk.
func (b *tesslPlanner) importVendored(deps []tesslDep) map[string]bool {
	found := map[string]bool{}
	if _, ok := b.r.exists(tesslPluginsDir); !ok {
		return found
	}
	versions := map[string]string{}
	for _, d := range deps {
		versions[d.name] = d.version
	}
	count := 0
	for _, ws := range b.r.dirEntries(tesslPluginsDir, b.onSkip) {
		if !ws.IsDir() {
			continue
		}
		for _, pl := range b.r.dirEntries(path.Join(tesslPluginsDir, ws.Name()), b.onSkip) {
			if !pl.IsDir() || count >= maxTesslPlugins {
				continue
			}
			name := ws.Name() + "/" + pl.Name()
			root, ok := b.pluginRoot(path.Join(tesslPluginsDir, ws.Name(), pl.Name()), versions[name])
			if !ok {
				b.p.add(newFinding(StatusUnsupported, path.Join(tesslPluginsDir, ws.Name(), pl.Name()), "", "",
					"no skills/, rules/ or evals/ found in this directory or in a version directory below it"))
				continue
			}
			count++
			found[name] = true
			label := name
			if v := versions[name]; v != "" {
				label += "@" + v
			}
			b.importPlugin(root, label)
		}
	}
	return found
}

// pluginRoot finds the directory that holds a plugin's content: the directory
// itself, else its version directory (the one tessl.json names, or the only one).
func (b *tesslPlanner) pluginRoot(dir, version string) (string, bool) {
	if b.isPlugin(dir) {
		return dir, true
	}
	if version != "" {
		if sub := path.Join(dir, version); b.isPlugin(sub) {
			return sub, true
		}
	}
	var candidates []string
	for _, e := range b.r.dirEntries(dir, b.onSkip) {
		if e.IsDir() && b.isPlugin(path.Join(dir, e.Name())) {
			candidates = append(candidates, path.Join(dir, e.Name()))
		}
	}
	if len(candidates) == 1 {
		return candidates[0], true
	}
	return "", false
}

func (b *tesslPlanner) isPlugin(dir string) bool {
	for _, marker := range []string{"skills", "rules", "evals", tesslPluginMeta} {
		if _, ok := b.r.exists(path.Join(dir, marker)); ok {
			return true
		}
	}
	return false
}

// importPlugin imports the content of one plugin rooted at root ("" for the
// project itself).
func (b *tesslPlanner) importPlugin(root, label string) {
	start := len(b.p.Items)
	if root != "" {
		b.p.add(newFinding(StatusApproximated, root, "", "", "vendored copy of "+label+" imported as local files; the registry link is not kept, so it no longer updates"))
	}
	if sub := path.Join(root, "skills"); b.exists(sub) {
		b.n.importSkills(b.p, b.r, sub, b.opt, b.onSkip)
	}
	if sub := path.Join(root, "rules"); b.exists(sub) {
		b.n.importRules(b.p, b.r, sub, map[string]bool{}, b.onSkip)
	}
	b.importMeta(root)
	b.importEvals(root, label, start)
	b.reportOthers(root)
}

func (b *tesslPlanner) exists(p string) bool {
	_, ok := b.r.exists(p)
	return ok
}

// importMeta reports the plugin's own metadata: it describes the dependency, not
// this project, so it is not written into config.toml.
func (b *tesslPlanner) importMeta(root string) {
	file := path.Join(root, tesslPluginMeta, "plugin.json")
	if !b.exists(file) {
		return
	}
	b.p.add(newFinding(StatusDropped, file, "", "",
		"plugin metadata (name, description, version) describes the dependency, not this project; it is recorded in the provenance finding and not written to config.toml"))
}

// tesslHandled are the entries of a plugin directory importPlugin reads.
var tesslHandled = map[string]bool{"skills": true, "rules": true, "evals": true, tesslPluginMeta: true}

// reportOthers reports the entries of a vendored plugin that are not read.
// Documentation and the usual package files are named for what they are. The
// project root, when it is itself a plugin, is only checked for docs/: its other
// entries are the project's own.
func (b *tesslPlanner) reportOthers(root string) {
	dir := root
	if dir == "" {
		dir = "."
	}
	for _, e := range b.r.dirEntries(dir, b.onSkip) {
		name := e.Name()
		lower := strings.ToLower(name)
		switch {
		case tesslHandled[name], strings.HasPrefix(name, "."):
		case name == "docs":
			b.p.add(newFinding(StatusDropped, path.Join(root, name), "", "",
				"documentation is reference material Tessl serves to the agent; copy what it needs into context/ by hand"))
		case root == "":
		case strings.HasPrefix(lower, "readme"), strings.HasPrefix(lower, "license"), strings.HasPrefix(lower, "changelog"):
		default:
			b.p.add(newFinding(StatusDropped, path.Join(root, name), "", "", "not a Tessl plugin entry the importer reads; ignored"))
		}
	}
}

// importEvals converts the scenarios of <root>/evals into *.eval.yaml files of a
// skill. Tessl evals belong to a plugin, not to one skill, so they go to the
// plugin's only skill, else the skill named like the plugin, else the first.
func (b *tesslPlanner) importEvals(root, label string, start int) {
	dir := path.Join(root, "evals")
	if !b.exists(dir) {
		return
	}
	var skills []int
	for i := start; i < len(b.p.Items); i++ {
		if b.p.Items[i].Kind == KindSkill {
			skills = append(skills, i)
		}
	}
	scenarios := b.r.dirEntries(dir, b.onSkip)
	if len(skills) == 0 {
		b.p.add(newFinding(StatusNeedsAction, dir, "", "", "the plugin has no skill to attach its eval scenarios to; ai-rulez evals belong to a skill"))
		return
	}
	target := b.evalTarget(skills, label, dir)
	for _, e := range scenarios {
		if !e.IsDir() {
			b.p.add(newFinding(StatusDropped, path.Join(dir, e.Name()), "", "", "expected a scenario directory with task.md and criteria.json"))
			continue
		}
		b.importScenario(path.Join(dir, e.Name()), e.Name(), label, &b.p.Items[target])
	}
}

// evalTarget picks the skill that receives a plugin's eval cases.
func (b *tesslPlanner) evalTarget(skills []int, label, dir string) int {
	if len(skills) == 1 {
		return skills[0]
	}
	plugin, _, _ := strings.Cut(path.Base(label), "@")
	sort.Slice(skills, func(i, j int) bool { return b.p.Items[skills[i]].Name < b.p.Items[skills[j]].Name })
	for _, i := range skills {
		if b.p.Items[i].Name == plugin {
			return i
		}
	}
	b.p.add(newFinding(StatusApproximated, dir, "", "skills/"+b.p.Items[skills[0]].Name+"/evals",
		"the plugin has several skills and none is named after it; its eval scenarios were attached to the first, "+b.p.Items[skills[0]].Name+"; move them if another skill owns them"))
	return skills[0]
}

// tesslCriteria is criteria.json of a scenario: a context sentence and a
// checklist whose items carry a name, a description and a weight.
type tesslCriteria struct {
	Context   string            `json:"context"`
	Type      string            `json:"type"`
	Checklist []json.RawMessage `json:"checklist"`
}

func (b *tesslPlanner) importScenario(dir, name, label string, skill *Item) {
	task, ok := b.readText(path.Join(dir, "task.md"))
	if !ok {
		b.p.add(newFinding(StatusDropped, dir, "", "", "scenario has no readable task.md; skipped"))
		return
	}
	id, synth := safeName(name)
	if synth {
		b.p.add(newFinding(StatusApproximated, dir, "name", "evals/"+id, "the scenario name has no ASCII letters or digits; a stable id was derived from it"))
	}
	var rubric string
	crit := path.Join(dir, "criteria.json")
	if b.exists(crit) {
		rubric = b.rubric(crit)
	} else {
		b.p.add(newFinding(StatusApproximated, dir, "criteria.json", "", "no criteria.json: the case checks only that the skill fires (trigger-only)"))
	}
	data, err := renderEvalFile(evalCase{id: id, description: "Imported from the Tessl scenario " + name + " of " + label, prompt: strings.TrimSpace(task), rubric: rubric})
	if err != nil {
		b.p.add(newFinding(StatusDropped, dir, "", "", "eval case could not be written: "+err.Error()))
		return
	}
	target := "evals/" + id + ".eval.yaml"
	for _, res := range skill.Resources {
		if res.Path == target {
			b.p.add(newFinding(StatusDropped, dir, "", "", "another scenario already produced "+target))
			return
		}
	}
	skill.Resources = append(skill.Resources, File{Path: target, Data: data})
	b.p.add(newFinding(StatusMapped, dir, "scenario", "skills/"+skill.Name+"/"+target, ""))
}

func (b *tesslPlanner) readText(file string) (string, bool) {
	data, err := b.r.read(file)
	if err != nil {
		return "", false
	}
	if !utf8.Valid(data) {
		return "", false
	}
	return normalizeText(string(data)), true
}

// rubric turns criteria.json into the rubric of an ai-rulez eval case: the
// context sentence and one line per checklist item. The weights are dropped.
func (b *tesslPlanner) rubric(file string) string {
	data, err := b.r.read(file)
	if err != nil {
		b.p.add(newFinding(StatusDropped, file, "", "", skipReasonOr(err)))
		return ""
	}
	var c tesslCriteria
	if err := json.Unmarshal(data, &c); err != nil {
		// A bare list of items is also accepted.
		if lerr := json.Unmarshal(data, &c.Checklist); lerr != nil {
			b.p.add(newFinding(StatusUnsupported, file, "", "", "not a criteria object or a checklist: "+err.Error()))
			return ""
		}
	}
	if c.Type != "" && c.Type != "weighted_checklist" {
		b.p.add(newFinding(StatusApproximated, file, "type", "", fmt.Sprintf("criteria type %q is not a weighted checklist; its items were read as a plain checklist", c.Type)))
	}
	var lines []string
	weighted := false
	for _, raw := range c.Checklist {
		line, hasWeight := checklistLine(raw)
		if line == "" {
			continue
		}
		weighted = weighted || hasWeight
		lines = append(lines, "- "+line)
	}
	if weighted {
		b.p.add(newFinding(StatusApproximated, file, "checklist", "rubric", "the weighted checklist became a rubric; the weights are dropped"))
	}
	var out []string
	if ctx := strings.TrimSpace(c.Context); ctx != "" {
		out = append(out, ctx)
	}
	if len(lines) > 0 {
		out = append(out, "The answer should satisfy these criteria:")
		out = append(out, lines...)
	}
	return strings.Join(out, "\n")
}

// checklistLine renders one checklist item and reports whether it had a weight.
func checklistLine(raw json.RawMessage) (line string, weighted bool) {
	var text string
	if json.Unmarshal(raw, &text) == nil {
		return strings.TrimSpace(text), false
	}
	var item struct {
		Name        string   `json:"name"`
		Description string   `json:"description"`
		MaxScore    *float64 `json:"max_score"`
		Weight      *float64 `json:"weight"`
	}
	if json.Unmarshal(raw, &item) != nil {
		return "", false
	}
	weighted = item.MaxScore != nil || item.Weight != nil
	switch {
	case item.Name != "" && item.Description != "":
		return item.Name + ": " + strings.TrimSpace(item.Description), weighted
	case item.Description != "":
		return strings.TrimSpace(item.Description), weighted
	}
	return item.Name, weighted
}

// evalCase is one case of an ai-rulez eval file.
type evalCase struct {
	id, description, prompt, rubric string
}

var evalIDChars = regexp.MustCompile(`[^a-z0-9._-]+`)

// renderEvalFile writes a *.eval.yaml with one case, fields in a fixed order.
func renderEvalFile(c evalCase) ([]byte, error) {
	id := evalIDChars.ReplaceAllString(strings.ToLower(c.id), "-")
	if id == "" {
		return nil, fmt.Errorf("empty case id")
	}
	if c.prompt == "" {
		return nil, fmt.Errorf("the scenario has an empty task")
	}
	cs := yamlMap()
	yamlAdd(cs, "id", yamlStr(id))
	yamlAdd(cs, "description", yamlStr(c.description))
	yamlAdd(cs, "prompt", yamlStr(c.prompt))
	yamlAdd(cs, "expect_trigger", &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: "true"})
	if c.rubric != "" {
		yamlAdd(cs, "rubric", yamlStr(c.rubric))
	}
	tags := &yaml.Node{Kind: yaml.SequenceNode, Style: yaml.FlowStyle, Content: []*yaml.Node{yamlStr("tessl")}}
	yamlAdd(cs, "tags", tags)
	root := yamlMap()
	yamlAdd(root, "schema_version", &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!int", Value: fmt.Sprint(evalSchemaVersion)})
	yamlAdd(root, "cases", &yaml.Node{Kind: yaml.SequenceNode, Content: []*yaml.Node{cs}})
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(root); err != nil {
		return nil, fmt.Errorf("render eval case: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("render eval case: %w", err)
	}
	return buf.Bytes(), nil
}

func yamlMap() *yaml.Node { return &yaml.Node{Kind: yaml.MappingNode} }

func yamlAdd(m *yaml.Node, key string, val *yaml.Node) {
	m.Content = append(m.Content, &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: key}, val)
}

// yamlStr is a string node; multi-line text is written as a literal block.
func yamlStr(s string) *yaml.Node {
	n := &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: s}
	if strings.Contains(s, "\n") && !strings.ContainsAny(s, "\r\t") && !strings.HasPrefix(s, " ") && !strings.HasSuffix(s, " ") && !strings.Contains(s, " \n") {
		n.Style = yaml.LiteralStyle
	}
	return n
}
