package importer

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/fs"
	"path"
	"regexp"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/samber/oops"
	"github.com/tailscale/hujson"
	"gopkg.in/yaml.v3"
)

// Tessl: tessl.json lists the tiles a project depends on and how they are
// installed (mode "managed": fetched on demand; "vendored": committed on disk).
// A consumer project keeps a vendored tile under .tessl/tiles/<workspace>/<name>/
// with a tile.json (rules under a `steering` map, skills under a `skills` map and
// optional docs), and the newer plugin source layout keeps a plugin under
// .tessl/plugins/<workspace>/<plugin>/ with rules/, skills/, evals/ and a
// .tessl-plugin/plugin.json. Both are imported from disk; a managed dependency
// that is not on disk is reported and nothing is ever fetched from the registry.
// The layout is read from the Tessl documentation and from real projects (see
// tests/fixtures/tessl); a tile the importer cannot map is reported, not guessed.

const (
	tesslName       = "tessl"
	tesslManifest   = "tessl.json"
	tesslDir        = ".tessl"
	tesslPluginsDir = ".tessl/plugins"
	tesslTilesDir   = ".tessl/tiles"
	tesslPluginMeta = ".tessl-plugin"
	tesslTileMeta   = "tile.json"
	tesslEvalsDir   = "evals"
	// maxTesslPlugins bounds how many vendored tiles or plugins are read.
	maxTesslPlugins = 200
	// evalSchemaVersion is the schema_version of an ai-rulez eval case file.
	evalSchemaVersion = 1
)

type tesslImporter struct{}

func (tesslImporter) Name() string { return tesslName }

func (tesslImporter) Description() string {
	return "Tessl project: tessl.json, vendored .tessl/tiles and .tessl/plugins skills and rules, and eval scenarios as *.eval.yaml"
}

func (tesslImporter) Detect(fsys fs.FS) []string {
	r := newReader(fsys)
	var found []string
	for _, f := range []string{tesslManifest, tesslDir, tesslPluginMeta} {
		if _, ok := r.exists(f); ok {
			found = append(found, f)
		}
	}
	sort.Strings(found)
	return found
}

type tesslPlanner struct {
	p      *Plan
	r      *reader
	n      nativeImporter
	opt    Options
	onSkip func(name, reason string)
}

// tesslDep is one dependency of tessl.json.
type tesslDep struct{ name, version string }

func (tesslImporter) Plan(fsys fs.FS, opt Options) (*Plan, error) {
	p := &Plan{}
	r := newReader(fsys)
	r.loadGeneratedManifests()
	b := &tesslPlanner{p: p, r: r, opt: opt}
	b.onSkip = func(name, reason string) { p.add(newFinding(StatusDropped, name, "", "", reason)) }

	deps, err := b.importManifest()
	if err != nil {
		return nil, err
	}
	imported := b.importVendored(deps)
	for _, d := range deps {
		if !imported[d.name] {
			b.p.add(newFinding(StatusNeedsAction, tesslManifest, "dependencies."+d.name, "",
				fmt.Sprintf("tile %s is not on disk under %s or %s; run `tessl install` (or vendor it) and rerun, or point --source at a populated directory. Nothing is fetched from the registry", d.name, tesslTilesDir, tesslPluginsDir)))
		}
	}
	if _, ok := r.exists(tesslPluginMeta); ok {
		b.importPlugin("", "this project")
	}
	if _, ok := r.exists(path.Join(tesslDir, "RULES.md")); ok {
		p.add(newFinding(StatusDropped, path.Join(tesslDir, "RULES.md"), "", "", "generated by Tessl; not imported as source"))
	}
	r.flushProblems(p)
	return p, nil
}

// importManifest reads tessl.json and returns its dependencies, sorted by name.
func (b *tesslPlanner) importManifest() ([]tesslDep, error) {
	if _, ok := b.r.exists(tesslManifest); !ok {
		return nil, nil
	}
	data, err := b.r.read(tesslManifest)
	if err != nil {
		b.p.add(newFinding(StatusDropped, tesslManifest, "", "", skipReasonOr(err)))
		return nil, nil
	}
	std, err := hujson.Standardize(trimBOM(data))
	var doc map[string]json.RawMessage
	if err == nil {
		err = json.Unmarshal(std, &doc)
	}
	if err != nil {
		return nil, oops.With("file", tesslManifest).Wrapf(err, "%s is not valid JSON (%s)", tesslManifest, CodeInvalid)
	}
	keys := make([]string, 0, len(doc))
	for k := range doc {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var deps []tesslDep
	for _, k := range keys {
		switch k {
		case litSchema, litName, litDescription, litVersion:
		case "mode":
			var mode string
			if json.Unmarshal(doc[k], &mode) != nil || (mode != "managed" && mode != "vendored") {
				b.p.add(newFinding(StatusUnsupported, tesslManifest, k, "", `mode must be "managed" or "vendored"`))
			}
		case "dependencies":
			deps = b.parseDependencies(doc[k])
		case "verify":
			b.p.add(newFinding(StatusUnsupported, tesslManifest, k, "", "Tessl's verify settings (integrity checks of the registry) have no ai-rulez equivalent; run `ai-rulez lock` after converting"))
		default:
			b.p.add(newFinding(StatusDropped, tesslManifest, k, "", "tessl.json key has no ai-rulez equivalent"))
		}
	}
	return deps, nil
}

func (b *tesslPlanner) parseDependencies(raw json.RawMessage) []tesslDep {
	var table map[string]json.RawMessage
	if err := json.Unmarshal(raw, &table); err != nil {
		b.p.add(newFinding(StatusUnsupported, tesslManifest, "dependencies", "", "dependencies is not an object keyed by plugin name"))
		return nil
	}
	names := make([]string, 0, len(table))
	for n := range table {
		names = append(names, n)
	}
	sort.Strings(names)
	var deps []tesslDep
	for _, n := range names {
		var obj struct {
			Version string `json:"version"`
		}
		var plain string
		switch {
		case json.Unmarshal(table[n], &plain) == nil:
			obj.Version = plain
		case json.Unmarshal(table[n], &obj) != nil:
			b.p.add(newFinding(StatusUnsupported, tesslManifest, "dependencies."+n, "", "dependency is neither a version nor an object"))
			continue
		}
		deps = append(deps, tesslDep{name: n, version: obj.Version})
	}
	return deps
}

// importVendored imports every tile below .tessl/tiles/<workspace>/<name> and
// every plugin below .tessl/plugins/<workspace>/<plugin>, and returns the names
// ("workspace/name") that were found on disk.
func (b *tesslPlanner) importVendored(deps []tesslDep) map[string]bool {
	found := map[string]bool{}
	versions := map[string]string{}
	for _, d := range deps {
		versions[d.name] = d.version
	}
	count := 0
	for _, base := range []string{tesslTilesDir, tesslPluginsDir} {
		if _, ok := b.r.exists(base); !ok {
			continue
		}
		for _, ws := range b.r.dirEntries(base, b.onSkip) {
			if !ws.IsDir() {
				continue
			}
			for _, pl := range b.r.dirEntries(path.Join(base, ws.Name()), b.onSkip) {
				if !pl.IsDir() || count >= maxTesslPlugins {
					continue
				}
				dir := path.Join(base, ws.Name(), pl.Name())
				name := ws.Name() + "/" + pl.Name()
				root, ok := b.pluginRoot(dir, versions[name])
				if !ok {
					b.p.add(newFinding(StatusUnsupported, dir, "", "",
						"no tile.json, skills/, rules/ or evals/ found in this directory or in a version directory below it"))
					continue
				}
				count++
				found[name] = true
				label := name
				if v := versions[name]; v != "" {
					label += "@" + v
				}
				b.importPlugin(root, label)
			}
		}
	}
	return found
}

// pluginRoot finds the directory that holds a tile's or plugin's content: the
// directory itself, else its version directory (the one tessl.json names, or the
// only one).
func (b *tesslPlanner) pluginRoot(dir, version string) (string, bool) {
	if b.isPlugin(dir) {
		return dir, true
	}
	if version != "" && checkSubpath(version) == "" {
		if sub := path.Join(dir, version); b.isPlugin(sub) {
			return sub, true
		}
	}
	var candidates []string
	for _, e := range b.r.dirEntries(dir, b.onSkip) {
		if e.IsDir() && b.isPlugin(path.Join(dir, e.Name())) {
			candidates = append(candidates, path.Join(dir, e.Name()))
		}
	}
	if len(candidates) == 1 {
		return candidates[0], true
	}
	return "", false
}

func (b *tesslPlanner) isPlugin(dir string) bool {
	for _, marker := range []string{skillsDir, rulesDir, tesslEvalsDir, tesslPluginMeta, tesslTileMeta} {
		if _, ok := b.r.exists(path.Join(dir, marker)); ok {
			return true
		}
	}
	return false
}

// importPlugin imports the content of one tile or plugin rooted at root ("" for
// the project itself): the plugin-era skills/ and rules/ directories, the tile-era
// tile.json steering and skills, evals and the metadata.
func (b *tesslPlanner) importPlugin(root, label string) {
	start := len(b.p.Items)
	if root != "" {
		b.p.add(newFinding(StatusApproximated, root, "", "", "vendored copy of "+label+" imported as local files; the registry link is not kept, so it no longer updates"))
	}
	if sub := path.Join(root, skillsDir); b.exists(sub) {
		b.n.importSkills(b.p, b.r, sub, b.opt, b.onSkip)
	}
	if sub := path.Join(root, rulesDir); b.exists(sub) {
		b.n.importRules(b.p, b.r, sub, map[string]bool{}, b.onSkip)
	}
	var rootSkill bool
	if root != "" { // a tile is always a subdirectory; the project root is not one
		rootSkill = b.importTile(root)
	}
	b.importMeta(root)
	b.importEvals(root, label, start)
	b.reportOthers(root, rootSkill)
}

// tesslTile is the subset of a tile's tile.json the importer reads. Rules live
// under `steering` (name to a rule file) and skills under `skills` (name to a
// SKILL.md path); docs and the rest of the metadata are not imported.
type tesslTile struct {
	Steering map[string]struct {
		Rules string `json:"rules"`
	} `json:"steering"`
	Skills map[string]struct {
		Path string `json:"path"`
	} `json:"skills"`
}

// importTile imports the rules and skills a vendored tile names in its tile.json.
// It reports whether a skill sits at the tile root: every other entry of such a
// tile is one of that skill's resources, not a separate one. A tile need not keep
// a rules/ or skills/ directory, so its manifests decide what to read.
func (b *tesslPlanner) importTile(root string) (rootSkill bool) {
	file := path.Join(root, tesslTileMeta)
	if !b.exists(file) {
		return false
	}
	data, err := b.r.read(file)
	if err != nil {
		b.p.add(newFinding(StatusDropped, file, "", "", skipReasonOr(err)))
		return false
	}
	var tile tesslTile
	if err := json.Unmarshal(trimBOM(data), &tile); err != nil {
		b.p.add(newFinding(StatusUnsupported, file, "", "", "tile.json is not valid JSON: "+err.Error()))
		return false
	}
	b.p.add(newFinding(StatusDropped, file, "", "",
		"tile metadata (name, version, summary) describes the dependency, not this project; it is not written to config.toml"))
	for _, name := range sortedKeys(tile.Steering) {
		b.importTileRule(root, name, tile.Steering[name].Rules)
	}
	for _, name := range sortedKeys(tile.Skills) {
		skillPath := tile.Skills[name].Path
		b.importTileSkill(root, name, skillPath)
		if checkSubpath(skillPath) == "" && path.Dir(path.Join(root, skillPath)) == root {
			rootSkill = true
		}
	}
	return rootSkill
}

// importTileRule imports one steering rule of a tile under its steering name.
func (b *tesslPlanner) importTileRule(root, name, rules string) {
	meta := path.Join(root, tesslTileMeta)
	if rules == "" || checkSubpath(rules) != "" {
		b.p.add(newFinding(StatusUnsupported, meta, "steering."+name, "", "the steering entry has no rule file inside the tile"))
		return
	}
	file := path.Join(root, rules)
	if !isMarkdown(file) {
		b.p.add(newFinding(StatusUnsupported, file, "", "", "not a Markdown rule file"))
		return
	}
	if !b.exists(file) {
		b.p.add(newFinding(StatusNeedsAction, file, "", "", "the rule tile.json names is not on disk"))
		return
	}
	ruleName, synth := safeName(name)
	b.n.importRuleFile(b.p, b.r, file, ruleName, synth, false)
}

// importTileSkill imports one skill of a tile, named by its `skills` key.
func (b *tesslPlanner) importTileSkill(root, name, skillPath string) {
	meta := path.Join(root, tesslTileMeta)
	if skillPath == "" || checkSubpath(skillPath) != "" || !strings.HasSuffix(skillPath, litSkillMD) {
		b.p.add(newFinding(StatusUnsupported, meta, "skills."+name, "", "the skill entry needs a path to a SKILL.md inside the tile"))
		return
	}
	file := path.Join(root, skillPath)
	if !b.exists(file) {
		b.p.add(newFinding(StatusNeedsAction, file, "", "", "the skill tile.json names is not on disk"))
		return
	}
	b.n.importSkillDir(b.p, b.r, path.Dir(file), name, b.opt, b.onSkip, tesslTileRootSkip())
}

// tesslTileRootSkip lists the top-level entries of a tile that are not resources
// of a SKILL.md kept at the tile root: the tile's own manifest and directories.
// It is a function, not a package-level map, so it adds no mutable global.
func tesslTileRootSkip() map[string]bool {
	return map[string]bool{
		skillsDir: true, rulesDir: true, tesslEvalsDir: true, "docs": true,
		tesslPluginMeta: true, tesslTileMeta: true, "steering": true,
	}
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func (b *tesslPlanner) exists(p string) bool {
	_, ok := b.r.exists(p)
	return ok
}

// importMeta reports the plugin's own metadata: it describes the dependency, not
// this project, so it is not written into config.toml.
func (b *tesslPlanner) importMeta(root string) {
	file := path.Join(root, tesslPluginMeta, "plugin.json")
	if !b.exists(file) {
		return
	}
	b.p.add(newFinding(StatusDropped, file, "", "",
		"plugin metadata (name, description, version) describes the dependency, not this project; it is recorded in the provenance finding and not written to config.toml"))
}

// tesslHandled are the entries of a tile or plugin directory importPlugin reads.
var tesslHandled = map[string]bool{
	skillsDir: true, rulesDir: true, tesslEvalsDir: true, tesslPluginMeta: true,
	"steering": true, tesslTileMeta: true,
}

// reportOthers reports the entries of a vendored plugin that are not read.
// Documentation and the usual package files are named for what they are. The
// project root, when it is itself a plugin, is only checked for docs/: its other
// entries are the project's own. When a skill sits at the tile root (rootSkill),
// every remaining entry is one of its resources and is not reported.
func (b *tesslPlanner) reportOthers(root string, rootSkill bool) {
	dir := root
	if dir == "" {
		dir = "."
	}
	for _, e := range b.r.dirEntries(dir, b.onSkip) {
		name := e.Name()
		lower := strings.ToLower(name)
		switch {
		case tesslHandled[name], strings.HasPrefix(name, "."):
		case name == "docs":
			b.p.add(newFinding(StatusDropped, path.Join(root, name), "", "",
				"documentation is reference material Tessl serves to the agent; copy what it needs into context/ by hand"))
		case root == "", rootSkill:
		case strings.HasPrefix(lower, "readme"), strings.HasPrefix(lower, litLicense), strings.HasPrefix(lower, "changelog"):
		default:
			b.p.add(newFinding(StatusDropped, path.Join(root, name), "", "", "not a Tessl plugin entry the importer reads; ignored"))
		}
	}
}

// importEvals converts the scenarios of <root>/evals into *.eval.yaml files of a
// skill. Tessl evals belong to a plugin, not to one skill, so they go to the
// plugin's only skill, else the skill named like the plugin, else the first.
func (b *tesslPlanner) importEvals(root, label string, start int) {
	dir := path.Join(root, tesslEvalsDir)
	if !b.exists(dir) {
		return
	}
	var skills []int
	for i := start; i < len(b.p.Items); i++ {
		if b.p.Items[i].Kind == KindSkill {
			skills = append(skills, i)
		}
	}
	scenarios := b.r.dirEntries(dir, b.onSkip)
	if len(skills) == 0 {
		b.p.add(newFinding(StatusNeedsAction, dir, "", "", "the plugin has no skill to attach its eval scenarios to; ai-rulez evals belong to a skill"))
		return
	}
	target := b.evalTarget(skills, label, dir)
	for _, e := range scenarios {
		if !e.IsDir() {
			b.p.add(newFinding(StatusDropped, path.Join(dir, e.Name()), "", "", "expected a scenario directory with task.md and criteria.json"))
			continue
		}
		b.importScenario(path.Join(dir, e.Name()), e.Name(), label, &b.p.Items[target])
	}
}

// evalTarget picks the skill that receives a plugin's eval cases.
func (b *tesslPlanner) evalTarget(skills []int, label, dir string) int {
	if len(skills) == 1 {
		return skills[0]
	}
	plugin, _, _ := strings.Cut(path.Base(label), "@")
	sort.Slice(skills, func(i, j int) bool { return b.p.Items[skills[i]].Name < b.p.Items[skills[j]].Name })
	for _, i := range skills {
		if b.p.Items[i].Name == plugin {
			return i
		}
	}
	b.p.add(newFinding(StatusApproximated, dir, "", "skills/"+b.p.Items[skills[0]].Name+"/evals",
		"the plugin has several skills and none is named after it; its eval scenarios were attached to the first, "+b.p.Items[skills[0]].Name+"; move them if another skill owns them"))
	return skills[0]
}

// tesslCriteria is criteria.json of a scenario: a context sentence and a
// checklist whose items carry a name, a description and a weight.
type tesslCriteria struct {
	Context   string            `json:"context"`
	Type      string            `json:"type"`
	Checklist []json.RawMessage `json:"checklist"`
}

func (b *tesslPlanner) importScenario(dir, name, label string, skill *Item) {
	task, ok := b.readText(path.Join(dir, "task.md"))
	if !ok {
		b.p.add(newFinding(StatusDropped, dir, "", "", "scenario has no readable task.md; skipped"))
		return
	}
	id, synth := safeName(name)
	if synth {
		b.p.add(newFinding(StatusApproximated, dir, litName, "evals/"+id, "the scenario name has no ASCII letters or digits; a stable id was derived from it"))
	}
	var rubric string
	crit := path.Join(dir, "criteria.json")
	if b.exists(crit) {
		rubric = b.rubric(crit)
	} else {
		b.p.add(newFinding(StatusApproximated, dir, "criteria.json", "", "no criteria.json: the case checks only that the skill fires (trigger-only)"))
	}
	data, err := renderEvalFile(evalCase{id: id, description: "Imported from the Tessl scenario " + name + " of " + label, prompt: strings.TrimSpace(task), rubric: rubric})
	if err != nil {
		b.p.add(newFinding(StatusDropped, dir, "", "", "eval case could not be written: "+err.Error()))
		return
	}
	target := "evals/" + id + ".eval.yaml"
	for _, res := range skill.Resources {
		if res.Path == target {
			b.p.add(newFinding(StatusDropped, dir, "", "", "another scenario already produced "+target))
			return
		}
	}
	skill.Resources = append(skill.Resources, File{Path: target, Data: data})
	b.p.add(newFinding(StatusMapped, dir, "scenario", "skills/"+skill.Name+"/"+target, ""))
}

func (b *tesslPlanner) readText(file string) (string, bool) {
	data, err := b.r.read(file)
	if err != nil {
		return "", false
	}
	if !utf8.Valid(data) {
		return "", false
	}
	return normalizeText(string(data)), true
}

// rubric turns criteria.json into the rubric of an ai-rulez eval case: the
// context sentence and one line per checklist item. The weights are dropped.
func (b *tesslPlanner) rubric(file string) string {
	data, err := b.r.read(file)
	if err != nil {
		b.p.add(newFinding(StatusDropped, file, "", "", skipReasonOr(err)))
		return ""
	}
	var c tesslCriteria
	if err := json.Unmarshal(trimBOM(data), &c); err != nil {
		// A bare list of items is also accepted.
		if lerr := json.Unmarshal(trimBOM(data), &c.Checklist); lerr != nil {
			b.p.add(newFinding(StatusUnsupported, file, "", "", "not a criteria object or a checklist: "+err.Error()))
			return ""
		}
	}
	if c.Type != "" && c.Type != "weighted_checklist" {
		b.p.add(newFinding(StatusApproximated, file, "type", "", fmt.Sprintf("criteria type %q is not a weighted checklist; its items were read as a plain checklist", c.Type)))
	}
	var lines []string
	weighted := false
	for _, raw := range c.Checklist {
		line, hasWeight := checklistLine(raw)
		if line == "" {
			continue
		}
		weighted = weighted || hasWeight
		lines = append(lines, "- "+line)
	}
	if weighted {
		b.p.add(newFinding(StatusApproximated, file, "checklist", "rubric", "the weighted checklist became a rubric; the weights are dropped"))
	}
	var out []string
	if ctx := strings.TrimSpace(c.Context); ctx != "" {
		out = append(out, ctx)
	}
	if len(lines) > 0 {
		out = append(out, "The answer should satisfy these criteria:")
		out = append(out, lines...)
	}
	return strings.Join(out, "\n")
}

// checklistLine renders one checklist item and reports whether it had a weight.
func checklistLine(raw json.RawMessage) (line string, weighted bool) {
	var text string
	if json.Unmarshal(raw, &text) == nil {
		return strings.TrimSpace(text), false
	}
	var item struct {
		Name        string   `json:"name"`
		Description string   `json:"description"`
		MaxScore    *float64 `json:"max_score"`
		Weight      *float64 `json:"weight"`
	}
	if json.Unmarshal(raw, &item) != nil {
		return "", false
	}
	weighted = item.MaxScore != nil || item.Weight != nil
	switch {
	case item.Name != "" && item.Description != "":
		return item.Name + ": " + strings.TrimSpace(item.Description), weighted
	case item.Description != "":
		return strings.TrimSpace(item.Description), weighted
	}
	return item.Name, weighted
}

// evalCase is one case of an ai-rulez eval file.
type evalCase struct {
	id, description, prompt, rubric string
}

var evalIDChars = regexp.MustCompile(`[^a-z0-9._-]+`)

// renderEvalFile writes a *.eval.yaml with one case, fields in a fixed order.
func renderEvalFile(c evalCase) ([]byte, error) {
	id := evalIDChars.ReplaceAllString(strings.ToLower(c.id), "-")
	if id == "" {
		return nil, oops.Errorf("empty case id")
	}
	if c.prompt == "" {
		return nil, oops.Errorf("the scenario has an empty task")
	}
	cs := yamlMap()
	yamlAdd(cs, "id", yamlStr(id))
	yamlAdd(cs, litDescription, yamlStr(c.description))
	yamlAdd(cs, "prompt", yamlStr(c.prompt))
	yamlAdd(cs, "expect_trigger", &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: "true"})
	if c.rubric != "" {
		yamlAdd(cs, "rubric", yamlStr(c.rubric))
	}
	tags := &yaml.Node{Kind: yaml.SequenceNode, Style: yaml.FlowStyle, Content: []*yaml.Node{yamlStr("tessl")}}
	yamlAdd(cs, "tags", tags)
	root := yamlMap()
	yamlAdd(root, "schema_version", &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!int", Value: fmt.Sprint(evalSchemaVersion)})
	yamlAdd(root, "cases", &yaml.Node{Kind: yaml.SequenceNode, Content: []*yaml.Node{cs}})
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(root); err != nil {
		return nil, oops.Wrapf(err, "render eval case")
	}
	if err := enc.Close(); err != nil {
		return nil, oops.Wrapf(err, "render eval case")
	}
	return buf.Bytes(), nil
}

func yamlMap() *yaml.Node { return &yaml.Node{Kind: yaml.MappingNode} }

func yamlAdd(m *yaml.Node, key string, val *yaml.Node) {
	m.Content = append(m.Content, &yaml.Node{Kind: yaml.ScalarNode, Tag: litYAMLStr, Value: key}, val)
}

// yamlStr is a string node; multi-line text is written as a literal block.
func yamlStr(s string) *yaml.Node {
	n := &yaml.Node{Kind: yaml.ScalarNode, Tag: litYAMLStr, Value: s}
	if strings.Contains(s, "\n") && !strings.ContainsAny(s, "\r\t") && !strings.HasPrefix(s, " ") && !strings.HasSuffix(s, " ") && !strings.Contains(s, " \n") {
		n.Style = yaml.LiteralStyle
	}
	return n
}
