package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/Goldziher/ai-rulez/internal/config"
	"github.com/Goldziher/ai-rulez/internal/templates"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Every layout ai-rulez wrote into a rules folder in v4.20.0 through v4.22.0.
// Header comments of .md and .mdc files were always HTML comments (the
// templates only use line comments for other extensions), so a rule file never
// carried a "# GENERATED FILE" line header.
func TestHasGeneratedBanner_ReleasedLayouts(t *testing.T) {
	t.Parallel()

	detailed := "<!--\n🤖 AI-RULEZ :: GENERATED FILE — DO NOT EDIT DIRECTLY\nProject: demo\nSource: .ai-rulez/config.toml\n-->\n\n"
	compact := "<!--\n🤖 AI-RULEZ :: GENERATED FILE — DO NOT EDIT | Generated: 2026-10-01\n-->\n\n"
	tests := []struct {
		name, path, content string
		want                bool
	}{
		{"4.20/4.21 cline: header then title", ".clinerules/x.md", detailed + "# X\n\nBody.\n", true},
		{"4.20/4.21 compact header", ".clinerules/x.md", compact + "# X\n", true},
		{"4.20/4.21 devin: trigger frontmatter, then header", ".devin/rules/x.md",
			"---\ntrigger: always_on\n---\n\n" + detailed + "# X\n", true},
		{"4.20/4.21 hashes full: hashes inside the header", ".clinerules/x.md",
			strings.Replace(detailed, "\n-->", "\nContent-Hash: blake3:a\nSource-Hash: blake3:b\n-->", 1) + "# X\n", true},
		{"4.20/4.21 cursor with hashes in the frontmatter", ".cursor/rules/x.mdc",
			"---\nalwaysApply: true\n# Content-Hash: blake3:a\n---\n\n# X\n", false}, // recognized by the stored hash, not the banner
		{"4.20/4.21 cursor bare", ".cursor/rules/x.mdc", "---\nalwaysApply: true\n---\n\n# X\n", false},
		{"4.22 rule banner after frontmatter", ".cursor/rules/x.mdc",
			"---\nalwaysApply: true\n---\n<!--\nGenerated by ai-rulez from .ai-rulez/rules/x.md. Edit the source, not this file.\n-->\n\n# X\n", true},
		{"4.22 rule banner without frontmatter", ".github/instructions/x.instructions.md",
			"<!--\nGenerated by ai-rulez. Edit the source, not this file.\n-->\n\n# X\n", true},
		{"line comment header of a non-markdown file", ".claude/rules/x.txt", "# 🤖 AI-RULEZ :: GENERATED FILE\n\nbody\n", true},
		{"quoted marker in a heading is not a banner", ".claude/rules/x.md", "# GENERATED FILE\n\nbody\n", false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, tt.want, hasGeneratedBanner(tt.path, []byte(tt.content)))
		})
	}
}

func TestLineEndings_CRLF(t *testing.T) {
	t.Parallel()

	lf := "---\nalwaysApply: true\n---\n<!--\nGenerated by ai-rulez. Edit the source.\n-->\n\n# X\n\nBody.\n"
	crlf := strings.ReplaceAll(lf, "\n", "\r\n")
	path := ".cursor/rules/x.mdc"

	t.Run("banner detection", func(t *testing.T) {
		assert.True(t, hasGeneratedBanner(path, []byte(crlf)))
		assert.True(t, hasGeneratedBanner(path, []byte(strings.Replace(crlf, "\r\n<!--", "\r\n\r\n<!--", 1))))
	})
	t.Run("stripHeader returns the same body", func(t *testing.T) {
		assert.Equal(t, stripHeader(lf, path), strings.ReplaceAll(stripHeader(crlf, path), "\r\n", "\n"))
		assert.Equal(t, "# X\r\n\r\nBody.\r\n", stripHeader(crlf, path))
	})
	t.Run("injectIntoBanner keeps CRLF and finds the banner", func(t *testing.T) {
		got, ok := injectIntoBanner(crlf, "Content-Hash: abc")
		require.True(t, ok)
		assert.Contains(t, got, "Edit the source.\r\nContent-Hash: abc\r\n-->")
	})
	t.Run("unterminated frontmatter", func(t *testing.T) {
		_, ok := injectIntoBanner("---\r\nk: v\r\n<!--\r\n-->\r\n", "x")
		assert.False(t, ok)
	})
}

func TestStripHeader_BodyWithHTMLCommentEnd(t *testing.T) {
	t.Parallel()

	// Arrange: fenced HTML in the body contains "-->" and a blank line after it.
	body := "# X\n\n```html\n<!-- note -->\n\n<p>hi</p>\n```\n"
	for _, tt := range []struct{ name, content, path string }{
		{"md without banner", body, ".claude/rules/x.md"},
		{"mdc with frontmatter, no banner", "---\nalwaysApply: true\n---\n\n" + body, ".cursor/rules/x.mdc"},
		{"md with banner", "<!--\nGenerated by ai-rulez.\n-->\n\n" + body, ".claude/rules/x.md"},
	} {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, body, stripHeader(tt.content, tt.path), "only a leading banner is stripped")
		})
	}

	t.Run("second run is a no-op", func(t *testing.T) {
		dir := t.TempDir()
		rel := ".claude/rules/x.md"
		gen := NewGenerator(&config.Config{BaseDir: dir, SourceHash: "src"})
		out := config.OutputFile{Path: rel, Content: "<!--\nGenerated by ai-rulez.\n-->\n\n" + body}
		require.NoError(t, gen.writeOutputs([]config.OutputFile{out}))
		abs := filepath.Join(dir, rel)
		old := time.Unix(1_600_000_000, 0)
		require.NoError(t, os.Chtimes(abs, old, old))

		require.NoError(t, gen.writeOutputs([]config.OutputFile{out}))

		info, err := os.Stat(abs)
		require.NoError(t, err)
		assert.True(t, info.ModTime().Equal(old))
		data, err := os.ReadFile(abs)
		require.NoError(t, err)
		contentHash, _ := extractStoredHashes(abs)
		assert.Equal(t, templates.HashContent(stripHeader(string(data), rel)), contentHash)
	})
}
