package generator

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/Goldziher/ai-rulez/internal/templates"
)

// A heading-shaped "# title" line followed by a blank line inside a body (a
// TOML developer_instructions string, a YAML block scalar, markdown) must not
// be taken for the generated-file header: the hashes were injected there while
// stripHeader never strips it, so the freshly generated file read as hand-edited.
func TestHashRoundTrip_HeadingInsideBodyIsNotAHeader(t *testing.T) {
	tests := []struct {
		name    string
		path    string
		content string
	}{
		{
			name:    "toml multi-line string starting with a heading",
			path:    ".codex/agents/a.toml",
			content: "name = \"a\"\ndeveloper_instructions = \"\"\"\n# a\n\nYou maintain things.\n\"\"\"\n",
		},
		{
			name:    "yaml block scalar containing a comment-like line",
			path:    "out/a.yaml",
			content: "name: a\ninstructions: |\n  x\n# a\n\nother: 1\n",
		},
		{
			name:    "markdown with a heading",
			path:    "out/a.md",
			content: "<!--\nGenerated\n-->\n# a\n\nbody\n",
		},
		{
			name:    "mdc with frontmatter and a heading",
			path:    "out/a.mdc",
			content: "---\nalwaysApply: true\n---\n# a\n\nbody\n",
		},
		{
			name:    "toml with a real leading banner",
			path:    "out/b.toml",
			content: "# Generated by ai-rulez\n\nname = \"b\"\n",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Arrange
			hash := templates.HashContent(stripHeader(tt.content, tt.path))
			final := normalizeTrailingNewline(injectHashes(tt.content, tt.path, hash, "blake3:src"))
			path := filepath.Join(t.TempDir(), filepath.Base(tt.path))
			if err := os.WriteFile(path, []byte(final), 0o600); err != nil {
				t.Fatal(err)
			}

			// Act
			edited := bodyEdited(final, path)

			// Assert
			if edited {
				t.Fatalf("freshly generated %s reads as edited:\n%s", tt.path, final)
			}
		})
	}
}
