package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Goldziher/ai-rulez/internal/config"
	"github.com/Goldziher/ai-rulez/internal/generator/providers"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestDisambiguatedRuleName(t *testing.T) {
	t.Parallel()

	tests := []struct{ in, want string }{
		{".claude/rules/testing.md", ".claude/rules/testing.ai-rulez.md"},
		{".cursor/rules/testing.mdc", ".cursor/rules/testing.ai-rulez.mdc"},
		{".github/instructions/testing.instructions.md", ".github/instructions/testing.ai-rulez.instructions.md"},
		{"/abs/.claude/rules/a.b.md", "/abs/.claude/rules/a.b.ai-rulez.md"},
	}
	for _, tt := range tests {
		assert.Equal(t, tt.want, disambiguatedRuleName(tt.in), tt.in)
	}
}

func TestGenerate_HandWrittenCollision_WritesDisambiguatedRule(t *testing.T) {
	t.Parallel()

	dir := newWindsurfProject(t)
	rel := ".windsurf/rules/coding-style.md"
	alt := ".windsurf/rules/coding-style.ai-rulez.md"
	hand := seedRuleFile(t, dir, rel, "my own rule\n")

	var first string
	for run := 1; run <= 2; run++ {
		require.NoError(t, newWindsurfGenerator(t, dir).Generate("default"), "run %d", run)

		got, err := os.ReadFile(hand)
		require.NoError(t, err)
		assert.Equal(t, "my own rule\n", string(got), "hand-written file untouched on run %d", run)
		generated, err := os.ReadFile(filepath.Join(dir, alt))
		require.NoError(t, err, "the rule must reach the tool under another name")
		assert.Contains(t, string(generated), "Generated by ai-rulez")
		if run == 1 {
			first = string(generated)
		}
		assert.Equal(t, first, string(generated), "name and content are stable across runs")
	}

	manifest, err := os.ReadFile(filepath.Join(dir, ".ai-rulez", generatedManifestName))
	require.NoError(t, err)
	assert.Contains(t, string(manifest), alt)
	assert.NotContains(t, string(manifest), `"`+rel+`"`)
	ignore, err := os.ReadFile(filepath.Join(dir, ".gitignore"))
	require.NoError(t, err)
	assert.Contains(t, string(ignore), alt)
	assert.NotRegexp(t, `(?m)^`+strings.ReplaceAll(rel, ".", `\.`)+`$`, string(ignore))

	t.Run("dry run lists the disambiguated name only", func(t *testing.T) {
		plan, err := newWindsurfGenerator(t, dir).DryRun("default")
		require.NoError(t, err)
		assert.Contains(t, plan, "write-file: "+alt)
		assert.NotContains(t, plan, "write-file: "+rel)
	})

	t.Run("clean removes ours and keeps the hand-written file", func(t *testing.T) {
		_, err := newWindsurfGenerator(t, dir).Clean("default", CleanOptions{})
		require.NoError(t, err)
		assert.NoFileExists(t, filepath.Join(dir, alt))
		assert.FileExists(t, hand)
	})
}

func TestGenerate_CollisionGone_CleansDisambiguatedFile(t *testing.T) {
	t.Parallel()

	dir := newWindsurfProject(t)
	hand := seedRuleFile(t, dir, ".windsurf/rules/coding-style.md", "my own rule\n")
	require.NoError(t, newWindsurfGenerator(t, dir).Generate("default"))
	alt := filepath.Join(dir, ".windsurf/rules/coding-style.ai-rulez.md")
	require.FileExists(t, alt)

	require.NoError(t, os.Remove(hand))
	require.NoError(t, newWindsurfGenerator(t, dir).Generate("default"))

	assert.NoFileExists(t, alt)
	assert.FileExists(t, hand)
	got, err := os.ReadFile(hand)
	require.NoError(t, err)
	assert.Contains(t, string(got), "Generated by ai-rulez")
}

func TestDryRun_OmitsGuardSkippedFiles(t *testing.T) {
	t.Parallel()

	// A hand-written *.local.* file in a rules folder is reserved and never
	// disambiguated; the guard skips it, so a dry run must not announce a write.
	gen := &Generator{config: &config.Config{BaseDir: t.TempDir()}}
	seedRuleFile(t, gen.config.BaseDir, ".claude/rules/mine.local.md", "hand written\n")
	outputs := []config.OutputFile{
		{Path: ".claude/rules/mine.local.md", Content: "x\n", LocalOnly: true},
		{Path: ".claude/rules/fresh.md", Content: "y\n"},
	}

	got := gen.planLines(outputs)

	assert.Equal(t, []string{"write-file: .claude/rules/fresh.md"}, got)
}

func TestWriteOutput_Recognizes421CursorRuleFiles(t *testing.T) {
	t.Parallel()

	// 4.21.0 wrote .cursor/rules/*.mdc as frontmatter plus "# Name" with no
	// banner; with [header] hashes = "none" nothing in the file identifies it,
	// so only the committed manifest can. With hashes it carried YAML-comment
	// hashes inside the frontmatter.
	const bare = "---\nalwaysApply: true\n---\n\n# Style\n\nOld body.\n"
	const hashed = "---\nalwaysApply: true\n# Content-Hash: blake3:old\n# Source-Hash: blake3:src\n---\n\n# Style\n\nOld body.\n"
	rel := ".cursor/rules/style.mdc"
	tests := []struct {
		name     string
		existing string
		manifest bool
		skipped  bool
	}{
		{"hashes none, listed in the manifest", bare, true, false},
		{"frontmatter hashes, no manifest", hashed, false, false},
		{"hashes none, no manifest: indistinguishable from hand-written", bare, false, true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			dir := t.TempDir()
			seedRuleFile(t, dir, rel, tt.existing)
			if tt.manifest {
				writeManifest(t, dir, rel)
			}
			gen := &Generator{config: &config.Config{BaseDir: dir, SourceHash: "blake3:test",
				Header: &config.HeaderConfig{Hashes: config.HeaderHashesNone}}, skippedPaths: map[string]bool{}}

			require.NoError(t, gen.writeOutput(config.OutputFile{Path: rel, Content: "---\nalwaysApply: true\n---\n\n# Style\n\nNew body.\n"}))

			assert.Equal(t, tt.skipped, gen.skippedPaths[rel])
		})
	}
}

func TestCustomSplitProvider_GetsRulesFolderProtections(t *testing.T) {
	// Not parallel: loading a spec registers its folder process-wide.
	spec := "name = \"w3\"\n[root]\nfile = \"W3.md\"\nsections = [\"rules_inline\"]\n" +
		"[outputs.rules]\nmode = \"per_item_file\"\ndir = \".w3-gen/rules\"\nfilename = \"{id}.md\"\n" +
		"split = true\ndialect = \"claude\"\n"
	t.Cleanup(func() { config.UnregisterRulesDir(".w3-gen/rules") })
	_, err := providers.LoadProviderSpec([]byte(spec), "w3.toml", providers.FormatTOML)
	require.NoError(t, err)
	dir := t.TempDir()
	rel := ".w3-gen/rules/x.md"
	seedRuleFile(t, dir, rel, "hand written\n")
	gen := &Generator{config: &config.Config{BaseDir: dir, SourceHash: "blake3:test"}}

	assert.True(t, gen.isUnmanagedRuleFile(filepath.Join(dir, rel), "generated\n"), "overwrite guard applies")
	assert.Equal(t, rel, gitignorePatternForOutput(rel, false), "ignored per file, not the folder")
	out := injectHashes("---\nk: v\n---\n<!--\nGenerated by ai-rulez.\n-->\n\nbody\n", rel, "abc", "def")
	assert.Contains(t, out[strings.Index(out, "-->")-40:], "Content-Hash: abc", "hashes go into the banner")
}
