package generator

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/Goldziher/ai-rulez/v5/internal/config"
	"github.com/Goldziher/ai-rulez/v5/internal/testutil"
)

func generateProjectErr(t *testing.T, dir string) error {
	t.Helper()
	cfg, err := config.LoadConfig(context.Background(), dir)
	require.NoError(t, err)
	require.NoError(t, cfg.Validate())
	return NewGenerator(cfg).Generate("default")
}

func rawGenerator(t *testing.T, base string) *Generator {
	t.Helper()
	return NewGenerator(&config.Config{BaseDir: base})
}

func TestWrite_RefusesSymlinkTargetsOutsideTheProject(t *testing.T) {
	quietWarnings(t)
	tests := []struct {
		name  string
		setup func(t *testing.T, dir, outside string) (victim string)
		write func(t *testing.T, dir string) error
	}{
		{"dangling link to a file outside", func(t *testing.T, dir, outside string) string {
			victim := filepath.Join(outside, "victim")
			testutil.SymlinkOrSkip(t, victim, filepath.Join(dir, "CLAUDE.md"))
			return victim
		}, func(t *testing.T, dir string) error { return generateProjectErr(t, dir) }},
		{"link to an existing outside file carrying a generated banner", func(t *testing.T, dir, outside string) string {
			victim := filepath.Join(outside, "victim")
			require.NoError(t, os.WriteFile(victim, []byte("Generated by ai-rulez\n"), 0o600))
			testutil.SymlinkOrSkip(t, victim, filepath.Join(dir, "CLAUDE.md"))
			return victim
		}, func(t *testing.T, dir string) error { return generateProjectErr(t, dir) }},
		{"symlinked parent directory outside", func(t *testing.T, dir, outside string) string {
			testutil.SymlinkOrSkip(t, outside, filepath.Join(dir, ".claude"))
			return filepath.Join(outside, "skills", "alpha", "SKILL.md")
		}, func(t *testing.T, dir string) error { return generateProjectErr(t, dir) }},
		{"raw output through a dangling link", func(t *testing.T, dir, outside string) string {
			victim := filepath.Join(outside, "victim")
			require.NoError(t, os.MkdirAll(filepath.Join(dir, "hooks"), 0o755))
			testutil.SymlinkOrSkip(t, victim, filepath.Join(dir, "hooks", "TaskStart"))
			return victim
		}, func(t *testing.T, dir string) error {
			return rawGenerator(t, dir).writeOutput(config.OutputFile{
				Path: "hooks/TaskStart", RawContent: []byte("#!/bin/sh\n"), Mode: 0o755})
		}},
		{"raw output through a symlinked parent", func(t *testing.T, dir, outside string) string {
			testutil.SymlinkOrSkip(t, outside, filepath.Join(dir, ".clinerules"))
			return filepath.Join(outside, "hooks", "TaskStart")
		}, func(t *testing.T, dir string) error {
			return rawGenerator(t, dir).writeOutput(config.OutputFile{
				Path: ".clinerules/hooks/TaskStart", RawContent: []byte("#!/bin/sh\n"), Mode: 0o755})
		}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Arrange
			dir := hashesProject(t, "")
			outside := t.TempDir()
			victim := tt.setup(t, dir, outside)
			before, statErr := os.Stat(victim)

			// Act
			err := tt.write(t, dir)

			// Assert
			require.Error(t, err)
			assert.Contains(t, err.Error(), "outside")
			after, afterErr := os.Stat(victim)
			if statErr != nil {
				assert.True(t, os.IsNotExist(afterErr), "the victim must not be created")
				return
			}
			require.NoError(t, afterErr)
			assert.Equal(t, before.Mode(), after.Mode(), "mode untouched")
			data, readErr := os.ReadFile(victim)
			require.NoError(t, readErr)
			assert.Equal(t, "Generated by ai-rulez\n", string(data))
		})
	}
}

func TestWrite_FollowsASymlinkThatStaysInsideTheProject(t *testing.T) {
	quietWarnings(t)
	// Arrange
	dir := hashesProject(t, "")
	require.NoError(t, os.MkdirAll(filepath.Join(dir, "docs"), 0o755))
	target := filepath.Join(dir, "docs", "claude.md")
	link := filepath.Join(dir, "CLAUDE.md")
	testutil.SymlinkOrSkip(t, "docs/claude.md", link)

	// Act
	err := generateProjectErr(t, dir)

	// Assert
	require.NoError(t, err)
	info, lerr := os.Lstat(link)
	require.NoError(t, lerr)
	assert.NotZero(t, info.Mode()&os.ModeSymlink, "the link survives")
	data, rerr := os.ReadFile(target)
	require.NoError(t, rerr)
	assert.Contains(t, string(data), "GENERATED FILE")
}

func TestWriteRaw_NeverChangesTheModeOfAFileItDidNotCreate(t *testing.T) {
	quietWarnings(t)
	// Arrange
	dir := t.TempDir()
	real := filepath.Join(dir, "real")
	require.NoError(t, os.WriteFile(real, []byte("old"), 0o600))
	testutil.SymlinkOrSkip(t, "real", filepath.Join(dir, "linked"))

	// Act
	err := rawGenerator(t, dir).writeOutput(config.OutputFile{Path: "linked", RawContent: []byte("new"), Mode: 0o755})

	// Assert
	require.NoError(t, err)
	info, serr := os.Stat(real)
	require.NoError(t, serr)
	assert.Equal(t, os.FileMode(0o600), info.Mode().Perm())
	data, rerr := os.ReadFile(real)
	require.NoError(t, rerr)
	assert.Equal(t, "new", string(data))
}

func TestWriteRaw_AppliesTheModeToAFileItCreates(t *testing.T) {
	// Arrange
	dir := t.TempDir()

	// Act
	err := rawGenerator(t, dir).writeOutput(config.OutputFile{Path: "hooks/run", RawContent: []byte("x"), Mode: 0o755})

	// Assert
	require.NoError(t, err)
	info, serr := os.Stat(filepath.Join(dir, "hooks", "run"))
	require.NoError(t, serr)
	assert.Equal(t, os.FileMode(0o755), info.Mode().Perm())
}

func TestWrite_ManifestThroughALinkOutsideIsRefused(t *testing.T) {
	// Arrange
	dir := t.TempDir()
	g := rawGenerator(t, dir)
	outside := t.TempDir()
	victim := filepath.Join(outside, "victim")
	require.NoError(t, os.MkdirAll(filepath.Dir(g.manifestPath()), 0o755))
	testutil.SymlinkOrSkip(t, victim, g.manifestPath())

	// Act
	_, _, err := g.guardWrite(g.manifestPath())

	// Assert
	require.Error(t, err)
	assert.NoFileExists(t, victim)
}

func TestUser_RefusesOutputLinkedOutsideHome(t *testing.T) {
	quietWarnings(t)
	// Arrange
	home, gen := newUserHome(t, claudeOnlyConfig, userFixture())
	outside := t.TempDir()
	victim := filepath.Join(outside, "victim")
	require.NoError(t, os.WriteFile(victim, []byte("keep"), 0o600))
	require.NoError(t, os.MkdirAll(filepath.Join(home, ".claude"), 0o755))
	testutil.SymlinkOrSkip(t, victim, filepath.Join(home, ".claude", "CLAUDE.md"))

	// Act
	_, err := gen.GenerateUser("")

	// Assert
	data, rerr := os.ReadFile(victim)
	require.NoError(t, rerr)
	assert.Equal(t, "keep", string(data), "the file outside the home directory is untouched")
	if err != nil {
		assert.Contains(t, err.Error(), "outside")
	}
}

func TestWrite_FailsClosedOutsideScopeAndInsideGitDir(t *testing.T) {
	quietWarnings(t)
	tests := []struct {
		name string
		path func(dir, outside string) string
	}{
		{"parent traversal", func(dir, outside string) string { return "../" + filepath.Base(outside) + "/escaped.md" }},
		{"git config", func(string, string) string { return ".git/config" }},
		{"nested git hook", func(string, string) string { return "sub/.GIT/hooks/post-checkout" }},
		{"git dir spelled with a trailing dot", func(string, string) string { return ".git./config" }},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Arrange
			dir := t.TempDir()
			outside := t.TempDir()
			require.NoError(t, os.MkdirAll(filepath.Join(dir, ".git"), 0o755))
			gitConfig := filepath.Join(dir, ".git", "config")
			require.NoError(t, os.WriteFile(gitConfig, []byte("[core]\n"), 0o600))

			// Act
			err := rawGenerator(t, dir).writeOutput(config.OutputFile{Path: tt.path(dir, outside), Content: "[core]\n\tfsmonitor = echo PWNED\n"})

			// Assert
			require.Error(t, err)
			got, readErr := os.ReadFile(gitConfig)
			require.NoError(t, readErr)
			assert.Equal(t, "[core]\n", string(got))
			entries, dirErr := os.ReadDir(outside)
			require.NoError(t, dirErr)
			assert.Empty(t, entries)
		})
	}
}
